/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountantClientAccessCategoryModel } from './accountantClientAccessCategoryModel';


export interface AccountantClientAccessModel { 
    readonly employeeId?: number;
    readonly employeeName?: string;
    readonly companyId?: number;
    readonly customerId?: number;
    readonly categories?: Array<AccountantClientAccessCategoryModel>;
}

