/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Posting } from './posting';


export interface AccountInfo { 
    account?: Account;
    accountName: string;
    accountNumber: number;
    readonly balanceIn?: number;
    readonly balanceOut?: number;
    readonly sumAmount?: number;
    readonly optionsCollectionId?: number;
    /**
     * Link to postings on this account.
     */
    readonly postings?: Array<Posting>;
}

