/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { AccountSuggestion } from './accountSuggestion';


export interface AccountWithHelpInfo { 
    readonly id?: number;
    readonly displayName?: string;
    readonly numberPretty?: string;
    readonly description?: string;
    account?: Account;
    accountHelp?: AccountSuggestion;
}

