/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface Activity { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    name?: string;
    number?: string;
    description?: string;
    /**
     * PROJECT_SPECIFIC_ACTIVITY are made via project/projectActivity, as they must be part of a project.
     */
    activityType: Activity.ActivityTypeEnum;
    /**
     * Manipulate these with ActivityType
     */
    readonly isProjectActivity?: boolean;
    /**
     * Manipulate these with ActivityType
     */
    readonly isGeneral?: boolean;
    /**
     * Manipulate these with ActivityType
     */
    readonly isTask?: boolean;
    readonly isDisabled?: boolean;
    isChargeable?: boolean;
    rate?: number;
    costPercentage?: number;
    displayName?: string;
    readonly deletable?: boolean;
}
export namespace Activity {
    export type ActivityTypeEnum = 'GENERAL_ACTIVITY' | 'PROJECT_GENERAL_ACTIVITY' | 'PROJECT_SPECIFIC_ACTIVITY' | 'TASK';
    export const ActivityTypeEnum = {
        GeneralActivity: 'GENERAL_ACTIVITY' as ActivityTypeEnum,
        ProjectGeneralActivity: 'PROJECT_GENERAL_ACTIVITY' as ActivityTypeEnum,
        ProjectSpecificActivity: 'PROJECT_SPECIFIC_ACTIVITY' as ActivityTypeEnum,
        Task: 'TASK' as ActivityTypeEnum
    };
}


