/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivityBuilder { 
    companyId?: number;
    name?: string;
    description?: string;
    number?: number;
    general?: boolean;
    projectActivity?: boolean;
    allowTimetracking?: boolean;
    task?: boolean;
    crm?: boolean;
    chargeable?: boolean;
    disabled?: boolean;
}

