/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnualAccountsSubTotalLine } from './annualAccountsSubTotalLine';


export interface AnnualAccountsSubTotalSection { 
    name?: string;
    readonly sumOpeningBalance?: number;
    readonly sumClosingBalance?: number;
    subTotalLines?: Array<AnnualAccountsSubTotalLine>;
}

