/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnnualAccountsSubTotalLine { 
    readonly orid?: string;
    readonly grouping?: string;
    readonly name?: string;
    readonly technicalName?: string;
    readonly info?: string;
    readonly closingBalance?: number;
    readonly openingBalance?: number;
    readonly notes?: string;
    readonly freeNotes?: string;
}

