/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiValidationMessage } from './apiValidationMessage';


export interface ApiError { 
    status?: number;
    code?: number;
    message?: string;
    link?: string;
    developerMessage?: string;
    validationMessages?: Array<ApiValidationMessage>;
    requestId?: string;
}

