/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArchiveModelTypes { 
    readonly supplier?: boolean;
    readonly customer?: boolean;
    readonly project?: boolean;
    readonly order?: boolean;
    readonly offer?: boolean;
    readonly product?: boolean;
    readonly employee?: boolean;
    readonly account?: boolean;
    readonly asset?: boolean;
}

