/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Asset } from './asset';


export interface AssetGroup { 
    readonly id?: number;
    readonly description?: string;
    readonly assetCount?: number;
    readonly acquisitionCostSum?: number;
    readonly balanceInSum?: number;
    readonly balanceOutSum?: number;
    readonly balanceChangeSum?: number;
    readonly assets?: Array<Asset>;
    readonly startingBalance?: number;
    readonly balanceInAccount?: number;
    readonly sumStartingBalance?: number;
}

