/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';


export interface AssetDepreciationSpecification { 
    /**
     * Asset id
     */
    assetId: number;
    /**
     * For STRAIGHT_LINE: the total amount to write off.  FOR TAX_RELATED: the base amount to calculate the write off amounts from.  Not used for CUSTOM
     */
    amount: number;
    balanceAccount: Account;
    depreciationAccount: Account;
    /**
     * The depreciation period in months.
     */
    noOfMonths: number;
    /**
     * The depreciation method.
     */
    depreciationMethod: AssetDepreciationSpecification.DepreciationMethodEnum;
    /**
     * The start date for the depreciation. This will also be the voucher date
     */
    startDate: string;
    /**
     * The monthly amount to write off.  Only used for CUSTOM
     */
    customMonthlyWriteOffAmount?: number;
    /**
     * How many percent to depreciate for each year.  Only used for TAX_RELATED
     */
    taxRelatedDepreciationPercentage?: number;
    /**
     * HdddddiiifffD
     */
    diff?: number;
    /**
     * How many percent to depreciate for each year.  Only used for TAX_RELATED
     */
    depreciationRate?: number;
}
export namespace AssetDepreciationSpecification {
    export type DepreciationMethodEnum = 'MANUAL' | 'TAX_RELATED' | 'STRAIGHT_LINE' | 'CUSTOMIZED_AMOUNT' | 'NO_DEPRECIATION';
    export const DepreciationMethodEnum = {
        Manual: 'MANUAL' as DepreciationMethodEnum,
        TaxRelated: 'TAX_RELATED' as DepreciationMethodEnum,
        StraightLine: 'STRAIGHT_LINE' as DepreciationMethodEnum,
        CustomizedAmount: 'CUSTOMIZED_AMOUNT' as DepreciationMethodEnum,
        NoDepreciation: 'NO_DEPRECIATION' as DepreciationMethodEnum
    };
}


