/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AutoPayTransactionBuilder { 
    companyId?: number;
    amountCurrency?: number;
    currencyId?: number;
    isSalary?: boolean;
    statusId?: number;
    internalStatus?: number;
    creditorBic?: string;
    regulatoryReportingCode?: number;
    regulatoryReportingInfo?: number;
    bookingDate?: string;
    paymentDate?: string;
    autopayName?: string;
}

