/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AutoPaySupport { 
    id?: number;
    uploadNeeded?: boolean;
    isEikaType?: boolean;
    hasOrgNumber?: boolean;
    isPsd2Type?: boolean;
    hasApproveInOnlineBanking?: boolean;
    requiredBankFieldIds?: Array<number>;
}

