/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AutomationSettingsDTO { 
    canAccessAutoPay?: boolean;
    canAccessFabricAi?: boolean;
    canAccessFabricAiTraining?: boolean;
    canAddAutoPayPayments?: boolean;
    canAccessWelcomeBanner?: boolean;
    hasBookkeepingBeforeAttestationSetting?: boolean;
    hasVoucherApprovalModule?: boolean;
    testAccount?: boolean;
}

