/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BalanceSheetSettingsDTO { 
    readonly showEmployeeModule?: boolean;
    showDepartmentModule?: boolean;
    showProductModule?: boolean;
}

