/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BalanceSheetRow { 
    readonly accountId?: number;
    readonly accountNumber?: number;
    readonly accountName?: string;
    readonly postingCount?: number;
    readonly balanceIn?: number;
    readonly balanceChange?: number;
    readonly balanceOut?: number;
}

