/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface BankBalanceEstimation { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    date?: string;
    /**
     * java.lang.String
     */
    description: string;
    voucherId?: number;
    invoiceId?: number;
    invoiceNumber?: string;
    /**
     * java.math.BigDecimal
     */
    invoiceAmount?: number;
    /**
     * boolean
     */
    isIncomingInvoice?: boolean;
    /**
     * Recurrence type
     */
    recurrence: BankBalanceEstimation.RecurrenceEnum;
    /**
     * Category
     */
    category: BankBalanceEstimation.CategoryEnum;
    vendorOrCustomerName?: string;
    /**
     * boolean
     */
    isManuallyAdded?: boolean;
    batchId?: string;
}
export namespace BankBalanceEstimation {
    export type RecurrenceEnum = 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
    export const RecurrenceEnum = {
        None: 'NONE' as RecurrenceEnum,
        Daily: 'DAILY' as RecurrenceEnum,
        Weekly: 'WEEKLY' as RecurrenceEnum,
        Monthly: 'MONTHLY' as RecurrenceEnum
    };
    export type CategoryEnum = 'DUPLICATE' | 'STARTING_BALANCE' | 'NONE' | 'SALARY' | 'ENI' | 'TAX' | 'VAT_RETURNS' | 'VACATION_ALLOWANCE' | 'TRAVEL_AND_EXPENSES';
    export const CategoryEnum = {
        Duplicate: 'DUPLICATE' as CategoryEnum,
        StartingBalance: 'STARTING_BALANCE' as CategoryEnum,
        None: 'NONE' as CategoryEnum,
        Salary: 'SALARY' as CategoryEnum,
        Eni: 'ENI' as CategoryEnum,
        Tax: 'TAX' as CategoryEnum,
        VatReturns: 'VAT_RETURNS' as CategoryEnum,
        VacationAllowance: 'VACATION_ALLOWANCE' as CategoryEnum,
        TravelAndExpenses: 'TRAVEL_AND_EXPENSES' as CategoryEnum
    };
}


