/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BankTransactionBuilder { 
    companyId?: number;
    bankStatementId?: number;
    postedDate?: string;
    description?: string;
    amountCurrency?: number;
    accountId?: number;
}

