/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AutoPaySupport } from './autoPaySupport';
import { Change } from './change';


export interface Bank { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Bank name
     */
    readonly name?: string;
    /**
     * Bank statement file formats supported.
     */
    readonly bankStatementFileFormatSupport?: Array<Bank.BankStatementFileFormatSupportEnum>;
    /**
     * Register numbers belonging to bank.
     */
    readonly registerNumbers?: Array<number>;
    /**
     * Bank name to comply with LoadableDropdown
     */
    readonly displayName?: string;
    autoPaySupport?: AutoPaySupport;
    /**
     * Bank platform
     */
    readonly platform?: Bank.PlatformEnum;
}
export namespace Bank {
    export type BankStatementFileFormatSupportEnum = 'DNB_CSV' | 'EIKA_TELEPAY' | 'SPAREBANK1_TELEPAY' | 'VISMA_ACCOUNT_STATEMENT' | 'HANDELSBANKEN_TELEPAY' | 'SPAREBANKEN_VEST_TELEPAY' | 'NORDEA_CSV' | 'TRANSFERWISE' | 'SPAREBANKEN_SOR_TELEPAY' | 'SPAREBANKEN_OST_TELEPAY' | 'DANSKE_BANK_CSV' | 'CULTURA_BANK_TELEPAY' | 'SBANKEN_PRIVAT_CSV' | 'HAUGESUND_SPAREBANK_CSV' | 'VISMA_ACCOUNT_STATEMENT_PSD2' | 'SBANKEN_BEDRIFT_CSV' | 'LANDKREDITT_TELEPAY' | 'ZTL';
    export const BankStatementFileFormatSupportEnum = {
        DnbCsv: 'DNB_CSV' as BankStatementFileFormatSupportEnum,
        EikaTelepay: 'EIKA_TELEPAY' as BankStatementFileFormatSupportEnum,
        Sparebank1Telepay: 'SPAREBANK1_TELEPAY' as BankStatementFileFormatSupportEnum,
        VismaAccountStatement: 'VISMA_ACCOUNT_STATEMENT' as BankStatementFileFormatSupportEnum,
        HandelsbankenTelepay: 'HANDELSBANKEN_TELEPAY' as BankStatementFileFormatSupportEnum,
        SparebankenVestTelepay: 'SPAREBANKEN_VEST_TELEPAY' as BankStatementFileFormatSupportEnum,
        NordeaCsv: 'NORDEA_CSV' as BankStatementFileFormatSupportEnum,
        Transferwise: 'TRANSFERWISE' as BankStatementFileFormatSupportEnum,
        SparebankenSorTelepay: 'SPAREBANKEN_SOR_TELEPAY' as BankStatementFileFormatSupportEnum,
        SparebankenOstTelepay: 'SPAREBANKEN_OST_TELEPAY' as BankStatementFileFormatSupportEnum,
        DanskeBankCsv: 'DANSKE_BANK_CSV' as BankStatementFileFormatSupportEnum,
        CulturaBankTelepay: 'CULTURA_BANK_TELEPAY' as BankStatementFileFormatSupportEnum,
        SbankenPrivatCsv: 'SBANKEN_PRIVAT_CSV' as BankStatementFileFormatSupportEnum,
        HaugesundSparebankCsv: 'HAUGESUND_SPAREBANK_CSV' as BankStatementFileFormatSupportEnum,
        VismaAccountStatementPsd2: 'VISMA_ACCOUNT_STATEMENT_PSD2' as BankStatementFileFormatSupportEnum,
        SbankenBedriftCsv: 'SBANKEN_BEDRIFT_CSV' as BankStatementFileFormatSupportEnum,
        LandkredittTelepay: 'LANDKREDITT_TELEPAY' as BankStatementFileFormatSupportEnum,
        Ztl: 'ZTL' as BankStatementFileFormatSupportEnum
    };
    export type PlatformEnum = 'UNKNOWN' | 'TIETO_EVRY' | 'SDC' | 'INDEPENDENT';
    export const PlatformEnum = {
        Unknown: 'UNKNOWN' as PlatformEnum,
        TietoEvry: 'TIETO_EVRY' as PlatformEnum,
        Sdc: 'SDC' as PlatformEnum,
        Independent: 'INDEPENDENT' as PlatformEnum
    };
}


