/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankOnboardingStep } from './bankOnboardingStep';


export interface BankOnboardingDTO { 
    readonly steps?: Array<BankOnboardingStep>;
    readonly hasFullAccess?: boolean;
    readonly companyOrgnr?: string;
    readonly autoPayTwoFAEnabled?: boolean;
    readonly lockedCurrenciesMap?: { [key: string]: boolean; };
    readonly userIsAutoPayProvisioned?: boolean;
}

