/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankTransaction } from './bankTransaction';
import { Account } from './account';
import { BankReconciliationMatch } from './bankReconciliationMatch';
import { Posting } from './posting';
import { BankReconciliationPaymentType } from './bankReconciliationPaymentType';


export interface BankReconciliationAdjustment { 
    paymentType?: BankReconciliationPaymentType;
    bankTransactions?: Array<BankTransaction>;
    postingDate?: string;
    amount?: number;
    postings?: Array<Posting>;
    bankReconciliationMatch?: BankReconciliationMatch;
    date?: string;
    description?: string;
    interimAccount?: Account;
    voucherNumber?: string;
    voucherViewLink?: string;
    voucherDetailsLink?: string;
}

