/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankTransaction } from './bankTransaction';
import { Posting } from './posting';
import { Change } from './change';
import { BankReconciliation } from './bankReconciliation';


export interface BankReconciliationMatch { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    bankReconciliation: BankReconciliation;
    /**
     * Type of match, MANUAL and APPROVED_SUGGESTION are considered part of reconciliation.
     */
    type?: BankReconciliationMatch.TypeEnum;
    /**
     * Match transactions
     */
    transactions?: Array<BankTransaction>;
    /**
     * Match postings
     */
    postings?: Array<Posting>;
}
export namespace BankReconciliationMatch {
    export type TypeEnum = 'MANUAL' | 'PENDING_SUGGESTION' | 'REJECTED_SUGGESTION' | 'APPROVED_SUGGESTION' | 'ADJUSTMENT' | 'AUTO_MATCHED' | 'REJECTED_AUTO_MATCH';
    export const TypeEnum = {
        Manual: 'MANUAL' as TypeEnum,
        PendingSuggestion: 'PENDING_SUGGESTION' as TypeEnum,
        RejectedSuggestion: 'REJECTED_SUGGESTION' as TypeEnum,
        ApprovedSuggestion: 'APPROVED_SUGGESTION' as TypeEnum,
        Adjustment: 'ADJUSTMENT' as TypeEnum,
        AutoMatched: 'AUTO_MATCHED' as TypeEnum,
        RejectedAutoMatch: 'REJECTED_AUTO_MATCH' as TypeEnum
    };
}


