/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface BankDashboardAdvice { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * The advice type.
     */
    adviceType?: BankDashboardAdvice.AdviceTypeEnum;
    /**
     * The advice is active.
     */
    isActive?: boolean;
    /**
     * The date the advice was updated.
     */
    dateUpdated?: string;
    /**
     * The advice has been cancelled.
     */
    isCancelled?: boolean;
    /**
     * The date the advice has been cancelled by the user.
     */
    dateCancelled?: string;
}
export namespace BankDashboardAdvice {
    export type AdviceTypeEnum = 'SHORTEN_DUE_DATE_ON_OUTGOING_INVOICES_TO_CUSTOMERS' | 'INCREASE_DUE_DATE_ON_INCOMING_INVOICES_FROM_VENDORS' | 'APPLY_FOR_CASH_CREDIT_WITH_TRIPLETEX_APRILA';
    export const AdviceTypeEnum = {
        ShortenDueDateOnOutgoingInvoicesToCustomers: 'SHORTEN_DUE_DATE_ON_OUTGOING_INVOICES_TO_CUSTOMERS' as AdviceTypeEnum,
        IncreaseDueDateOnIncomingInvoicesFromVendors: 'INCREASE_DUE_DATE_ON_INCOMING_INVOICES_FROM_VENDORS' as AdviceTypeEnum,
        ApplyForCashCreditWithTripletexAprila: 'APPLY_FOR_CASH_CREDIT_WITH_TRIPLETEX_APRILA' as AdviceTypeEnum
    };
}


