/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface BankReconciliationSettings { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * The number of matches showed per page in bank reconciliation.
     */
    numberOfMatchesPerPage: BankReconciliationSettings.NumberOfMatchesPerPageEnum;
}
export namespace BankReconciliationSettings {
    export type NumberOfMatchesPerPageEnum = 'ITEMS_10' | 'ITEMS_50' | 'ITEMS_100' | 'ITEMS_500' | 'ITEMS_1000' | 'ITEMS_5000' | 'ITEMS_10000';
    export const NumberOfMatchesPerPageEnum = {
        Items10: 'ITEMS_10' as NumberOfMatchesPerPageEnum,
        Items50: 'ITEMS_50' as NumberOfMatchesPerPageEnum,
        Items100: 'ITEMS_100' as NumberOfMatchesPerPageEnum,
        Items500: 'ITEMS_500' as NumberOfMatchesPerPageEnum,
        Items1000: 'ITEMS_1000' as NumberOfMatchesPerPageEnum,
        Items5000: 'ITEMS_5000' as NumberOfMatchesPerPageEnum,
        Items10000: 'ITEMS_10000' as NumberOfMatchesPerPageEnum
    };
}


