/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankTransaction } from './bankTransaction';
import { Bank } from './bank';
import { Change } from './change';


export interface BankStatement { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Opening balance on the account.
     */
    readonly openingBalanceCurrency?: number;
    /**
     * Closing balance on the account.
     */
    readonly closingBalanceCurrency?: number;
    /**
     * Bank statement file name.
     */
    readonly fileName?: string;
    bank?: Bank;
    readonly fromDate?: string;
    readonly toDate?: string;
    /**
     * Bank transactions tied to the bank statement
     */
    readonly transactions?: Array<BankTransaction>;
}

