/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Customer } from './customer';
import { Currency } from './currency';
import { Supplier } from './supplier';
import { Voucher } from './voucher';


export interface BankTransactionPosting { 
    voucher?: Voucher;
    date?: string;
    description?: string;
    account?: Account;
    customer?: Customer;
    supplier?: Supplier;
    amount?: number;
    amountCurrency?: number;
    currency?: Currency;
    invoiceNumber?: string;
    postingMatchType?: BankTransactionPosting.PostingMatchTypeEnum;
}
export namespace BankTransactionPosting {
    export type PostingMatchTypeEnum = 'DEFAULT' | 'INTERNAL_TRANSFER' | 'WAGE' | 'TAX' | 'VAT';
    export const PostingMatchTypeEnum = {
        Default: 'DEFAULT' as PostingMatchTypeEnum,
        InternalTransfer: 'INTERNAL_TRANSFER' as PostingMatchTypeEnum,
        Wage: 'WAGE' as PostingMatchTypeEnum,
        Tax: 'TAX' as PostingMatchTypeEnum,
        Vat: 'VAT' as PostingMatchTypeEnum
    };
}


