/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BetaProgramDTO { 
    name?: string;
    titleKey?: string;
    summaryKey?: string;
    descriptionActivationKey?: string;
    descriptionDeactivationKey?: string;
    state?: BetaProgramDTO.StateEnum;
}
export namespace BetaProgramDTO {
    export type StateEnum = 'ACTIVE' | 'AVAILABLE' | 'NOT_AVAILABLE';
    export const StateEnum = {
        Active: 'ACTIVE' as StateEnum,
        Available: 'AVAILABLE' as StateEnum,
        NotAvailable: 'NOT_AVAILABLE' as StateEnum
    };
}


