/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';


export interface CancelResponseDTO { 
    /**
     * The redirect URL to ZTL SCA for cancelling the payment
     */
    readonly redirectUrl?: string;
    /**
     * Was the cancellation successful?
     */
    readonly cancellationSuccessful?: boolean;
    paymentToBeCancelled?: Payment;
}

