/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangeLogEmployee { 
    readonly id?: number;
    readonly url?: string;
    readonly pictureId?: number;
    readonly name?: string;
    readonly number?: string;
    actualEmployee?: ChangeLogEmployee;
}

