/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Employee } from './employee';


export interface Checkout { 
    proxyOrClient?: boolean;
    payingCustomer?: boolean;
    company: Company;
    employee: Employee;
    /**
     * Returns whether the company category is paying.
     */
    isPayingCustomer?: boolean;
    /**
     * Returns whether employee is proxy or not
     */
    isProxyOrClient?: boolean;
}

