/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientContext { 
    /**
     * Whether the current session is in a trial account
     */
    trial?: boolean;
    /**
     * Whether the current session has access to the year-end module
     */
    subscribed?: boolean;
    /**
     * Whether the current session has access to development features
     */
    devMode?: boolean;
    /**
     * Whether the current session has access to pilot features
     */
    pilotMode?: boolean;
    /**
     * Whether the current session is a proxy for an accountant
     */
    activeAccountantProxy?: boolean;
    /**
     * Whether the current session is a Tripletex employee with extra privileges
     */
    hackedOrSupportAccess?: boolean;
    /**
     * The category of the company which is selected in the current session
     */
    companyTypeId?: number;
    /**
     * The id of the company which is selected in the current session
     */
    companyId?: number;
    /**
     * The name of the company which is selected in the current session
     */
    companyName?: string;
}

