/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientInbox { 
    readonly clientId?: number;
    readonly clientName?: string;
    readonly customerId?: number;
    readonly authorized?: boolean;
    readonly inboxCount?: number;
    readonly url?: string;
}

