/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommentInput { 
    /**
     * The comment
     */
    comment: string;
    /**
     * Is this comment a structured comment? It must be in a predefined list from Skatteetaten
     */
    isStructured?: boolean;
    /**
     * The id of the vatReturns
     */
    vatReturnsId?: number;
}

