/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { Change } from './change';


export interface Comment { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    readonly comment?: string;
    readonly createdAt?: string;
    readonly editedAt?: string;
    readonly voucherId?: number;
    employee?: Employee;
    readonly actualEmployeeId?: number;
    readonly actualEmployeeCompanyId?: number;
    readonly actualEmployeeName?: string;
}

