/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericDataOverview } from './genericDataOverview';


export interface CommercialVehicle { 
    yearEndReport?: YearEndReport;
    readonly sumExpenses?: number;
    readonly accountedValue?: number;
    readonly groupedAccountedValue?: number;
    readonly amountToBePostedOnAccount?: number;
    genericDataOverviews?: Array<GenericDataOverview>;
}

