/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyChooserCompany { 
    readonly url?: string;
    readonly displayName?: string;
    parent?: CompanyChooserCompany;
    readonly id?: number;
    readonly isSuspended?: boolean;
}

