/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface CompanyHoliday { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    year?: number;
    days?: number;
    vacationPayPercentage1?: number;
    vacationPayPercentage2?: number;
    isMaxPercentage2Amount6G?: boolean;
}

