/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Country } from './country';


export interface CompanyBankAccountPresentation { 
    /**
     * Iban-number
     */
    iban?: string;
    /**
     * Bban-number
     */
    bban?: string;
    /**
     * BIC/SWIFT for this bankaccount
     */
    bic?: string;
    country?: Country;
    readonly provider?: CompanyBankAccountPresentation.ProviderEnum;
}
export namespace CompanyBankAccountPresentation {
    export type ProviderEnum = 'NETS' | 'AUTOPAY';
    export const ProviderEnum = {
        Nets: 'NETS' as ProviderEnum,
        Autopay: 'AUTOPAY' as ProviderEnum
    };
}


