/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { CompanyInfo } from './companyInfo';


export interface CompanyInfoOverview { 
    yearEndReport?: YearEndReport;
    companyInfo?: Array<CompanyInfo>;
}

