/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ControlledTransactionsSummary { 
    /**
     * The sum of all transactions with the category operational income
     */
    sumOperationalIncome?: number;
    /**
     * The sum of all transactions with the category financial income
     */
    sumFinancialIncome?: number;
    /**
     * The sum of all transactions with the category operational cost
     */
    totalOperationalCost?: number;
    /**
     * The sum of all transactions with the category financial cost
     */
    totalFinancialCost?: number;
    /**
     * The sum of all transactions with the category extraordinary purchase
     */
    totalExtraordinaryPurchases?: number;
    /**
     * The sum of all transactions with the category extraordinary sale
     */
    totalExtraordinarySales?: number;
    /**
     * The sum of all outstanding with the category claim
     */
    totalClaims?: number;
    /**
     * The sum of all outstanding with the category debt
     */
    totalDebt?: number;
    /**
     * The sum of all outstanding with the category guarantor responsibility
     */
    totalGuarantorResponsibility?: number;
    /**
     * The sum of all outstanding with the category guarantee basis
     */
    totalGuaranteeBasis?: number;
}

