/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ControlledTransactionsSummary } from './controlledTransactionsSummary';
import { YearEndReport } from './yearEndReport';
import { ControlledTransactionsFunctionAndRisk } from './controlledTransactionsFunctionAndRisk';
import { GenericData } from './genericData';
import { ControlledTransactionsRelatedCompanies } from './controlledTransactionsRelatedCompanies';


export interface ControlledTransactions { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * Is exempt from sharing transactions
     */
    exemptFromTransactionSharing?: boolean;
    /**
     * Is exempt from sharing prices
     */
    exemptFromPriceSharing?: boolean;
    /**
     * Year of consolidated margin
     */
    consolidatedMarginYear?: number;
    /**
     * Percentage of consolidated margin
     */
    consolidatedMarginPercentage?: number;
    /**
     * Whether or not the company only reports provision income
     */
    reportsOnlyProvisionIncome?: string;
    /**
     * The total cost related to development of the company\'s immaterial assets
     */
    costOfImmaterialAssets?: number;
    /**
     * The number of patents registered by the company
     */
    numberOfRegisteredPatents?: number;
    /**
     * Whether or not the group related to the company has undergone restructuring
     */
    groupBeenRestructured?: boolean;
    /**
     * Whether or not the company has serviced another company in the same group for free
     */
    companyServicedOtherCompanyInGroupForFree?: boolean;
    /**
     * Whether or not the company acts as a guarantor for an agreement by another company in the same group
     */
    companyGuarantorForAgreementsByOtherCompaniesInSameGroup?: boolean;
    /**
     * Related companies that\'s using the company\'s immaterial assets
     */
    relatedCompaniesUsingImmaterialAssets?: Array<ControlledTransactionsRelatedCompanies>;
    /**
     * List of functions and risks
     */
    functionAndRisk?: Array<ControlledTransactionsFunctionAndRisk>;
    summary?: ControlledTransactionsSummary;
}

