/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { ShareholderRegisterData } from './shareholderRegisterData';


export interface ContactInfo { 
    yearEndReport?: YearEndReport;
    name?: ShareholderRegisterData;
    email?: ShareholderRegisterData;
    role?: ShareholderRegisterData;
    phone?: ShareholderRegisterData;
}

