/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SticosConversationMessage } from './sticosConversationMessage';
import { SupportAIConversationMessage } from './supportAIConversationMessage';
import { Change } from './change';
import { CopilotRequest } from './copilotRequest';
import { CopilotFollowUpQuestion } from './copilotFollowUpQuestion';


export interface CopilotResponse { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    copilotRequest: CopilotRequest;
    supportAIConversationMessage: SupportAIConversationMessage;
    sticosConversationMessage: SticosConversationMessage;
    responseStartTimestamp: string;
    responseEndTimestamp: string;
    errorCode?: CopilotResponse.ErrorCodeEnum;
    source?: CopilotResponse.SourceEnum;
    feedback?: CopilotResponse.FeedbackEnum;
    /**
     * List of follow-up questions
     */
    copilotFollowUpQuestion?: Array<CopilotFollowUpQuestion>;
}
export namespace CopilotResponse {
    export type ErrorCodeEnum = 'NO_ERROR' | 'OTHER_ERROR' | 'COPILOT_INVALID_FORMAT' | 'SUPPORT_AI_SERVER_ERROR' | 'SUPPORT_AI_SERVER_UNAVAILABLE' | 'COPILOT_INCOMPLETE_RESPONSE';
    export const ErrorCodeEnum = {
        NoError: 'NO_ERROR' as ErrorCodeEnum,
        OtherError: 'OTHER_ERROR' as ErrorCodeEnum,
        CopilotInvalidFormat: 'COPILOT_INVALID_FORMAT' as ErrorCodeEnum,
        SupportAiServerError: 'SUPPORT_AI_SERVER_ERROR' as ErrorCodeEnum,
        SupportAiServerUnavailable: 'SUPPORT_AI_SERVER_UNAVAILABLE' as ErrorCodeEnum,
        CopilotIncompleteResponse: 'COPILOT_INCOMPLETE_RESPONSE' as ErrorCodeEnum
    };
    export type SourceEnum = 'SUPPORT' | 'STICOS' | 'ACCOUNT_PLAN';
    export const SourceEnum = {
        Support: 'SUPPORT' as SourceEnum,
        Sticos: 'STICOS' as SourceEnum,
        AccountPlan: 'ACCOUNT_PLAN' as SourceEnum
    };
    export type FeedbackEnum = 'NO_FEEDBACK' | 'THUMBS_UP' | 'THUMBS_DOWN';
    export const FeedbackEnum = {
        NoFeedback: 'NO_FEEDBACK' as FeedbackEnum,
        ThumbsUp: 'THUMBS_UP' as FeedbackEnum,
        ThumbsDown: 'THUMBS_DOWN' as FeedbackEnum
    };
}


