/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';
import { Cost } from './cost';


export interface CostParticipant { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    displayName?: string;
    /**
     * Optional employee id in case the participant is an employee
     */
    employeeId?: number;
    cost: Cost;
}

