/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { Change } from './change';
import { EmployeeCategory } from './employeeCategory';


export interface CreateSalaryEmployee { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    firstName: string;
    lastName: string;
    readonly displayName?: string;
    number?: string;
    department?: Department;
    employeeCategory?: EmployeeCategory;
    readonly pictureId?: number;
    readonly isContact?: boolean;
}

