/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateSalaryEmployee } from './createSalaryEmployee';
import { SalaryV2PaymentValidationResult } from './salaryV2PaymentValidationResult';
import { Employment } from './employment';
import { PreviousSalaryAggregates } from './previousSalaryAggregates';


export interface CreateSalaryEmployeeToEmploymentRelationship { 
    employee?: CreateSalaryEmployee;
    /**
     * Employments
     */
    readonly employments?: Array<Employment>;
    /**
     * ValidationResults
     */
    readonly validationResults?: Array<SalaryV2PaymentValidationResult>;
    /**
     * Previous Salaries
     */
    readonly previousSalaries?: Array<PreviousSalaryAggregates>;
}

