/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface CurrencyPaymentsSum { 
    currency?: Currency;
    /**
     * Sum of the payments in currency
     */
    readonly sum?: number;
    /**
     * Exchange rate used for the sum
     */
    readonly exchangeRate?: number;
    /**
     * Display exchange rate used for the sum. Eg. EURNOK are displayed per 1 (9.87), while SEKNOK per 100 (98,27)
     */
    readonly displayExchangeRate?: number;
    /**
     * Sum of the amounts after exchange rate applied. Eg. if exchange rate is 10, then 100 EUR will be 1000 NOK
     */
    readonly exchangedAmountsSum?: number;
    /**
     * Count of the payments in currency
     */
    readonly count?: number;
}

