/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { Change } from './change';


export interface CurrencyExchangeRate { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    targetCurrency: Currency;
    sourceCurrency: Currency;
    rate?: number;
    /**
     * Source of exchange rates, i.e Norges Bank
     */
    source?: CurrencyExchangeRate.SourceEnum;
    date?: string;
}
export namespace CurrencyExchangeRate {
    export type SourceEnum = 'NORGES_BANK' | 'HALLONEN';
    export const SourceEnum = {
        NorgesBank: 'NORGES_BANK' as SourceEnum,
        Hallonen: 'HALLONEN' as SourceEnum
    };
}


