/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerImportRowContent } from './customerImportRowContent';
import { CustomerImport } from './customerImport';
import { ImportRowErrorMessage } from './importRowErrorMessage';
import { Change } from './change';


export interface CustomerPotential { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    importComponent: CustomerImport;
    rowContent?: CustomerImportRowContent;
    /**
     * errorMessage
     */
    errorMessage?: Array<ImportRowErrorMessage>;
    rowStatus?: CustomerPotential.RowStatusEnum;
    readonly rowNumber?: number;
}
export namespace CustomerPotential {
    export type RowStatusEnum = 'NEW' | 'UPDATE' | 'FAIL' | 'DUPLICATE';
    export const RowStatusEnum = {
        New: 'NEW' as RowStatusEnum,
        Update: 'UPDATE' as RowStatusEnum,
        Fail: 'FAIL' as RowStatusEnum,
        Duplicate: 'DUPLICATE' as RowStatusEnum
    };
}


