/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerImport } from './customerImport';
import { CustomerImportField } from './customerImportField';
import { Change } from './change';


export interface CustomerImportHeader { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    importComponent?: CustomerImport;
    orderOfColumn?: number;
    name?: string;
    sampleValue?: string;
    suggestedColumnField?: CustomerImportField;
}

