/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SegmentationData } from './segmentationData';


export interface DashboardContextDTO { 
    readonly contextId?: string;
    readonly companyId?: number;
    readonly loginEmployeeId?: number;
    readonly tripletexEmployeeId?: number;
    readonly companyName?: string;
    readonly companyCurrency?: string;
    readonly companyStartDate?: string;
    readonly language?: string;
    readonly trialAccount?: boolean;
    readonly showEaccountingMessage?: boolean;
    segmentationData?: SegmentationData;
    readonly isEligibleForOnboardingFeedback?: boolean;
    readonly loginEmployeeFirstName?: string;
}

