/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatabaseMigrationGroup } from './databaseMigrationGroup';


export interface DatabaseMigrationSummary { 
    readonly migrationGroups?: Array<DatabaseMigrationGroup>;
}

