/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface DebtCollector { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    name?: string;
    sendType?: DebtCollector.SendTypeEnum;
    readonly annualFee?: number;
    readonly feePerCase?: number;
}
export namespace DebtCollector {
    export type SendTypeEnum = 'API' | 'EMAIL' | 'SFTP';
    export const SendTypeEnum = {
        Api: 'API' as SendTypeEnum,
        Email: 'EMAIL' as SendTypeEnum,
        Sftp: 'SFTP' as SendTypeEnum
    };
}


