/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PurchaseOrderline } from './purchaseOrderline';
import { Change } from './change';


export interface Deviation { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    purchaseOrderLine: PurchaseOrderline;
    date: string;
    cause?: Deviation.CauseEnum;
    action?: Deviation.ActionEnum;
    comment?: string;
    readonly receivedBy?: string;
    readonly quantityOrdered?: number;
    readonly quantityReceived?: number;
    readonly deviation?: number;
}
export namespace Deviation {
    export type CauseEnum = 'CAUSE_DEFECT' | 'CAUSE_TOO_FEW' | 'CAUSE_TOO_MANY' | 'CAUSE_REPLACEMENT';
    export const CauseEnum = {
        CauseDefect: 'CAUSE_DEFECT' as CauseEnum,
        CauseTooFew: 'CAUSE_TOO_FEW' as CauseEnum,
        CauseTooMany: 'CAUSE_TOO_MANY' as CauseEnum,
        CauseReplacement: 'CAUSE_REPLACEMENT' as CauseEnum
    };
    export type ActionEnum = 'ACTION_IGNORE' | 'ACTION_GENERATE_RESTORDER' | 'ACTION_RETURN' | 'ACTION_RETURN_GENERATE_RESTORDER';
    export const ActionEnum = {
        ActionIgnore: 'ACTION_IGNORE' as ActionEnum,
        ActionGenerateRestorder: 'ACTION_GENERATE_RESTORDER' as ActionEnum,
        ActionReturn: 'ACTION_RETURN' as ActionEnum,
        ActionReturnGenerateRestorder: 'ACTION_RETURN_GENERATE_RESTORDER' as ActionEnum
    };
}


