/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductGroup } from './productGroup';
import { Customer } from './customer';
import { Product } from './product';
import { Change } from './change';


export interface DiscountPolicy { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    percentage?: number;
    fixedAmount?: number;
    product: Product;
    customer: Customer;
    productGroup?: ProductGroup;
    salesPriceWithDiscount?: number;
    isPercentage?: number;
    discountType?: DiscountPolicy.DiscountTypeEnum;
}
export namespace DiscountPolicy {
    export type DiscountTypeEnum = 'CUSTOMER_DISCOUNT' | 'PRODUCT_DISCOUNT' | 'PRODUCT_GROUP_DISCOUNT';
    export const DiscountTypeEnum = {
        CustomerDiscount: 'CUSTOMER_DISCOUNT' as DiscountTypeEnum,
        ProductDiscount: 'PRODUCT_DISCOUNT' as DiscountTypeEnum,
        ProductGroupDiscount: 'PRODUCT_GROUP_DISCOUNT' as DiscountTypeEnum
    };
}


