/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';


export interface DividendDetails { 
    yearEndReport?: YearEndReport;
    readonly name?: string;
    readonly grouping?: string;
    readonly value?: number;
}

