/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentReceptionItem { 
    /**
     * Message Id.
     */
    messageId: number;
    /**
     * Document Id.
     */
    documentId: number;
    /**
     * The name of the document.
     */
    documentName: string;
    /**
     * Employee Id of the receiver of the document.
     */
    receiverEmployeeId: number;
    /**
     * Document receiver.
     */
    readonly receiverName?: string;
    /**
     * Document sender.
     */
    readonly senderName?: string;
    /**
     * Document size in human readable format.
     */
    readonly displaySize?: string;
    /**
     * Document size.
     */
    readonly size?: number;
    /**
     * Document create date.
     */
    created: string;
    /**
     * Document edit date.
     */
    edited: string;
    /**
     * Is new document.
     */
    readonly isNew?: boolean;
    /**
     * Document mime type.
     */
    readonly mimeType?: string;
}

