/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface DocumentArchive { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * The name of the document.
     */
    fileName: string;
    /**
     * The size of the document in readable format.
     */
    readonly size?: number;
    archiveDate?: string;
    /**
     * Type of the document
     */
    mimeType: string;
}

