/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';
import { DynamicFormField } from './dynamicFormField';


export interface DynamicControlFormTemplate { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    type?: string;
    readonly displayName?: string;
    description?: string;
    formVersion?: string;
    typeNumber?: number;
    previousTemplateId?: number;
    rootTemplateId?: number;
    isArchived?: boolean;
    isNelfo?: boolean;
    nhoVersion?: string;
    readonly signatureRequired?: boolean;
    fields?: Array<DynamicFormField>;
}

