/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeDeductionTableBuilder { 
    companyId?: number;
    employeeId?: number;
    date?: string;
    percentage?: number;
    taxFreeAmount?: number;
}

