/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HolidayAllowanceEarned } from './holidayAllowanceEarned';
import { Department } from './department';
import { Address } from './address';
import { Employment } from './employment';
import { Country } from './country';
import { InternationalId } from './internationalId';
import { Change } from './change';
import { EmployeeCategory } from './employeeCategory';


export interface Employee { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    firstName: string;
    lastName: string;
    readonly displayName?: string;
    employeeNumber?: string;
    dateOfBirth?: string;
    email?: string;
    phoneNumberMobileCountry?: Country;
    phoneNumberMobile?: string;
    phoneNumberHome?: string;
    phoneNumberWork?: string;
    nationalIdentityNumber?: string;
    dnumber?: string;
    internationalId?: InternationalId;
    bankAccountNumber?: string;
    /**
     * IBAN field
     */
    iban?: string;
    /**
     * Bic (swift) field
     */
    bic?: string;
    /**
     * Country of creditor bank field
     */
    creditorBankCountryId?: number;
    /**
     * UsesAbroadPayment field. Determines if we should use domestic or abroad remittance. To be able to use abroad remittance, one has to: 1: have Autopay 2: have valid combination of the fields Iban, Bic (swift) and Country of creditor bank. 
     */
    usesAbroadPayment?: boolean;
    /**
     * Define the employee\'s user type.<br>STANDARD: Reduced access. Users with limited system entitlements.<br>EXTENDED: Users can be given all system entitlements.<br>NO_ACCESS: User with no log on access.<br>Users with access to Tripletex must confirm the email address.
     */
    userType?: Employee.UserTypeEnum;
    /**
     * Determines if salary information can be registered on the user including hours, travel expenses and employee expenses. The user may also be selected as a project member on projects.
     */
    readonly allowInformationRegistration?: boolean;
    /**
     * Determines if the employee is a contact (external) in the company.
     */
    isContact?: boolean;
    /**
     * True if this Employee object represents an accounting or auditor office
     */
    readonly isProxy?: boolean;
    comments?: string;
    address?: Address;
    department?: Department;
    /**
     * Employments tied to the employee
     */
    employments?: Array<Employment>;
    holidayAllowanceEarned?: HolidayAllowanceEarned;
    employeeCategory?: EmployeeCategory;
    readonly isAuthProjectOverviewURL?: boolean;
    readonly pictureId?: number;
    readonly companyId?: number;
}
export namespace Employee {
    export type UserTypeEnum = 'STANDARD' | 'EXTENDED' | 'NO_ACCESS';
    export const UserTypeEnum = {
        Standard: 'STANDARD' as UserTypeEnum,
        Extended: 'EXTENDED' as UserTypeEnum,
        NoAccess: 'NO_ACCESS' as UserTypeEnum
    };
}


