/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeImportRowContent { 
    firstName?: string;
    lastName?: string;
    email?: string;
    postalAddress1?: string;
    postalAddress2?: string;
    postalCode?: string;
    postalAddressCity?: string;
    postalAddressCountry?: string;
    phoneNumberWork?: string;
    phoneNumberMobile?: string;
    employeeNumber?: string;
    percentOfEmployment?: string;
    dateOfBirth?: string;
    socialSecurityNumber?: string;
    getdNumber?: string;
    bban?: string;
    iban?: string;
    swift?: string;
    vacationAllowanceEarnedYear?: string;
    vacationAllowanceBasis?: string;
    vacationAllowanceAmount?: string;
    vacationAllowanceExtraWeekAmount?: string;
    startDate?: string;
    employmentType?: string;
    employmentForm?: string;
    occupationCode?: string;
    yearlyWage?: string;
    hourlyWage?: string;
    divisionNumber?: string;
    internationalIdNumber?: string;
    internationalIdType?: string;
    internationalIdCountry?: string;
    salaryType?: string;
    empty?: boolean;
}

