/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Employee } from './employee';


export interface EmployeeCompany { 
    isDefault?: boolean;
    company?: Company;
    employee?: Employee;
    isSuspended?: boolean;
}

