/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeImportField } from './employeeImportField';
import { EmployeeImport } from './employeeImport';
import { Change } from './change';


export interface EmployeeImportHeader { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    importComponent?: EmployeeImport;
    orderOfColumn?: number;
    name?: string;
    sampleValue?: string;
    suggestedColumnField?: EmployeeImportField;
}

