/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeImportField { 
    readonly id?: number;
    readonly displayName?: string;
    readonly displayNameExpanded?: string;
    readonly isMandatory?: boolean;
    readonly sequence?: number;
    readonly fieldName?: string;
    readonly dependentOnFieldIds?: Array<number>;
}

