/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeLoginInfoBuilder { 
    companyId?: number;
    ip?: string;
    port?: string;
    loginResult?: number;
    browserDetails?: string;
    employeeId?: number;
    username?: string;
    timestamp?: string;
}

