/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { Address } from './address';
import { Employment } from './employment';
import { CompanyEmployeeRate } from './companyEmployeeRate';
import { Change } from './change';
import { EmployeeCategory } from './employeeCategory';


export interface EmployeeOverview { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    firstName: string;
    lastName: string;
    readonly displayName?: string;
    number?: string;
    dateOfBirth?: string;
    email?: string;
    readonly phoneNumberMobile?: string;
    phoneNumberHome?: string;
    phoneNumberWork?: string;
    nationalIdentityNumber?: string;
    readonly isContact?: boolean;
    address?: Address;
    department?: Department;
    employeeCategory?: EmployeeCategory;
    readonly pictureId?: number;
    readonly companyId?: number;
    lastActiveEmployment?: Employment;
    currentCompanyEmployeeRate?: CompanyEmployeeRate;
    readonly deliveryMethodWageSlipString?: string;
    bankAccountNumber?: string;
    allowLogin?: boolean;
    isProxy?: boolean;
}

