/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Employee } from './employee';
import { Change } from './change';


export interface Entitlement { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    employee: Employee;
    /**
     * Descriptive name for the privilege. Might change between releases.
     */
    readonly name?: string;
    /**
     * Unique id for the type of privilege.
     */
    entitlementId: number;
    customer: Company;
}

