/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtraordinaryDistributionData { 
    readonly remainderNotTaxedFelling?: number;
    readonly remainderIncludedThisYear?: number;
    readonly sumLaterIncomeRecognition?: number;
    readonly municipalityNumber?: string;
    readonly paidPublicContributionForestFund?: number;
}

