/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Favorite { 
    readonly id?: number;
    readonly rank?: number;
    readonly name?: string;
    readonly pageUrl?: string;
}

