/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileIdForIncomingPayments { 
    /**
     * FileId corresponding to an Incoming Payment PDF.
     */
    readonly fileId?: number;
    /**
     * Date on incoming payments file.
     */
    readonly date?: string;
    /**
     * Account number.
     */
    readonly accountNumber?: string;
}

