/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FlexSummary { 
    readonly incomingHourBalance?: number;
    readonly outgoingHourBalance?: number;
    readonly change?: number;
}

