/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ForestFundData { 
    readonly municipalityNumber?: number;
    readonly paidPublicContributionForestFund?: number;
    readonly calculatedReversalOfPrevCalculations?: number;
    readonly basisForCalculationTaxAssets?: number;
}

