/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParameterizedHeader } from './parameterizedHeader';
import { MultiPart } from './multiPart';
import { ContentDisposition } from './contentDisposition';
import { MediaType } from './mediaType';
import { FormDataContentDisposition } from './formDataContentDisposition';


export interface FormDataBodyPart { 
    contentDisposition?: ContentDisposition;
    entity?: object;
    headers?: { [key: string]: Array<string>; };
    mediaType?: MediaType;
    messageBodyWorkers?: object;
    parent?: MultiPart;
    providers?: object;
    formDataContentDisposition?: FormDataContentDisposition;
    simple?: boolean;
    name?: string;
    value?: string;
    parameterizedHeaders?: { [key: string]: Array<ParameterizedHeader>; };
}

