/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneralLedgerAccountSum { 
    readonly accountId?: number;
    readonly balanceChange?: number;
    readonly balanceIn?: number;
    readonly balanceOut?: number;
    readonly noOfCurrencies?: number;
    readonly balanceCurrency?: string;
    readonly balanceCurrencyChange?: number;
    readonly balanceCurrencyIn?: number;
    readonly balanceCurrencyOut?: number;
}

