/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneralBannerDTO { 
    bannerType?: GeneralBannerDTO.BannerTypeEnum;
    title?: string;
    message?: string;
    tag?: string;
    link?: string;
}
export namespace GeneralBannerDTO {
    export type BannerTypeEnum = 'info' | 'warning' | 'error' | 'success';
    export const BannerTypeEnum = {
        Info: 'info' as BannerTypeEnum,
        Warning: 'warning' as BannerTypeEnum,
        Error: 'error' as BannerTypeEnum,
        Success: 'success' as BannerTypeEnum
    };
}


