/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetStartedTaskWidget } from './getStartedTaskWidget';


export interface GetStartedSummary { 
    numberOfCompletedTasks?: number;
    userName?: string;
    completedTasksPercentage?: string;
    uncompletedTasksPercentage?: string;
    accountSettingsURL?: string;
    tasks?: Array<GetStartedTaskWidget>;
}

