/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetStartedTaskWidget { 
    id?: number;
    icon?: string;
    title?: string;
    status?: GetStartedTaskWidget.StatusEnum;
    actionUrl?: string;
    dataTestId?: string;
}
export namespace GetStartedTaskWidget {
    export type StatusEnum = 'INITIAL' | 'UNAVAILABLE' | 'PENDING' | 'DONE';
    export const StatusEnum = {
        Initial: 'INITIAL' as StatusEnum,
        Unavailable: 'UNAVAILABLE' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Done: 'DONE' as StatusEnum
    };
}


