/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { PurchaseOrder } from './purchaseOrder';
import { Change } from './change';
import { GoodsReceiptLine } from './goodsReceiptLine';


export interface GoodsReceipt { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    purchaseOrder?: PurchaseOrder;
    registrationDate: string;
    receivedBy?: Employee;
    readonly status?: GoodsReceipt.StatusEnum;
    comment?: string;
    /**
     * Purchase Order lines tied to the goods receipt
     */
    goodsReceiptLines: Array<GoodsReceiptLine>;
}
export namespace GoodsReceipt {
    export type StatusEnum = 'STATUS_OPEN' | 'STATUS_CONFIRMED';
    export const StatusEnum = {
        StatusOpen: 'STATUS_OPEN' as StatusEnum,
        StatusConfirmed: 'STATUS_CONFIRMED' as StatusEnum
    };
}


