/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportGroupFilter } from './reportGroupFilter';
import { ReportGroupAutoGroup } from './reportGroupAutoGroup';


export interface HeaderBlueprintV1 { 
    name?: string;
    description?: string;
    hideSelf?: boolean;
    visibilityExpression?: string;
    removeEmpty?: boolean;
    expression?: string;
    variableName?: string;
    valueFormat?: string;
    cellFormat?: string;
    reference?: string;
    initialExpansionState?: number;
    filter?: ReportGroupFilter;
    autoGroup?: ReportGroupAutoGroup;
    children?: Array<HeaderBlueprintV1>;
    version?: number;
}

