/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HelpCenterArticle } from './helpCenterArticle';
import { HelpCenterVideo } from './helpCenterVideo';


export interface HelpCenterArticles { 
    mainArticle?: HelpCenterArticle;
    readonly relevantArticles?: Array<HelpCenterArticle>;
    readonly videos?: Array<HelpCenterVideo>;
    readonly faqs?: Array<HelpCenterArticle>;
    readonly salesforceSupportRequestsUrl?: string;
    readonly helpCenterUrl?: string;
    readonly helpCenterSearchUrl?: string;
    readonly keyboardShortcutsArticleUrl?: string;
}

