/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HourBuilder { 
    companyId?: number;
    employeeId?: number;
    date?: string;
    projectId?: number;
    activityId?: number;
    hours?: number;
    comment?: string;
    invoiceId?: number;
    approved?: boolean;
}

