/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IdPortenLoginRequest { 
    /**
     * The url where the user should be redirected back to when authentication is complete
     */
    internalRedirectUrl?: string;
}

