/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IdPortenLogin { 
    /**
     * The url which the client needs to redirect for performing authentication
     */
    readonly url?: string;
}

