/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Project } from './project';
import { Department } from './department';
import { ProductUnit } from './productUnit';
import { Employee } from './employee';
import { Customer } from './customer';
import { Currency } from './currency';
import { Asset } from './asset';
import { Product } from './product';
import { VatType } from './vatType';


export interface IncomeVoucherPaymentPosting { 
    account?: Account;
    customer?: Customer;
    vatType?: VatType;
    product?: Product;
    project?: Project;
    employee?: Employee;
    department?: Department;
    asset?: Asset;
    incomeDescription?: string;
    postingId?: number;
    currency?: Currency;
    clientId?: string;
    amount?: number;
    quantity1?: number;
    productUnit1?: ProductUnit;
    quantity2?: number;
    productUnit2?: ProductUnit;
    date?: string;
    amountGross?: number;
    /**
     * Is vat code closed?
     */
    readonly isVatClosed?: boolean;
    /**
     * Is amount of this posting (for VAT purposes) changeable
     */
    readonly isAmountVatClosed?: boolean;
    amountGrossCurrency?: number;
    paymentTypeId?: number;
}

