/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncomingInvoicePaymentHistoryTransaction } from './incomingInvoicePaymentHistoryTransaction';


export interface IncomingInvoicePaymentHistory { 
    readonly baseVoucherId?: number;
    readonly transactions?: Array<IncomingInvoicePaymentHistoryTransaction>;
    readonly remainingAmountToPay?: number;
    readonly remainingAmountToPayCurrency?: number;
}

