/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncomeVoucherPaymentPosting } from './incomeVoucherPaymentPosting';
import { Currency } from './currency';
import { IncomeVoucherPosting } from './incomeVoucherPosting';
import { Voucher } from './voucher';


export interface IncomeVoucher { 
    voucherId?: number;
    voucherNumber?: string;
    invoiceNumber?: string;
    invoiceDate?: string;
    incomeDate?: string;
    description?: string;
    customerId?: number;
    sendToLedger?: boolean;
    dueDate?: string;
    /**
     * Income postings
     */
    incomePostings?: Array<IncomeVoucherPosting>;
    /**
     * Payment postings
     */
    paymentPostings?: Array<IncomeVoucherPaymentPosting>;
    /**
     * Ids for payment postings to be deleted
     */
    paymentPostingIdsForDeletion?: Array<number>;
    currency?: Currency;
    voucherTempNumber?: number;
    debitPostingId?: number;
    /**
     * Id of attachment linked to the voucher
     */
    attachmentId?: number;
    canBeDeleted?: boolean;
    canBeReversed?: boolean;
    isTemporary?: boolean;
    reverseVoucher?: Voucher;
}

