/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncomeStatement { 
    readonly businessIncome?: number;
    readonly taxableBusinessIncome?: number;
    readonly totalAddition?: number;
    readonly totalDeduction?: number;
    readonly changes?: number;
    readonly receivedGroupContribution?: number;
    readonly payedGroupContribution?: number;
}

