/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncomingInvoiceHeaderWrite { 
    /**
     * The Incoming invoice draft vendor
     */
    vendorId?: number;
    /**
     * The date the invoice was issued.
     */
    invoiceDate: string;
    /**
     * The date the invoice is due.
     */
    dueDate?: string;
    /**
     * Currency used in the invoice.
     */
    currencyId?: number;
    /**
     * Amount including VAT.
     */
    invoiceAmount?: number;
    /**
     * Description of the invoice.
     */
    description?: string;
    /**
     * If value is set to 0, the invoice number will be generated.
     */
    invoiceNumber?: string;
    /**
     * Voucher type of the invoice.
     */
    voucherType?: number;
    /**
     * The purchase order that the invoice belongs to.
     */
    purchaseOrderId?: number;
    /**
     * The id of the payment type chosen
     */
    paymentTypeId?: number;
    /**
     * The date of the payment
     */
    paymentDate?: string;
    /**
     * The amount of the payment type chosen in the company currency
     */
    paymentAmount?: number;
    /**
     * The amount of the payment type chosen in the chosen currency
     */
    paymentAmountCurrency?: number;
}

