/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncomingInvoiceVendor { 
    readonly id?: number;
    readonly displayName?: string;
    readonly departmentId?: number;
}

