/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericData } from './genericData';


export interface InterestLimitationCalculationOfTotalNetCosts { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * Total interest expenses from account 815x
     */
    totalInterestExpensesFromAccount?: number;
    /**
     * Total interest income from account 805x
     */
    totalInterestIncomeFromAccount?: number;
    /**
     * Correction of interest expenses
     */
    correctionOfInterestExpenses?: number;
    /**
     * Correction Of Interest Income
     */
    correctionOfInterestIncome?: number;
    /**
     * Guarantee commissions on debt
     */
    guaranteeCommissionsOnDebt?: number;
    /**
     * Loss on realization of premium discount bonds
     */
    lossOnRealizationOfPremiumDiscountBonds?: number;
    /**
     * Gain on realization of premium discount bonds
     */
    gainOnRealizationOfPremiumDiscountBonds?: number;
    /**
     * Loss on realization of composite volume debt instruments
     */
    lossOnRealizationOfCompositeVolumeDebtInstruments?: number;
    /**
     * Gain on realization of composite volume debt instruments
     */
    gainOnRealizationOfCompositeVolumeDebtInstruments?: number;
    /**
     * Net interest costs
     */
    readonly netInterestCosts?: number;
}

