/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { InterestExpensesToRelatedPartyOutsideGroup } from './interestExpensesToRelatedPartyOutsideGroup';
import { InterestExpensesToRelatedPartyOutsideGroupOtherWithOutstandingClaim } from './interestExpensesToRelatedPartyOutsideGroupOtherWithOutstandingClaim';
import { InterestExpensesToRelatedPartyOutsideGroupOtherGroupGuarantor } from './interestExpensesToRelatedPartyOutsideGroupOtherGroupGuarantor';
import { GenericData } from './genericData';


export interface InterestExpensesToRelatedPartiesOutsideGroup { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * Interest expenses to companies in the same group
     */
    interestExpensesToCompanies?: Array<InterestExpensesToRelatedPartyOutsideGroup>;
    /**
     * Interest expenses to other group guarantor
     */
    interestExpensesToOthersGroupGuarantor?: Array<InterestExpensesToRelatedPartyOutsideGroupOtherGroupGuarantor>;
    /**
     * Interest expenses to other companies with outstanding claims
     */
    interestExpensesToOthersWithOutstandingClaim?: Array<InterestExpensesToRelatedPartyOutsideGroupOtherWithOutstandingClaim>;
    /**
     * Total interest expenses
     */
    readonly totalInterestExpenses?: number;
    /**
     * Costs for guarantee commission
     */
    costsForGuaranteeCommission?: number;
    /**
     * Total interest expenses including guarantee costs
     */
    readonly totalInterestExpensesIncludingGuaranteeCosts?: number;
}

