/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { CompaniesIncludedInNorwegianPartOfGroup } from './companiesIncludedInNorwegianPartOfGroup';
import { GenericData } from './genericData';


export interface InterestLimitationNorwegianPartOfGroup { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * Information about the Norwegian group reported by another company
     */
    infoNorwegianPartOfGroupReportedAnotherCompany?: boolean;
    /**
     * Company name
     */
    companyName?: string;
    /**
     * Organization number
     */
    organizationNumber?: string;
    /**
     * Country code
     */
    countryCode?: string;
    /**
     * Companies included in the Norwegian part of the group
     */
    companiesIncludedInNorwegianPartOfGroup?: Array<CompaniesIncludedInNorwegianPartOfGroup>;
}

