/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Change } from './change';


export interface Inventory { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    name: string;
    number?: string;
    readonly displayName?: string;
    isMainInventory?: boolean;
    isInactive?: boolean;
    description?: string;
    email?: string;
    phone?: string;
    deletable?: boolean;
    address?: Address;
    lastStocking?: string;
    status?: string;
    hasLocations?: boolean;
}

