/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StockChange } from './stockChange';
import { Change } from './change';
import { Inventory } from './inventory';


export interface InventoryCorrection { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    readonly number?: number;
    date: string;
    comment?: string;
    fromWarehouse?: Inventory;
    warehouse?: Inventory;
    stockChanges?: Array<StockChange>;
}

