/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { InventoriesDetails } from './inventoriesDetails';


export interface InventoriesOverview { 
    yearEndReport?: YearEndReport;
    inventories?: Array<InventoriesDetails>;
    readonly totalOpeningBalance?: number;
    readonly totalClosingBalance?: number;
    readonly totalOpeningBalanceTaxValue?: number;
    readonly totalClosingBalanceTaxValue?: number;
    readonly openingBalanceDifferences?: number;
    readonly closingBalanceDifferences?: number;
    readonly changes?: number;
}

