/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceOverviewMetaDTO { 
    readonly hasModuleProjectEconomy?: boolean;
    readonly hasModuleDepartment?: boolean;
    readonly hasModuleDepartmentAccounting?: boolean;
    readonly hasModuleSmsNotification?: boolean;
    readonly hasModuleNetsPrint?: boolean;
    readonly isVatOn?: boolean;
    readonly isReminderDebtCollectionActionAllowed?: boolean;
    readonly isCreditActionAllowed?: boolean;
    readonly companyCurrencyId?: number;
    readonly companyCountryId?: number;
}

