/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceBuilder { 
    companyId?: number;
    number?: number;
    projectId?: number;
    date?: string;
    approved?: boolean;
    charged?: boolean;
    history?: string;
    comment?: string;
    expense?: boolean;
    termOfPayment?: string;
    amount?: number;
    amountCurrency?: number;
    amountExVat?: number;
    amountExVatCurrency?: number;
    vendorId?: number;
    vendorInvoiceNumber?: number;
    currencyId?: number;
    voucherId?: number;
    kid?: string;
    externalNumberSeries?: boolean;
}

