/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { DebtCollector } from './debtCollector';


export interface InvoiceReminderDetails { 
    readonly chargedMoreThanTwice?: boolean;
    readonly lastReminderDueDate?: string;
    readonly lastReminderType?: InvoiceReminderDetails.LastReminderTypeEnum;
    readonly lastChargedReminderDate?: string;
    readonly isCreditNote?: boolean;
    readonly isPaid?: boolean;
    readonly email?: string;
    readonly smsNumber?: string;
    address?: Address;
    debtCollector?: DebtCollector;
}
export namespace InvoiceReminderDetails {
    export type LastReminderTypeEnum = 'SOFT_REMINDER' | 'REMINDER' | 'NOTICE_OF_DEBT_COLLECTION' | 'DEBT_COLLECTION';
    export const LastReminderTypeEnum = {
        SoftReminder: 'SOFT_REMINDER' as LastReminderTypeEnum,
        Reminder: 'REMINDER' as LastReminderTypeEnum,
        NoticeOfDebtCollection: 'NOTICE_OF_DEBT_COLLECTION' as LastReminderTypeEnum,
        DebtCollection: 'DEBT_COLLECTION' as LastReminderTypeEnum
    };
}


