/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceMessage { 
    readonly contentId?: number;
    readonly messageContentType?: number;
    readonly status?: number;
    readonly sendTime?: string;
    readonly readTime?: string;
    readonly receiverEmail?: string;
}

