/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LastPosted { 
    readonly voucherId?: number;
    readonly voucherNumber?: number;
    readonly voucherDate?: string;
    readonly timestamp?: string;
    readonly supplier?: string;
    readonly amount?: number;
    readonly paymentStatus?: string;
    readonly postedByEmployee?: string;
    readonly actualEmployeeId?: number;
    readonly automaticallyPosted?: boolean;
    readonly commentCount?: number;
    readonly lastComment?: string;
    readonly companyId?: number;
    readonly hasAttachment?: boolean;
    readonly description?: string;
}

