/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employment } from './employment';
import { Change } from './change';


export interface LeaveOfAbsence { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    employment?: Employment;
    /**
     * Existing leave of absence ID used by the current accounting system
     */
    importedLeaveOfAbsenceId?: string;
    startDate: string;
    endDate?: string;
    percentage: number;
    isWageDeduction?: boolean;
    /**
     * Define the leave of absence type.
     */
    type?: LeaveOfAbsence.TypeEnum;
}
export namespace LeaveOfAbsence {
    export type TypeEnum = 'LEAVE_OF_ABSENCE' | 'FURLOUGH' | 'PARENTAL_BENEFITS' | 'MILITARY_SERVICE' | 'EDUCATIONAL' | 'COMPASSIONATE' | 'OTHER_NOT_STATUTORILY_REQUIRED' | 'OTHER_STATUTORILY_REQUIRED' | 'EDUCATIONAL_NOT_STATUTORILY_REQUIRED' | 'EDUCATIONAL_STATUTORILY_REQUIRED';
    export const TypeEnum = {
        LeaveOfAbsence: 'LEAVE_OF_ABSENCE' as TypeEnum,
        Furlough: 'FURLOUGH' as TypeEnum,
        ParentalBenefits: 'PARENTAL_BENEFITS' as TypeEnum,
        MilitaryService: 'MILITARY_SERVICE' as TypeEnum,
        Educational: 'EDUCATIONAL' as TypeEnum,
        Compassionate: 'COMPASSIONATE' as TypeEnum,
        OtherNotStatutorilyRequired: 'OTHER_NOT_STATUTORILY_REQUIRED' as TypeEnum,
        OtherStatutorilyRequired: 'OTHER_STATUTORILY_REQUIRED' as TypeEnum,
        EducationalNotStatutorilyRequired: 'EDUCATIONAL_NOT_STATUTORILY_REQUIRED' as TypeEnum,
        EducationalStatutorilyRequired: 'EDUCATIONAL_STATUTORILY_REQUIRED' as TypeEnum
    };
}


