/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface LeaveOfAbsenceType { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Defines the leave of absence type option.
     */
    leaveOfAbsenceType: LeaveOfAbsenceType.LeaveOfAbsenceTypeEnum;
    nameNO?: string;
    code?: string;
}
export namespace LeaveOfAbsenceType {
    export type LeaveOfAbsenceTypeEnum = 'LEAVE_OF_ABSENCE' | 'FURLOUGH' | 'PARENTAL_BENEFITS' | 'MILITARY_SERVICE' | 'EDUCATIONAL' | 'COMPASSIONATE' | 'OTHER_NOT_STATUTORILY_REQUIRED' | 'OTHER_STATUTORILY_REQUIRED' | 'EDUCATIONAL_NOT_STATUTORILY_REQUIRED' | 'EDUCATIONAL_STATUTORILY_REQUIRED';
    export const LeaveOfAbsenceTypeEnum = {
        LeaveOfAbsence: 'LEAVE_OF_ABSENCE' as LeaveOfAbsenceTypeEnum,
        Furlough: 'FURLOUGH' as LeaveOfAbsenceTypeEnum,
        ParentalBenefits: 'PARENTAL_BENEFITS' as LeaveOfAbsenceTypeEnum,
        MilitaryService: 'MILITARY_SERVICE' as LeaveOfAbsenceTypeEnum,
        Educational: 'EDUCATIONAL' as LeaveOfAbsenceTypeEnum,
        Compassionate: 'COMPASSIONATE' as LeaveOfAbsenceTypeEnum,
        OtherNotStatutorilyRequired: 'OTHER_NOT_STATUTORILY_REQUIRED' as LeaveOfAbsenceTypeEnum,
        OtherStatutorilyRequired: 'OTHER_STATUTORILY_REQUIRED' as LeaveOfAbsenceTypeEnum,
        EducationalNotStatutorilyRequired: 'EDUCATIONAL_NOT_STATUTORILY_REQUIRED' as LeaveOfAbsenceTypeEnum,
        EducationalStatutorilyRequired: 'EDUCATIONAL_STATUTORILY_REQUIRED' as LeaveOfAbsenceTypeEnum
    };
}


