/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface License { 
    /**
     * Returns the license id.
     */
    readonly id?: number;
    /**
     * Returns license name.
     */
    readonly name?: string;
    /**
     * Returns license creation date.
     */
    readonly date?: string;
    /**
     * Returns license display text
     */
    readonly displayTextKey?: string;
    /**
     * Returns license content
     */
    readonly content?: string;
}

