/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lookup1881Hours } from './lookup1881Hours';


export interface Lookup1881Day { 
    readonly weekDay?: number;
    readonly hours?: Array<Lookup1881Hours>;
}

