/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lookup1881Day } from './lookup1881Day';


export interface Lookup1881RushHoursToll { 
    readonly days?: Array<Lookup1881Day>;
    readonly price?: number;
    readonly description?: string;
}

