/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface Mapping { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    readonly year?: number;
    readonly type?: string;
    readonly post?: string;
    readonly subPost?: string;
    readonly groupNumber?: string;
    readonly negate?: boolean;
    readonly excludeFromTaxReturn?: boolean;
    readonly groupingEnk?: string;
    readonly groupingAs?: string;
    readonly groupingAns?: string;
    readonly groupingAgricultureEnk?: string;
    readonly groupingForestryEnk?: string;
    negatePreviousYear?: boolean;
    excludeFromTaxReturnPreviousYear?: boolean;
    groupingEnkPreviousYear?: string;
    groupingAsPreviousYear?: string;
    groupingAnsPreviousYear?: string;
    readonly groupingAgricultureEnkPreviousYear?: string;
    readonly groupingForestryEnkPreviousYear?: string;
}

