/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MenuItemV2 { 
    title?: string;
    id?: string;
    url?: string;
    category?: string;
    child?: boolean;
}

