/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MigrationGroup { 
    migrationSource?: MigrationGroup.MigrationSourceEnum;
    migrationCategory?: MigrationGroup.MigrationCategoryEnum;
    migrationScope?: MigrationGroup.MigrationScopeEnum;
    shardGroup?: MigrationGroup.ShardGroupEnum;
    displayName?: string;
    tableName?: string;
}
export namespace MigrationGroup {
    export type MigrationSourceEnum = 'TripletexMigrations' | 'Tripletex';
    export const MigrationSourceEnum = {
        TripletexMigrations: 'TripletexMigrations' as MigrationSourceEnum,
        Tripletex: 'Tripletex' as MigrationSourceEnum
    };
    export type MigrationCategoryEnum = 'Structure' | 'Data';
    export const MigrationCategoryEnum = {
        Structure: 'Structure' as MigrationCategoryEnum,
        Data: 'Data' as MigrationCategoryEnum
    };
    export type MigrationScopeEnum = 'Common' | 'Production' | 'Api' | 'Cactus' | 'BugBounty';
    export const MigrationScopeEnum = {
        Common: 'Common' as MigrationScopeEnum,
        Production: 'Production' as MigrationScopeEnum,
        Api: 'Api' as MigrationScopeEnum,
        Cactus: 'Cactus' as MigrationScopeEnum,
        BugBounty: 'BugBounty' as MigrationScopeEnum
    };
    export type ShardGroupEnum = 'GLOBAL' | 'COMPANY' | 'ARCHIVE';
    export const ShardGroupEnum = {
        Global: 'GLOBAL' as ShardGroupEnum,
        Company: 'COMPANY' as ShardGroupEnum,
        Archive: 'ARCHIVE' as ShardGroupEnum
    };
}


