/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchemaVersion } from './schemaVersion';
import { Shard } from './shard';


export interface MigrationTypeSchemaVersion { 
    readonly shardGroup?: MigrationTypeSchemaVersion.ShardGroupEnum;
    shard?: Shard;
    readonly tableName?: string;
    readonly displayName?: string;
    readonly schemaVersions?: Array<SchemaVersion>;
}
export namespace MigrationTypeSchemaVersion {
    export type ShardGroupEnum = 'GLOBAL' | 'COMPANY' | 'ARCHIVE';
    export const ShardGroupEnum = {
        Global: 'GLOBAL' as ShardGroupEnum,
        Company: 'COMPANY' as ShardGroupEnum,
        Archive: 'ARCHIVE' as ShardGroupEnum
    };
}


