/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelExpenseRate } from './travelExpenseRate';
import { TravelExpense } from './travelExpense';
import { Change } from './change';
import { Passenger } from './passenger';
import { Cost } from './cost';
import { TravelExpenseRateCategory } from './travelExpenseRateCategory';
import { DrivingStop } from './drivingStop';


export interface MileageAllowance { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    travelExpense?: TravelExpense;
    rateType?: TravelExpenseRate;
    rateCategory?: TravelExpenseRateCategory;
    date: string;
    departureLocation: string;
    destination: string;
    km?: number;
    rate?: number;
    amount?: number;
    isCompanyCar?: boolean;
    /**
     * The corresponded number for the vehicleType. Default value = 0.
     */
    vehicleType?: number;
    /**
     * Link to individual passengers.
     */
    readonly passengers?: Array<Passenger>;
    passengerSupplement?: MileageAllowance;
    trailerSupplement?: MileageAllowance;
    tollCost?: Cost;
    /**
     * Link to individual mileage stops.
     */
    readonly drivingStops?: Array<DrivingStop>;
}

