/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MobileAppModules { 
    /**
     * Number of registered hours today.
     */
    readonly numberOfRegisteredHoursToday?: number;
    /**
     * Number of orders.
     */
    readonly numberOfOpenOrders?: number;
    /**
     * Number of travels & expenses for approval.
     */
    readonly numberOfTravelsAndExpensesForApproval?: number;
    /**
     * Number of vouchers for approval.
     */
    readonly numberOfVouchersForApproval?: number;
    /**
     * Number of pending approvals requested vacation days for approval.
     */
    readonly numberOfRequestedVacationDaysForApproval?: number;
    /**
     * Number of open and rejected travels & expenses.
     */
    readonly numberOfOpenAndRejectedTravelsExpenses?: number;
    /**
     * Number of payslips.
     */
    readonly numberOfPayslips?: number;
}

