/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MobileAppSpecificRightsInfo { 
    hourRegistrationEnabled?: boolean;
    projectEnabled?: boolean;
    departmentEnabled?: boolean;
    userIsAllowedToRegisterHours?: boolean;
    payrollAccountingEnabled?: boolean;
    userIsAuthWageMenu?: boolean;
    userIsAuthMySalary?: boolean;
    electronicVouchersEnabled?: boolean;
    travelExpenseEnabled?: boolean;
    documentArchiveEnabled?: boolean;
    archiveReceptionEnabled?: boolean;
    userIsPayslipOnly?: boolean;
    travelExpenseRatesEnabled?: boolean;
    taxFreeMileageRatesEnabled?: boolean;
    approveTravelExpenseEnabled?: boolean;
    userIsAuthProjectInfo?: boolean;
    userIsAuthTravelAndExpenseApprove?: boolean;
    userIsAuthEmployeeInfo?: boolean;
    userIsAuthVoucherApprove?: boolean;
    userIsAuthInvoicing?: boolean;
    userIsAuthCreateOrder?: boolean;
    vatOnForCompany?: boolean;
    taxFreeDietRatesEnabled?: boolean;
    travelDietIgnorePostingEnabled?: boolean;
    employeeEnabled?: boolean;
    hourBalanceEnabledForEmployee?: boolean;
    vacationBalanceEnabledForEmployee?: boolean;
    userIsAuthCreateCustomer?: boolean;
    userIsAuthProjectMenu?: boolean;
    userIsAuthCompanyAccountingReports?: boolean;
    vvselectroEnabled?: boolean;
    customerEnabled?: boolean;
    userIsAuthCustomerInfo?: boolean;
    userIsAuthProductAdmin?: boolean;
    userIsAuthDirectRemitAutopayAdmin?: boolean;
    userIsAuthDirectRemitAutopayLight?: boolean;
    userIsAuthDirectRemitZtl?: boolean;
}

