/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MobileAppLogin { 
    /**
     * Users username (email)
     */
    username: string;
    /**
     * Users password
     */
    password: string;
    /**
     * App secret
     */
    appSecret: string;
    /**
     * Expiration date for the combined token
     */
    expirationDate: string;
    /**
     * Optional employee ID. Default employee is used when null
     */
    employeeId?: number;
}

