/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { Change } from './change';


export interface MobileEmployee { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    firstName: string;
    lastName: string;
    readonly displayName?: string;
    employeeNumber?: string;
    department?: Department;
    dateOfBirth?: string;
    email?: string;
    /**
     * Determines if salary information can be registered on the user including hours, travel expenses and employee expenses. The user may also be selected as a project member on projects.
     */
    readonly allowInformationRegistration?: boolean;
    readonly isContact?: boolean;
    readonly pictureId?: number;
}

