/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { HourSummary } from './hourSummary';
import { Change } from './change';
import { TimesheetEntry } from './timesheetEntry';
import { FlexSummary } from './flexSummary';
import { VacationSummary } from './vacationSummary';


export interface MonthlyStatus { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    employee?: Employee;
    readonly timesheetEntries?: Array<TimesheetEntry>;
    readonly approvedDate?: string;
    readonly completed?: boolean;
    approvedBy?: Employee;
    readonly approved?: boolean;
    readonly approvedUntilDate?: string;
    readonly monthYear?: string;
    hoursPayout?: number;
    vacationPayout?: number;
    hourSummary?: HourSummary;
    flexSummary?: FlexSummary;
    vacationSummary?: VacationSummary;
}

