/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MySubscriptionModuleDTO { 
    readonly id?: number;
    readonly categoryType?: MySubscriptionModuleDTO.CategoryTypeEnum;
    readonly category?: string;
    readonly title?: string;
    readonly shortDescription?: string;
    readonly descriptionPart1?: string;
    readonly descriptionPart2?: string;
    readonly perUsePrice?: number;
    readonly perUserPrice?: number;
    readonly monthlyPrice?: number;
    readonly yearlyPrice?: number;
    readonly startUpPrice?: number;
    readonly perUserOverLimitPrice?: number;
    readonly priceDescription?: string;
    readonly active?: boolean;
    readonly available?: boolean;
    readonly processing?: boolean;
    readonly futurePurchase?: boolean;
    readonly infoText?: string;
    readonly agreementTitle?: string;
    readonly agreementText?: string;
    readonly unavailableText?: string;
    readonly licenseUrl?: string;
    readonly licenseText?: string;
    readonly redirectUrl?: string;
    readonly priceLine1Text?: string;
    readonly priceLine2Text?: string;
    readonly priceLine3Text?: string;
    readonly price1?: number;
    readonly price2?: number;
    readonly price3?: number;
    readonly canDeactivate?: boolean;
    readonly deactivationError?: string;
    readonly possibleStartDate?: string;
    readonly purchaseStartDate?: string;
    readonly purchaseEndDate?: string;
    readonly hasAutoInvoice?: boolean;
    readonly currencyCode?: string;
    ordered?: boolean;
}
export namespace MySubscriptionModuleDTO {
    export type CategoryTypeEnum = 'ACCOUNTING' | 'BANK_SERVICES' | 'INVOICE' | 'OTHER' | 'PACKAGE' | 'PROJECT_COST_MANAGEMENT' | 'VOUCHER_SERVICES' | 'WAREHOUSE_AND_LOGISTICS' | 'WAGE';
    export const CategoryTypeEnum = {
        Accounting: 'ACCOUNTING' as CategoryTypeEnum,
        BankServices: 'BANK_SERVICES' as CategoryTypeEnum,
        Invoice: 'INVOICE' as CategoryTypeEnum,
        Other: 'OTHER' as CategoryTypeEnum,
        Package: 'PACKAGE' as CategoryTypeEnum,
        ProjectCostManagement: 'PROJECT_COST_MANAGEMENT' as CategoryTypeEnum,
        VoucherServices: 'VOUCHER_SERVICES' as CategoryTypeEnum,
        WarehouseAndLogistics: 'WAREHOUSE_AND_LOGISTICS' as CategoryTypeEnum,
        Wage: 'WAGE' as CategoryTypeEnum
    };
}


