/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface News { 
    title?: string;
    publish_date?: string;
    excerpt?: string;
    permalink?: string;
}

