/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { NoteContainer } from './noteContainer';


export interface NoteOverview { 
    yearEndReport?: YearEndReport;
    noteContainers?: Array<NoteContainer>;
}

