/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';


export interface OpeningBalanceCustomerPosting { 
    customer: Customer;
    amount: number;
    description?: string;
}

