/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Project } from './project';
import { Department } from './department';
import { Employee } from './employee';
import { Product } from './product';


export interface OpeningBalanceBalancePosting { 
    account: Account;
    project?: Project;
    department?: Department;
    product?: Product;
    employee?: Employee;
    amount: number;
    /**
     * Only relevant for accounts in a different currency than the company currency, e.g an EUR account in a Norwegian company.  If provided on other accounts, it must always equal \'amount\'
     */
    amountCurrency?: number;
}

