/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderOutBuilder { 
    projectId?: number;
    companyId?: number;
    number?: string;
    invoiceComment?: string;
    type?: number;
}

