/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderLineBuilder { 
    projectId?: number;
    companyId?: number;
    invoiceId?: number;
    orderLineId?: number;
}

