/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericData } from './genericData';
import { RealizationAndRentalOfAssets } from './realizationAndRentalOfAssets';


export interface OtherCircumstancesOverview { 
    yearEndReport?: YearEndReport;
    posts?: Array<GenericData>;
    assetsCompanyPosts?: Array<RealizationAndRentalOfAssets>;
    assetsShareholderPosts?: Array<RealizationAndRentalOfAssets>;
}

