/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericData } from './genericData';


export interface ParticipantReportAcquisitionAndRealization { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * Acquisition and realization types
     */
    readonly transferType?: string;
    /**
     * Realization and acquisition transaction type codelist
     */
    readonly transactionType?: string;
    /**
     * Name
     */
    readonly name?: string;
    /**
     * Identification
     */
    readonly identification?: string;
    /**
     * Time
     */
    readonly time?: string;
    /**
     * Amount
     */
    readonly amount?: number;
    /**
     * Remuneration
     */
    readonly remuneration?: number;
    /**
     * Costs
     */
    readonly costs?: number;
    /**
     * Addition non deductible loss
     */
    readonly additionNonDeductibleLoss?: number;
    /**
     * Unused shielding previous years
     */
    readonly unusedShieldingPreviousYears?: number;
    /**
     * Other corrections
     */
    readonly otherCorrections?: number;
    /**
     * Gain loss realization
     */
    readonly gainLossRealization?: number;
    /**
     * Acquired initial value
     */
    readonly acquiredInitialValue?: number;
    /**
     * Price
     */
    readonly price?: number;
    /**
     * Initial value realized shares
     */
    readonly initialValueRealizedShares?: number;
    /**
     * Temporary gain loss realization
     */
    readonly temporaryGainLossRealization?: number;
    coveredExemptionMethod?: boolean;
}

