/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantReportPaidIn { 
    /**
     * Share of taxable equity at beginning of year
     */
    readonly shareOfTaxableEquityBeginningOfYear?: number;
    /**
     * Acquisition of share
     */
    readonly acquisitionOfShare?: number;
    /**
     * Disposal of share
     */
    readonly disposalOfShare?: number;
    /**
     * Deposit
     */
    readonly deposit?: number;
    /**
     * Other correction
     */
    readonly otherCorrection?: number;
    /**
     * Repayment
     */
    readonly repayment?: number;
    /**
     * Inadvertent deposit
     */
    readonly improperDeposit?: number;
    /**
     * Tax benefit from loss
     */
    readonly taxBenefitFromLoss?: number;
    /**
     * Tax capital equity as of end of year
     */
    readonly taxCapitalEquityAsOfEndOfYear?: number;
}

