/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantReportAdditionsToOrdinaryIncome { 
    /**
     * Distribution after tax
     */
    readonly distributionAfterTax?: number;
    /**
     * Other correction
     */
    readonly otherCorrection?: number;
    /**
     * Shielding deduction offset against distribution
     */
    readonly shieldingDeductionOffsetAgainstDistribution?: number;
    /**
     * Additions to ordinary income
     */
    readonly additionsToOrdinaryIncome?: number;
}

