/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantReportAcquisitionAndRealization } from './participantReportAcquisitionAndRealization';
import { ParticipantReportPaidIn } from './participantReportPaidIn';
import { Participant } from './participant';
import { ParticipantReportAgriculture } from './participantReportAgriculture';
import { ParticipantReportPriceAdjustmentManagement } from './participantReportPriceAdjustmentManagement';
import { ParticipantReportShieldingBasis } from './participantReportShieldingBasis';
import { ParticipantReportDistribution } from './participantReportDistribution';
import { ParticipantReportRetainedEarnings } from './participantReportRetainedEarnings';
import { ParticipantReportShieldingDeduction } from './participantReportShieldingDeduction';
import { ParticipantReportTaxBasisSpecification } from './participantReportTaxBasisSpecification';
import { ParticipantReportAdditionsToOrdinaryIncome } from './participantReportAdditionsToOrdinaryIncome';


export interface ParticipantReport { 
    participant?: Participant;
    /**
     * Share of assets and liabilities
     */
    readonly shareOfAssetsLiabilities?: number;
    /**
     * Share of deficit and surplus
     */
    readonly shareOfDeficitSurplus?: number;
    /**
     * Total labor remuneration
     */
    readonly totalLaborRemuneration?: number;
    /**
     * Total calculated capital
     */
    readonly calculatedTotalCapital?: number;
    /**
     * Shares realized or acquired
     */
    readonly sharesRealizedOrAcquired?: boolean;
    /**
     * Resides in Nord Troms or Finnnmark
     */
    readonly residentInNordTromsOrFinnmark?: boolean;
    /**
     * Compensation
     */
    readonly compensation?: number;
    agriculture?: ParticipantReportAgriculture;
    distribution?: ParticipantReportDistribution;
    calculationOfShieldingBasis?: ParticipantReportShieldingBasis;
    calculationOfShieldingDeduction?: ParticipantReportShieldingDeduction;
    calculationOfAdditionsToOrdinaryIncome?: ParticipantReportAdditionsToOrdinaryIncome;
    specificationOfTaxableBasis?: ParticipantReportTaxBasisSpecification;
    paidIn?: ParticipantReportPaidIn;
    retainedEarnings?: ParticipantReportRetainedEarnings;
    /**
     * Acquisition and Realization
     */
    readonly acquisitionAndRealization?: Array<ParticipantReportAcquisitionAndRealization>;
    priceAdjustmentManagement?: ParticipantReportPriceAdjustmentManagement;
}

