/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericData } from './genericData';


export interface Participant { 
    yearEndReport?: YearEndReport;
    readonly groupId?: number;
    readonly name?: string;
    readonly number?: string;
    readonly ownership?: number;
    readonly ownershipAtBeginningOfYear?: number;
    readonly shareOfResult?: number;
    readonly shareOfWealth?: number;
    posts?: Array<GenericData>;
}

