/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { Municipality } from './municipality';
import { GenericData } from './genericData';


export interface ParticipantAssessmentReport { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * Company name
     */
    companyName?: string;
    /**
     * Organization number
     */
    orgNumber?: string;
    municipality?: Municipality;
    /**
     * Country code
     */
    countryCode?: string;
    /**
     * Value before appreciation for net assets
     */
    valueBeforeAppreciationForNetAssets?: number;
    /**
     * Debt
     */
    debt?: number;
    /**
     * Ordinary income
     */
    ordinaryIncome?: number;
    /**
     * Loss
     */
    loss?: number;
    /**
     * Payment to participant
     */
    paymentToParticipant?: number;
    /**
     * Gain on realization of share
     */
    gainOnRealizationOfShare?: number;
    /**
     * Loss on realization of share
     */
    lossOnRealizationOfShare?: number;
}

