/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantReportAgriculture { 
    /**
     * Basis for calculation of agricultural deduction
     */
    readonly basisForCalculationOfAgriculturalDeduction?: number;
    /**
     * Rental income from agricultural operations
     */
    readonly rentalIncomeFromAgriculturalOperations?: number;
}

