/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantReportPriceAdjustmentManagement { 
    /**
     * Pricing adjustment
     */
    readonly pricingAdjustment?: number;
    /**
     * Realized share of price adjustment
     */
    readonly realizedShareOfPriceAdjustment?: number;
    /**
     * Realized share cost price
     */
    readonly realizedShareCostPrice?: number;
    /**
     * Realized share tax equity
     */
    readonly realizedShareTaxEquity?: number;
    /**
     * Accumulated adjustments
     */
    readonly accumulatedAdjustments?: number;
}

