/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentCardInfoDetails } from './paymentCardInfoDetails';


export interface PaymentCardInfoDTO { 
    /**
     * Amount of cancelled payments
     */
    readonly cancelled?: Array<PaymentCardInfoDetails>;
    /**
     * Amount of payments under processing
     */
    readonly underProcessing?: Array<PaymentCardInfoDetails>;
    /**
     * Amount of payments for approval
     */
    readonly forApproval?: Array<PaymentCardInfoDetails>;
}

