/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentTypeAutomation { 
    /**
     * Id corresponding to a Dropdown Type used in the Payment Widget\'s dropdown elements
     */
    id?: number;
    /**
     * Value of a Dropdown Type used in the Payment Widget\'s dropdown elements
     */
    description?: string;
    /**
     * The Payment Type (NETS, AUTOPAY, POSTING_RULE)
     */
    paymentIntegration?: PaymentTypeAutomation.PaymentIntegrationEnum;
}
export namespace PaymentTypeAutomation {
    export type PaymentIntegrationEnum = 'NONE' | 'NOT_PAID' | 'NETS' | 'AUTOPAY' | 'POSTING_RULE' | 'ZTL';
    export const PaymentIntegrationEnum = {
        None: 'NONE' as PaymentIntegrationEnum,
        NotPaid: 'NOT_PAID' as PaymentIntegrationEnum,
        Nets: 'NETS' as PaymentIntegrationEnum,
        Autopay: 'AUTOPAY' as PaymentIntegrationEnum,
        PostingRule: 'POSTING_RULE' as PaymentIntegrationEnum,
        Ztl: 'ZTL' as PaymentIntegrationEnum
    };
}


