/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { Change } from './change';


export interface PersonalIncome { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    yearEndReport?: YearEndReport;
    incomeGroupId: number;
    businessActivityType?: PersonalIncome.BusinessActivityTypeEnum;
    postType: PersonalIncome.PostTypeEnum;
    postValue: string;
}
export namespace PersonalIncome {
    export type BusinessActivityTypeEnum = 'OTHER_COMMERCIAL_ACTIVITIES' | 'OTHER_COMMERCIAL_ACTIVITIES_2' | 'OTHER_COMMERCIAL_ACTIVITIES_3' | 'OTHER_COMMERCIAL_ACTIVITIES_4' | 'AGRICULTURE_HORTICULTURE_FUR_FARMING' | 'FISHING_AND_HUNTING_AT_SEA' | 'REINDEER_HUSBANDRY' | 'FAMILY_DAY_CARE_CENTRE_IN_OWN_HOME' | 'SLATE_QUARRYING' | 'FORESTRY' | 'NOT_INDUSTRY';
    export const BusinessActivityTypeEnum = {
        OtherCommercialActivities: 'OTHER_COMMERCIAL_ACTIVITIES' as BusinessActivityTypeEnum,
        OtherCommercialActivities2: 'OTHER_COMMERCIAL_ACTIVITIES_2' as BusinessActivityTypeEnum,
        OtherCommercialActivities3: 'OTHER_COMMERCIAL_ACTIVITIES_3' as BusinessActivityTypeEnum,
        OtherCommercialActivities4: 'OTHER_COMMERCIAL_ACTIVITIES_4' as BusinessActivityTypeEnum,
        AgricultureHorticultureFurFarming: 'AGRICULTURE_HORTICULTURE_FUR_FARMING' as BusinessActivityTypeEnum,
        FishingAndHuntingAtSea: 'FISHING_AND_HUNTING_AT_SEA' as BusinessActivityTypeEnum,
        ReindeerHusbandry: 'REINDEER_HUSBANDRY' as BusinessActivityTypeEnum,
        FamilyDayCareCentreInOwnHome: 'FAMILY_DAY_CARE_CENTRE_IN_OWN_HOME' as BusinessActivityTypeEnum,
        SlateQuarrying: 'SLATE_QUARRYING' as BusinessActivityTypeEnum,
        Forestry: 'FORESTRY' as BusinessActivityTypeEnum,
        NotIndustry: 'NOT_INDUSTRY' as BusinessActivityTypeEnum
    };
    export type PostTypeEnum = 'INTEREST_ON_ENTERPRISE_DEBT' | 'CAPITAL_INCOME' | 'CAPITAL_EXPENSES' | 'REDUCTION_AMOUNT_FOR_RENTED_PROPERTY' | 'GAINS_FROM_REALISATION_AGRICULTURE_OR_FORESTRY' | 'NUMBER_OF_MONTHS_WITH_OPERATIONS' | 'RISK_FREE_INTEREST_RATE' | 'ENTERPRISE_DEBT_OB' | 'ENTERPRISE_DEBT_CB' | 'PROFIT_SHARE_SPOUSE' | 'NEGATIVE_PERSONAL_INCOME_PREVIOUS_YEAR' | 'COORDINATION_ENK' | 'COORDINATION_ANS_DA' | 'COORDINATION_LOTT' | 'NEGATIVE_PERSONAL_INCOME_CARRIED_FORWARD_NEXT_YEAR' | 'BUSINESS_TYPE_DESCRIPTION' | 'INDUSTRY_TYPE' | 'INCOME_AMOUNT_FROM_PROFIT_AND_LOSS_ACCOUNT' | 'DEDUCTED_AMOUNT_FROM_PROFIT_AND_LOSS_ACCOUNT' | 'DISTRIBUTE_INCOME' | 'NEGATIVE_PERSONAL_INCOME_PREVIOUS_YEAR_SPOUSE' | 'COORDINATION_ENK_SPOUSE' | 'COORDINATION_ANS_DA_SPOUSE' | 'COORDINATION_LOTT_SPOUSE' | 'NEGATIVE_PERSONAL_INCOME_CARRIED_FORWARD_NEXT_YEAR_SPOUSE';
    export const PostTypeEnum = {
        InterestOnEnterpriseDebt: 'INTEREST_ON_ENTERPRISE_DEBT' as PostTypeEnum,
        CapitalIncome: 'CAPITAL_INCOME' as PostTypeEnum,
        CapitalExpenses: 'CAPITAL_EXPENSES' as PostTypeEnum,
        ReductionAmountForRentedProperty: 'REDUCTION_AMOUNT_FOR_RENTED_PROPERTY' as PostTypeEnum,
        GainsFromRealisationAgricultureOrForestry: 'GAINS_FROM_REALISATION_AGRICULTURE_OR_FORESTRY' as PostTypeEnum,
        NumberOfMonthsWithOperations: 'NUMBER_OF_MONTHS_WITH_OPERATIONS' as PostTypeEnum,
        RiskFreeInterestRate: 'RISK_FREE_INTEREST_RATE' as PostTypeEnum,
        EnterpriseDebtOb: 'ENTERPRISE_DEBT_OB' as PostTypeEnum,
        EnterpriseDebtCb: 'ENTERPRISE_DEBT_CB' as PostTypeEnum,
        ProfitShareSpouse: 'PROFIT_SHARE_SPOUSE' as PostTypeEnum,
        NegativePersonalIncomePreviousYear: 'NEGATIVE_PERSONAL_INCOME_PREVIOUS_YEAR' as PostTypeEnum,
        CoordinationEnk: 'COORDINATION_ENK' as PostTypeEnum,
        CoordinationAnsDa: 'COORDINATION_ANS_DA' as PostTypeEnum,
        CoordinationLott: 'COORDINATION_LOTT' as PostTypeEnum,
        NegativePersonalIncomeCarriedForwardNextYear: 'NEGATIVE_PERSONAL_INCOME_CARRIED_FORWARD_NEXT_YEAR' as PostTypeEnum,
        BusinessTypeDescription: 'BUSINESS_TYPE_DESCRIPTION' as PostTypeEnum,
        IndustryType: 'INDUSTRY_TYPE' as PostTypeEnum,
        IncomeAmountFromProfitAndLossAccount: 'INCOME_AMOUNT_FROM_PROFIT_AND_LOSS_ACCOUNT' as PostTypeEnum,
        DeductedAmountFromProfitAndLossAccount: 'DEDUCTED_AMOUNT_FROM_PROFIT_AND_LOSS_ACCOUNT' as PostTypeEnum,
        DistributeIncome: 'DISTRIBUTE_INCOME' as PostTypeEnum,
        NegativePersonalIncomePreviousYearSpouse: 'NEGATIVE_PERSONAL_INCOME_PREVIOUS_YEAR_SPOUSE' as PostTypeEnum,
        CoordinationEnkSpouse: 'COORDINATION_ENK_SPOUSE' as PostTypeEnum,
        CoordinationAnsDaSpouse: 'COORDINATION_ANS_DA_SPOUSE' as PostTypeEnum,
        CoordinationLottSpouse: 'COORDINATION_LOTT_SPOUSE' as PostTypeEnum,
        NegativePersonalIncomeCarriedForwardNextYearSpouse: 'NEGATIVE_PERSONAL_INCOME_CARRIED_FORWARD_NEXT_YEAR_SPOUSE' as PostTypeEnum
    };
}


