/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PilotFeature { 
    companyId?: number;
    pilotFeatures?: Array<PilotFeature.PilotFeaturesEnum>;
}
export namespace PilotFeature {
    export type PilotFeaturesEnum = 'LOGISTICS' | 'REPORT_ENGINE' | 'MULTIPLE_LEDGERS' | 'FINANCIAL_SERVICES' | 'YEAR_END' | 'CREATE_SALARY_REDESIGN_MVP' | 'SALARY_REDESIGN_MVP' | 'NONE';
    export const PilotFeaturesEnum = {
        Logistics: 'LOGISTICS' as PilotFeaturesEnum,
        ReportEngine: 'REPORT_ENGINE' as PilotFeaturesEnum,
        MultipleLedgers: 'MULTIPLE_LEDGERS' as PilotFeaturesEnum,
        FinancialServices: 'FINANCIAL_SERVICES' as PilotFeaturesEnum,
        YearEnd: 'YEAR_END' as PilotFeaturesEnum,
        CreateSalaryRedesignMvp: 'CREATE_SALARY_REDESIGN_MVP' as PilotFeaturesEnum,
        SalaryRedesignMvp: 'SALARY_REDESIGN_MVP' as PilotFeaturesEnum,
        None: 'NONE' as PilotFeaturesEnum
    };
}


