/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostPrefill { 
    /**
     * Year where subject should be prefilled
     */
    year?: number;
    /**
     * Subject to prefill
     */
    subject: PostPrefill.SubjectEnum;
}
export namespace PostPrefill {
    export type SubjectEnum = 'REAL_ESTATE' | 'SHARES_AND_SECURITIES';
    export const SubjectEnum = {
        RealEstate: 'REAL_ESTATE' as SubjectEnum,
        SharesAndSecurities: 'SHARES_AND_SECURITIES' as SubjectEnum
    };
}


