/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Change } from './change';


export interface PostingRules { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    accountReceivableCustomersId?: Account;
    accountDebtVendorsId?: Account;
    accountDebtEmployeesAndOwnersId?: Account;
    accountRoundDiffId?: Account;
    /**
     * True if VAT postings generated by the system are done per department (when department is available), false if not
     */
    readonly vatPerDepartment?: boolean;
    /**
     * True if multiple industries are enabled, false if not.  If enabled, business activity types can be used to separate between different tax categories, and between general and primary VAT reports. This is done by setting a business activity type on the departments, as well as setting a default business activity type.
     */
    readonly multipleIndustries?: boolean;
    /**
     * The default business activity type for the company.  This is used when a department does not have a business activity type set, or no departmentId is given in a Posting.If multiple industries are not enabled, this value is not relevant.
     */
    readonly defaultBusinessActivityTypeId?: number;
}

