/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictionKey } from './predictionKey';


export interface PredictionLine { 
    readonly account?: string;
    readonly amount?: number;
    readonly vatNumber?: string;
    readonly vatPercentage?: number;
    readonly project?: string;
    readonly department?: string;
    key?: PredictionKey;
}

