/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PrepareTaxcardsArgsInternal { 
    employeeIds?: string;
    contactEmployeeId?: number;
    contactEmail?: string;
    taxcardYear?: number;
    mobilePhone?: string;
    mobilePhoneCountryId?: number;
    notificationType?: string;
}

