/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreviousSalaryAggregates { 
    readonly salaryTransactionId?: number;
    readonly wagePaymentIdOfEmployee?: number;
    readonly displayName?: string;
    readonly isAccessibleToLoggedInUser?: boolean;
}

