/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductBuilder { 
    companyId?: number;
    name?: string;
    description?: string;
    elNumber?: number;
    number?: number;
    vatType?: number;
    productUnitId?: number;
}

