/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { Product } from './product';
import { Stocktaking } from './stocktaking';
import { Change } from './change';
import { InventoryLocation } from './inventoryLocation';


export interface ProductLine { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    stocktaking: Stocktaking;
    product: Product;
    count?: number;
    /**
     * Unit price purchase (cost) excluding VAT in the order\'s currency
     */
    unitCostCurrency?: number;
    readonly costCurrency?: number;
    comment?: string;
    /**
     * If a line is counted or not - only for internal use; will return true/false based on whether the stocktaking is completed otherwise.
     */
    readonly counted?: boolean;
    counter?: Employee;
    /**
     * When the line was counted - only for internal use
     */
    readonly dateCounted?: string;
    /**
     * For internal use only
     */
    readonly expectedStock?: number;
    location?: InventoryLocation;
}

