/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';
import { ProductImportField } from './productImportField';
import { ProductImport } from './productImport';


export interface ProductImportHeader { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    productImport?: ProductImport;
    orderOfColumn?: number;
    name?: string;
    sampleValue?: string;
    suggestedColumnField?: ProductImportField;
}

