/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductImportRowErrorMessage } from './productImportRowErrorMessage';
import { Change } from './change';
import { ProductRowJSON } from './productRowJSON';
import { ProductImport } from './productImport';


export interface ProductPotential { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    productImport: ProductImport;
    rowContent?: ProductRowJSON;
    /**
     * errorMessage
     */
    errorMessage?: Array<ProductImportRowErrorMessage>;
    rowStatus?: ProductPotential.RowStatusEnum;
}
export namespace ProductPotential {
    export type RowStatusEnum = 'NEW' | 'UPDATE' | 'FAIL';
    export const RowStatusEnum = {
        New: 'NEW' as RowStatusEnum,
        Update: 'UPDATE' as RowStatusEnum,
        Fail: 'FAIL' as RowStatusEnum
    };
}


