/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericDataOverview } from './genericDataOverview';


export interface ProfitAndLoss { 
    yearEndReport?: YearEndReport;
    readonly sumProfit?: number;
    readonly sumLoss?: number;
    readonly sumProfitAndLoss?: number;
    readonly openingBalance?: number;
    readonly openingBalanceProfit?: number;
    readonly openingBalanceLoss?: number;
    readonly closingBalanceProfit?: number;
    readonly closingBalanceLoss?: number;
    readonly postedOpeningBalanceProfit?: number;
    readonly postedOpeningBalanceLoss?: number;
    readonly postedClosingBalanceProfit?: number;
    readonly postedClosingBalanceLoss?: number;
    readonly closingBalance?: number;
    readonly annualIncomeRecognition?: number;
    readonly annualDeduction?: number;
    readonly amountToBePostedOnIncomeRecognitionAccount?: number;
    readonly amountToBePostedOnDeductionAccount?: number;
    genericDataOverviews?: Array<GenericDataOverview>;
}

