/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectBudgetStatus { 
    readonly totalTotalIncomeCurrency?: number;
    readonly budgetTotalIncomeCurrency?: number;
    readonly budgetTotalCostCurrency?: number;
}

