/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectPeriodHourlyReport { 
    readonly chargeableHours?: number;
    readonly nonChargeableHours?: number;
    readonly approvedButUnchargedHours?: number;
    readonly nonApprovedHours?: number;
    readonly registeredHours?: number;
}

