/**
 * Project Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectsGet200ResponseInner { 
    /**
     * Unique identifier for the project.
     */
    id?: string;
    /**
     * Name of the project.
     */
    name?: string;
    /**
     * Brief description of the project.
     */
    description?: string;
}

