/**
 * Project Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Quick insights about the project.
 */
export interface ProjectsProjectIdInfoGet200ResponseInsights { 
    /**
     * Current status of the project.
     */
    status?: string;
    /**
     * Project progress percentage.
     */
    progress?: number;
}

