/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectPeriodMonthlyStatus { 
    readonly income?: number;
    readonly costs?: number;
    readonly dateFrom?: string;
    readonly dateTo?: string;
}

