/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Invoice } from './invoice';
import { Currency } from './currency';
import { Product } from './product';
import { Change } from './change';
import { VatType } from './vatType';
import { InventoryLocation } from './inventoryLocation';
import { Inventory } from './inventory';


export interface ProjectOrderLine { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    product?: Product;
    inventory?: Inventory;
    inventoryLocation?: InventoryLocation;
    description?: string;
    count?: number;
    /**
     * Unit price purchase (cost) excluding VAT in the order\'s currency
     */
    unitCostCurrency?: number;
    /**
     * Unit price of purchase excluding VAT in the order\'s currency
     */
    unitPriceExcludingVatCurrency?: number;
    currency?: Currency;
    /**
     * Markup given as a percentage (%)
     */
    markup?: number;
    /**
     * Discount given as a percentage (%)
     */
    discount?: number;
    vatType?: VatType;
    /**
     * Total amount on order line excluding VAT in the order\'s currency
     */
    readonly amountExcludingVatCurrency?: number;
    /**
     * Total amount on order line including VAT in the order\'s currency
     */
    readonly amountIncludingVatCurrency?: number;
    project: Project;
    date: string;
    isChargeable?: boolean;
    readonly isBudget?: boolean;
    invoice?: Invoice;
}

