/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Invoice } from './invoice';
import { Change } from './change';
import { VatType } from './vatType';


export interface ProjectInvoiceDetails { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    project?: Project;
    /**
     * Fee amount of the project. For example: 100 NOK.
     */
    readonly feeAmount?: number;
    /**
     * Fee amount of the project in the invoice currency.
     */
    readonly feeAmountCurrency?: number;
    /**
     * The percentage value of mark-up of amountFee. For example: 10%.
     */
    readonly markupPercent?: number;
    /**
     * The amount value of mark-up of amountFee on the project invoice. For example: 10 NOK.
     */
    readonly markupAmount?: number;
    /**
     * The amount value of mark-up of amountFee on the project invoice, in the invoice currency.
     */
    readonly markupAmountCurrency?: number;
    /**
     * The amount of chargeable manual order lines and vendor invoices on the project invoice.
     */
    readonly amountOrderLinesAndReinvoicing?: number;
    /**
     * The amount of chargeable manual order lines and vendor invoices on the project invoice, in the invoice currency.
     */
    readonly amountOrderLinesAndReinvoicingCurrency?: number;
    /**
     * The amount of travel costs and expenses on the project invoice.
     */
    readonly amountTravelReportsAndExpenses?: number;
    /**
     * The amount of travel costs and expenses on the project invoice, in the invoice currency.
     */
    readonly amountTravelReportsAndExpensesCurrency?: number;
    /**
     * The fee comment on the project invoice.
     */
    readonly feeInvoiceText?: string;
    /**
     * The comment on the project invoice.
     */
    readonly invoiceText?: string;
    /**
     * Determines if extra costs should be included on the project invoice.
     */
    readonly includeOrderLinesAndReinvoicing?: boolean;
    /**
     * Determines if hours should be included on the project invoice.
     */
    readonly includeHours?: boolean;
    /**
     * Determines if akonto should be included on the project invoice.
     */
    readonly includeOnAccountBalance?: boolean;
    /**
     * The akonto amount on the project invoice.
     */
    readonly onAccountBalanceAmount?: number;
    /**
     * The akonto amount on the project invoice in the invoice currency.
     */
    readonly onAccountBalanceAmountCurrency?: number;
    vatType?: VatType;
    invoice?: Invoice;
}

