/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectAccess { 
    accessOrderLines?: ProjectAccess.AccessOrderLinesEnum;
    accessHours?: ProjectAccess.AccessHoursEnum;
    accessAttachments?: ProjectAccess.AccessAttachmentsEnum;
    accessControlForms?: ProjectAccess.AccessControlFormsEnum;
}
export namespace ProjectAccess {
    export type AccessOrderLinesEnum = 'NONE' | 'READ' | 'WRITE';
    export const AccessOrderLinesEnum = {
        None: 'NONE' as AccessOrderLinesEnum,
        Read: 'READ' as AccessOrderLinesEnum,
        Write: 'WRITE' as AccessOrderLinesEnum
    };
    export type AccessHoursEnum = 'NONE' | 'READ' | 'WRITE';
    export const AccessHoursEnum = {
        None: 'NONE' as AccessHoursEnum,
        Read: 'READ' as AccessHoursEnum,
        Write: 'WRITE' as AccessHoursEnum
    };
    export type AccessAttachmentsEnum = 'NONE' | 'READ' | 'WRITE';
    export const AccessAttachmentsEnum = {
        None: 'NONE' as AccessAttachmentsEnum,
        Read: 'READ' as AccessAttachmentsEnum,
        Write: 'WRITE' as AccessAttachmentsEnum
    };
    export type AccessControlFormsEnum = 'NONE' | 'READ' | 'WRITE';
    export const AccessControlFormsEnum = {
        None: 'NONE' as AccessControlFormsEnum,
        Read: 'READ' as AccessControlFormsEnum,
        Write: 'WRITE' as AccessControlFormsEnum
    };
}


