/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Department } from './department';
import { Employee } from './employee';
import { ProjectCategory } from './projectCategory';
import { Customer } from './customer';


export interface ProjectOverviewAggregate { 
    id?: number;
    name?: string;
    displayName?: string;
    number?: string;
    startDate?: string;
    endDate?: string;
    isReadyForInvoicing?: boolean;
    isClosed?: boolean;
    isFixedPrice?: boolean;
    isInternal?: boolean;
    isAuthProjectOverviewContractType?: boolean;
    projectManager?: Employee;
    customer?: Customer;
    mainProject?: Project;
    department?: Department;
    projectCategory?: ProjectCategory;
    plannedBudget?: number;
    completedBudget?: number;
    /**
     * READ/WRITE access on project
     */
    accessType?: ProjectOverviewAggregate.AccessTypeEnum;
    invoiceReserveTotalAmountCurrency?: number;
    invoiceAkontoReserveAmountCurrency?: number;
    invoiceExtracostsReserveCurrency?: number;
    invoiceFeeReserveCurrency?: number;
    hoursToApprove?: number;
    invoicesToApprove?: number;
    expensesToApprove?: number;
    vouchersToApprove?: number;
    isProjectAttestor?: boolean;
}
export namespace ProjectOverviewAggregate {
    export type AccessTypeEnum = 'NONE' | 'READ' | 'WRITE';
    export const AccessTypeEnum = {
        None: 'NONE' as AccessTypeEnum,
        Read: 'READ' as AccessTypeEnum,
        Write: 'WRITE' as AccessTypeEnum
    };
}


