/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Activity } from './activity';
import { Change } from './change';


export interface ProjectActivity { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    activity?: Activity;
    project?: Project;
    startDate?: string;
    endDate?: string;
    isClosed?: boolean;
    /**
     * Set budget hours
     */
    budgetHours?: number;
    /**
     * Set budget hourly rate
     */
    budgetHourlyRateCurrency?: number;
    /**
     * Set budget fee
     */
    budgetFeeCurrency?: number;
}

