/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectControlFormType } from './projectControlFormType';


export interface ProjectSettings { 
    approveHourLists?: boolean;
    approveInvoices?: boolean;
    markReadyForInvoicing?: boolean;
    historicalInformation?: boolean;
    projectForecast?: boolean;
    budgetOnSubcontracts?: boolean;
    projectCategories?: boolean;
    referenceFee?: boolean;
    sortOrderProjects?: ProjectSettings.SortOrderProjectsEnum;
    autoCloseInvoicedProjects?: boolean;
    mustApproveRegisteredHours?: boolean;
    showProjectOrderLinesToAllProjectParticipants?: boolean;
    hourCostPercentage?: boolean;
    fixedPriceProjectsFeeCalcMethod?: ProjectSettings.FixedPriceProjectsFeeCalcMethodEnum;
    fixedPriceProjectsInvoiceByProgress?: boolean;
    projectBudgetReferenceFee?: boolean;
    allowMultipleProjectInvoiceVat?: boolean;
    standardReinvoicing?: boolean;
    isCurrentMonthDefaultPeriod?: boolean;
    showProjectOnboarding?: boolean;
    autoConnectIncomingOrderlineToProject?: boolean;
    autoGenerateProjectNumber?: boolean;
    autoGenerateStartingNumber?: number;
    projectNameScheme?: ProjectSettings.ProjectNameSchemeEnum;
    projectTypeOfContract?: ProjectSettings.ProjectTypeOfContractEnum;
    projectOrderLinesSortOrder?: ProjectSettings.ProjectOrderLinesSortOrderEnum;
    projectHourlyRateModel?: ProjectSettings.ProjectHourlyRateModelEnum;
    onlyProjectMembersCanRegisterInfo?: boolean;
    onlyProjectActivitiesTimesheetRegistration?: boolean;
    hourlyRateProjectsWriteUpDown?: boolean;
    showRecentlyClosedProjectsOnSupplierInvoice?: boolean;
    defaultProjectContractComment?: string;
    defaultProjectInvoicingComment?: string;
    resourcePlanning?: boolean;
    resourceGroups?: boolean;
    holidayPlan?: boolean;
    resourcePlanPeriod?: ProjectSettings.ResourcePlanPeriodEnum;
    /**
     * Control forms required for invoicing
     */
    controlFormsRequiredForInvoicing?: Array<ProjectControlFormType>;
    /**
     * Control forms required for hour tracking
     */
    controlFormsRequiredForHourTracking?: Array<ProjectControlFormType>;
    /**
     * Dynamic control form ids required for invoicing
     */
    dynamicControlFormIdsRequiredForInvoicing?: Array<number>;
    /**
     * Dynamic control form ids required for hour tracking
     */
    dynamicControlFormIdsRequiredForHourTracking?: Array<number>;
    useLoggedInUserEmailOnProjectBudget?: boolean;
    emailOnProjectBudget?: string;
    useLoggedInUserEmailOnProjectContract?: boolean;
    emailOnProjectContract?: string;
    useLoggedInUserEmailOnDocuments?: boolean;
    emailOnDocuments?: string;
    useProductNetPrice?: boolean;
}
export namespace ProjectSettings {
    export type SortOrderProjectsEnum = 'SORT_ORDER_NAME_AND_NUMBER' | 'SORT_ORDER_NAME';
    export const SortOrderProjectsEnum = {
        SortOrderNameAndNumber: 'SORT_ORDER_NAME_AND_NUMBER' as SortOrderProjectsEnum,
        SortOrderName: 'SORT_ORDER_NAME' as SortOrderProjectsEnum
    };
    export type FixedPriceProjectsFeeCalcMethodEnum = 'FIXED_PRICE_PROJECTS_CALC_METHOD_INVOICED_FEE' | 'FIXED_PRICE_PROJECTS_CALC_METHOD_PERCENT_COMPLETED';
    export const FixedPriceProjectsFeeCalcMethodEnum = {
        FixedPriceProjectsCalcMethodInvoicedFee: 'FIXED_PRICE_PROJECTS_CALC_METHOD_INVOICED_FEE' as FixedPriceProjectsFeeCalcMethodEnum,
        FixedPriceProjectsCalcMethodPercentCompleted: 'FIXED_PRICE_PROJECTS_CALC_METHOD_PERCENT_COMPLETED' as FixedPriceProjectsFeeCalcMethodEnum
    };
    export type ProjectNameSchemeEnum = 'NAME_STANDARD' | 'NAME_INCL_CUSTOMER_NAME' | 'NAME_INCL_PARENT_NAME' | 'NAME_INCL_PARENT_NUMBER' | 'NAME_INCL_PARENT_NAME_AND_NUMBER';
    export const ProjectNameSchemeEnum = {
        NameStandard: 'NAME_STANDARD' as ProjectNameSchemeEnum,
        NameInclCustomerName: 'NAME_INCL_CUSTOMER_NAME' as ProjectNameSchemeEnum,
        NameInclParentName: 'NAME_INCL_PARENT_NAME' as ProjectNameSchemeEnum,
        NameInclParentNumber: 'NAME_INCL_PARENT_NUMBER' as ProjectNameSchemeEnum,
        NameInclParentNameAndNumber: 'NAME_INCL_PARENT_NAME_AND_NUMBER' as ProjectNameSchemeEnum
    };
    export type ProjectTypeOfContractEnum = 'PROJECT_FIXED_PRICE' | 'PROJECT_HOUR_RATES';
    export const ProjectTypeOfContractEnum = {
        ProjectFixedPrice: 'PROJECT_FIXED_PRICE' as ProjectTypeOfContractEnum,
        ProjectHourRates: 'PROJECT_HOUR_RATES' as ProjectTypeOfContractEnum
    };
    export type ProjectOrderLinesSortOrderEnum = 'SORT_ORDER_ID' | 'SORT_ORDER_DATE' | 'SORT_ORDER_PRODUCT' | 'SORT_ORDER_CUSTOM';
    export const ProjectOrderLinesSortOrderEnum = {
        SortOrderId: 'SORT_ORDER_ID' as ProjectOrderLinesSortOrderEnum,
        SortOrderDate: 'SORT_ORDER_DATE' as ProjectOrderLinesSortOrderEnum,
        SortOrderProduct: 'SORT_ORDER_PRODUCT' as ProjectOrderLinesSortOrderEnum,
        SortOrderCustom: 'SORT_ORDER_CUSTOM' as ProjectOrderLinesSortOrderEnum
    };
    export type ProjectHourlyRateModelEnum = 'TYPE_PREDEFINED_HOURLY_RATES' | 'TYPE_PROJECT_SPECIFIC_HOURLY_RATES' | 'TYPE_FIXED_HOURLY_RATE';
    export const ProjectHourlyRateModelEnum = {
        TypePredefinedHourlyRates: 'TYPE_PREDEFINED_HOURLY_RATES' as ProjectHourlyRateModelEnum,
        TypeProjectSpecificHourlyRates: 'TYPE_PROJECT_SPECIFIC_HOURLY_RATES' as ProjectHourlyRateModelEnum,
        TypeFixedHourlyRate: 'TYPE_FIXED_HOURLY_RATE' as ProjectHourlyRateModelEnum
    };
    export type ResourcePlanPeriodEnum = 'PERIOD_MONTH' | 'PERIOD_WEEK' | 'PERIOD_DAY';
    export const ResourcePlanPeriodEnum = {
        PeriodMonth: 'PERIOD_MONTH' as ResourcePlanPeriodEnum,
        PeriodWeek: 'PERIOD_WEEK' as ResourcePlanPeriodEnum,
        PeriodDay: 'PERIOD_DAY' as ResourcePlanPeriodEnum
    };
}


