/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectManager { 
    /**
     * The employeeId of the employee to be added as a project manager
     */
    employeeId?: number;
    /**
     * The display name of the employee that can be project manager
     */
    displayName?: string;
    /**
     * Specifies whether the employee can invoice
     */
    canInvoice: boolean;
}

