/**
 * Project Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectsProjectIdInfoGet200ResponseInsights } from './projectsProjectIdInfoGet200ResponseInsights';


export interface ProjectsProjectIdInfoGet200Response { 
    /**
     * The ID of the project.
     */
    id?: string;
    suggestions?: Array<string>;
    insights?: ProjectsProjectIdInfoGet200ResponseInsights;
}

