/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Employee } from './employee';
import { Customer } from './customer';
import { Change } from './change';


export interface Prospect { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    name?: string;
    description?: string;
    createdDate: string;
    customer?: Customer;
    salesEmployee?: Employee;
    isClosed?: boolean;
    closedReason?: number;
    closedDate?: string;
    competitor?: string;
    prospectType?: number;
    project?: Project;
    projectOffer?: Project;
    /**
     * The estimated start date for income on the prospect.
     */
    finalIncomeDate?: string;
    /**
     * The estimated startup fee on this prospect.
     */
    finalInitialValue?: number;
    /**
     * The estimated monthly fee on this prospect.
     */
    finalMonthlyValue?: number;
    /**
     * Tripletex specific.
     */
    finalAdditionalServicesValue?: number;
    /**
     * The estimated total fee on this prospect.
     */
    readonly totalValue?: number;
}

