/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { Country } from './country';
import { Change } from './change';


export interface PurchaseOrderAddress { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    addressLine1?: string;
    addressLine2?: string;
    postalCode?: string;
    city?: string;
    country?: Country;
    displayName?: string;
    readonly addressAsString?: string;
    readonly displayNameInklMatrikkel?: string;
    knr?: number;
    gnr?: number;
    bnr?: number;
    fnr?: number;
    snr?: number;
    unitNumber?: string;
    name?: string;
    customerVendor?: Customer;
}

