/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PurchaseOrder } from './purchaseOrder';
import { Change } from './change';
import { Voucher } from './voucher';


export interface PurchaseOrderIncomingInvoiceRelation { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    orderOut: PurchaseOrder;
    voucher: Voucher;
}

