/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RealizationAndRentalOfAssets { 
    readonly groupId?: number;
    readonly genericDataType?: RealizationAndRentalOfAssets.GenericDataTypeEnum;
    readonly genericDataSubType?: RealizationAndRentalOfAssets.GenericDataSubTypeEnum;
    readonly genericDataSubTypeGroupId?: number;
    readonly assetType?: RealizationAndRentalOfAssets.AssetTypeEnum;
    readonly pricingMethod?: RealizationAndRentalOfAssets.PricingMethodEnum;
    readonly rentalValue?: number;
    readonly valueOfSaleOrWithdrawal?: number;
}
export namespace RealizationAndRentalOfAssets {
    export type GenericDataTypeEnum = 'MISC' | 'TRANSPORT' | 'ACCOMMODATION_AND_RESTAURANT' | 'PROFIT_AND_LOSS' | 'CUSTOMER_RECEIVABLE' | 'INVENTORIES' | 'TANGIBLE_FIXED_ASSETS' | 'RECONCILIATION_OF_EQUITY' | 'PERMANENT_DIFFERENCES' | 'TEMPORARY_DIFFERENCES' | 'DOCUMENT_DOWNLOADED' | 'GROUP_CONTRIBUTIONS' | 'TAX_RETURN' | 'TAX_CALCULATIONS' | 'DOCUMENTATION' | 'SHARES_AND_SECURITIES' | 'REAL_ESTATE' | 'PARTICIPANT' | 'SALARY_AND_PENSION_EXPENSES' | 'COOPERATIVE_ENTERPRISE' | 'OTHER_CIRCUMSTANCES' | 'RESEARCH_AND_DEVELOPMENT' | 'TIMBER_ACCOUNT' | 'CONTROLLED_TRANSACTIONS' | 'PARTICIPANT_ASSESSMENT_REPORT' | 'CONTROLLED_TRANSACTIONS_COMPANY_SPECIFICATION' | 'INTEREST_LIMITATION' | 'DOCUMENT_WITH_ALTINN_ID';
    export const GenericDataTypeEnum = {
        Misc: 'MISC' as GenericDataTypeEnum,
        Transport: 'TRANSPORT' as GenericDataTypeEnum,
        AccommodationAndRestaurant: 'ACCOMMODATION_AND_RESTAURANT' as GenericDataTypeEnum,
        ProfitAndLoss: 'PROFIT_AND_LOSS' as GenericDataTypeEnum,
        CustomerReceivable: 'CUSTOMER_RECEIVABLE' as GenericDataTypeEnum,
        Inventories: 'INVENTORIES' as GenericDataTypeEnum,
        TangibleFixedAssets: 'TANGIBLE_FIXED_ASSETS' as GenericDataTypeEnum,
        ReconciliationOfEquity: 'RECONCILIATION_OF_EQUITY' as GenericDataTypeEnum,
        PermanentDifferences: 'PERMANENT_DIFFERENCES' as GenericDataTypeEnum,
        TemporaryDifferences: 'TEMPORARY_DIFFERENCES' as GenericDataTypeEnum,
        DocumentDownloaded: 'DOCUMENT_DOWNLOADED' as GenericDataTypeEnum,
        GroupContributions: 'GROUP_CONTRIBUTIONS' as GenericDataTypeEnum,
        TaxReturn: 'TAX_RETURN' as GenericDataTypeEnum,
        TaxCalculations: 'TAX_CALCULATIONS' as GenericDataTypeEnum,
        Documentation: 'DOCUMENTATION' as GenericDataTypeEnum,
        SharesAndSecurities: 'SHARES_AND_SECURITIES' as GenericDataTypeEnum,
        RealEstate: 'REAL_ESTATE' as GenericDataTypeEnum,
        Participant: 'PARTICIPANT' as GenericDataTypeEnum,
        SalaryAndPensionExpenses: 'SALARY_AND_PENSION_EXPENSES' as GenericDataTypeEnum,
        CooperativeEnterprise: 'COOPERATIVE_ENTERPRISE' as GenericDataTypeEnum,
        OtherCircumstances: 'OTHER_CIRCUMSTANCES' as GenericDataTypeEnum,
        ResearchAndDevelopment: 'RESEARCH_AND_DEVELOPMENT' as GenericDataTypeEnum,
        TimberAccount: 'TIMBER_ACCOUNT' as GenericDataTypeEnum,
        ControlledTransactions: 'CONTROLLED_TRANSACTIONS' as GenericDataTypeEnum,
        ParticipantAssessmentReport: 'PARTICIPANT_ASSESSMENT_REPORT' as GenericDataTypeEnum,
        ControlledTransactionsCompanySpecification: 'CONTROLLED_TRANSACTIONS_COMPANY_SPECIFICATION' as GenericDataTypeEnum,
        InterestLimitation: 'INTEREST_LIMITATION' as GenericDataTypeEnum,
        DocumentWithAltinnId: 'DOCUMENT_WITH_ALTINN_ID' as GenericDataTypeEnum
    };
    export type GenericDataSubTypeEnum = 'NONE' | 'NOT_LICENSED' | 'FREIGHT_TRANSPORT' | 'TAXI' | 'ACQUISITION_AND_REALIZATION' | 'PRODUCT_TYPE_INVENTORY' | 'CASH_REGISTER_SYSTEM' | 'PRIVATE_WITHDRAWAL_OF_GOODS' | 'ENTERTAINMENT' | 'MULTI_UNIT_BUILDING_UNIT' | 'RENTAL_WITHDRAWAL_SALE_COMPANY' | 'RENTAL_WITHDRAWAL_SALE_SHAREHOLDER' | 'RESOLUTION' | 'OTHER_PUBLIC_SUPPORT' | 'RELATED_COMPANY' | 'FUNCTION_AND_RISK' | 'TRANSACTION' | 'OUTSTANDING' | 'INTEREST_EXPENSES_TO_COMPANY_IN_SAME_GROUP' | 'INTEREST_EXPENSES_TO_OTHER_GROUP_GUARANTOR' | 'INTEREST_EXPENSES_TO_OTHER_WITH_OUTSTANDING_CLAIM' | 'COMPANIES_INCLUDED_IN_NORWEGIAN_PART_OF_GROUP' | 'INTEREST_INCOME_FROM_COMPANY_IN_SAME_GROUP' | 'INTEREST_EXPENSES_TO_RELATED_PARTY_OUTSIDE_GROUP' | 'INTEREST_EXPENSES_TO_RELATED_PARTY_OUTSIDE_GROUP_OTHER_GROUP_GUARANTOR' | 'INTEREST_EXPENSES_TO_RELATED_PARTY_OUTSIDE_GROUP_OTHER_WITH_OUTSTANDING_CLAIM' | 'INTEREST_INCOME_FROM_RELATED_PARTY_OUTSIDE_GROUP' | 'FORWARDING_DISALLOWED_INTEREST_DEDUCTION';
    export const GenericDataSubTypeEnum = {
        None: 'NONE' as GenericDataSubTypeEnum,
        NotLicensed: 'NOT_LICENSED' as GenericDataSubTypeEnum,
        FreightTransport: 'FREIGHT_TRANSPORT' as GenericDataSubTypeEnum,
        Taxi: 'TAXI' as GenericDataSubTypeEnum,
        AcquisitionAndRealization: 'ACQUISITION_AND_REALIZATION' as GenericDataSubTypeEnum,
        ProductTypeInventory: 'PRODUCT_TYPE_INVENTORY' as GenericDataSubTypeEnum,
        CashRegisterSystem: 'CASH_REGISTER_SYSTEM' as GenericDataSubTypeEnum,
        PrivateWithdrawalOfGoods: 'PRIVATE_WITHDRAWAL_OF_GOODS' as GenericDataSubTypeEnum,
        Entertainment: 'ENTERTAINMENT' as GenericDataSubTypeEnum,
        MultiUnitBuildingUnit: 'MULTI_UNIT_BUILDING_UNIT' as GenericDataSubTypeEnum,
        RentalWithdrawalSaleCompany: 'RENTAL_WITHDRAWAL_SALE_COMPANY' as GenericDataSubTypeEnum,
        RentalWithdrawalSaleShareholder: 'RENTAL_WITHDRAWAL_SALE_SHAREHOLDER' as GenericDataSubTypeEnum,
        Resolution: 'RESOLUTION' as GenericDataSubTypeEnum,
        OtherPublicSupport: 'OTHER_PUBLIC_SUPPORT' as GenericDataSubTypeEnum,
        RelatedCompany: 'RELATED_COMPANY' as GenericDataSubTypeEnum,
        FunctionAndRisk: 'FUNCTION_AND_RISK' as GenericDataSubTypeEnum,
        Transaction: 'TRANSACTION' as GenericDataSubTypeEnum,
        Outstanding: 'OUTSTANDING' as GenericDataSubTypeEnum,
        InterestExpensesToCompanyInSameGroup: 'INTEREST_EXPENSES_TO_COMPANY_IN_SAME_GROUP' as GenericDataSubTypeEnum,
        InterestExpensesToOtherGroupGuarantor: 'INTEREST_EXPENSES_TO_OTHER_GROUP_GUARANTOR' as GenericDataSubTypeEnum,
        InterestExpensesToOtherWithOutstandingClaim: 'INTEREST_EXPENSES_TO_OTHER_WITH_OUTSTANDING_CLAIM' as GenericDataSubTypeEnum,
        CompaniesIncludedInNorwegianPartOfGroup: 'COMPANIES_INCLUDED_IN_NORWEGIAN_PART_OF_GROUP' as GenericDataSubTypeEnum,
        InterestIncomeFromCompanyInSameGroup: 'INTEREST_INCOME_FROM_COMPANY_IN_SAME_GROUP' as GenericDataSubTypeEnum,
        InterestExpensesToRelatedPartyOutsideGroup: 'INTEREST_EXPENSES_TO_RELATED_PARTY_OUTSIDE_GROUP' as GenericDataSubTypeEnum,
        InterestExpensesToRelatedPartyOutsideGroupOtherGroupGuarantor: 'INTEREST_EXPENSES_TO_RELATED_PARTY_OUTSIDE_GROUP_OTHER_GROUP_GUARANTOR' as GenericDataSubTypeEnum,
        InterestExpensesToRelatedPartyOutsideGroupOtherWithOutstandingClaim: 'INTEREST_EXPENSES_TO_RELATED_PARTY_OUTSIDE_GROUP_OTHER_WITH_OUTSTANDING_CLAIM' as GenericDataSubTypeEnum,
        InterestIncomeFromRelatedPartyOutsideGroup: 'INTEREST_INCOME_FROM_RELATED_PARTY_OUTSIDE_GROUP' as GenericDataSubTypeEnum,
        ForwardingDisallowedInterestDeduction: 'FORWARDING_DISALLOWED_INTEREST_DEDUCTION' as GenericDataSubTypeEnum
    };
    export type AssetTypeEnum = 'EMPTY' | 'GOODS' | 'RESIDENTIAL_PROPERTY' | 'HOLIDAY_PROPERTY' | 'OTHER_PROPERTY' | 'CAR' | 'MOTORHOMES' | 'MOTORCYCLES' | 'OTHER_VEHICLES' | 'BOAT' | 'HELICOPTER' | 'PLANE' | 'OTHER_WEALTH';
    export const AssetTypeEnum = {
        Empty: 'EMPTY' as AssetTypeEnum,
        Goods: 'GOODS' as AssetTypeEnum,
        ResidentialProperty: 'RESIDENTIAL_PROPERTY' as AssetTypeEnum,
        HolidayProperty: 'HOLIDAY_PROPERTY' as AssetTypeEnum,
        OtherProperty: 'OTHER_PROPERTY' as AssetTypeEnum,
        Car: 'CAR' as AssetTypeEnum,
        Motorhomes: 'MOTORHOMES' as AssetTypeEnum,
        Motorcycles: 'MOTORCYCLES' as AssetTypeEnum,
        OtherVehicles: 'OTHER_VEHICLES' as AssetTypeEnum,
        Boat: 'BOAT' as AssetTypeEnum,
        Helicopter: 'HELICOPTER' as AssetTypeEnum,
        Plane: 'PLANE' as AssetTypeEnum,
        OtherWealth: 'OTHER_WEALTH' as AssetTypeEnum
    };
    export type PricingMethodEnum = 'SELF_ASSESSED_VALUE' | 'VALUATION_BY_A_VALUER' | 'VALUATION_BY_A_THIRD_PARTY' | 'OTHER_VALUATION';
    export const PricingMethodEnum = {
        SelfAssessedValue: 'SELF_ASSESSED_VALUE' as PricingMethodEnum,
        ValuationByAValuer: 'VALUATION_BY_A_VALUER' as PricingMethodEnum,
        ValuationByAThirdParty: 'VALUATION_BY_A_THIRD_PARTY' as PricingMethodEnum,
        OtherValuation: 'OTHER_VALUATION' as PricingMethodEnum
    };
}


