/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReconciliationSelectedState { 
    /**
     * Total sum for selected postings
     */
    readonly sumSelectedPostings?: number;
    /**
     * Total sum for selected transactions
     */
    readonly sumSelectedTransactions?: number;
    readonly selectedDifference?: number;
    /**
     * Flag to show difference for selected entries
     */
    readonly showDifference?: boolean;
    /**
     * Flag to show manual match button for selected entries
     */
    readonly showManualMatch?: boolean;
    /**
     * Flag to show enter balance button for selected entries
     */
    readonly showPostBalance?: boolean;
    /**
     * Flag to show transfer entries button for selected entries
     */
    readonly showTransferEntries?: boolean;
    /**
     * Flag to show post transactions entries button for selected entries
     */
    readonly showPostEntries?: boolean;
}

