/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';
import { ReconciliationGroup } from './reconciliationGroup';


export interface ReconciliationMatch { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Id of the BankReconciliation.
     */
    reconciliationId?: number;
    /**
     * Is this BankReconciliationMatch approved.
     */
    readonly isApproved?: boolean;
    postingsGroup?: ReconciliationGroup;
    transactionsGroup?: ReconciliationGroup;
}

