/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReminderWidgetDTO } from './reminderWidgetDTO';


export interface ReminderDTO { 
    readonly reminders?: Array<ReminderWidgetDTO>;
}

