/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReminderChargeAndInterest { 
    /**
     * chargedAmount
     */
    readonly chargeAmount?: number;
    /**
     * interestAmount
     */
    readonly interestAmount?: number;
    /**
     * interestPercentage
     */
    readonly interestPercentage?: number;
    /**
     * currency
     */
    currency?: string;
}

