/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface RemunerationType { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Defines the remuneration type option. 
     */
    remunerationType: RemunerationType.RemunerationTypeEnum;
    nameNO?: string;
    code?: string;
}
export namespace RemunerationType {
    export type RemunerationTypeEnum = 'MONTHLY_WAGE' | 'HOURLY_WAGE' | 'COMMISION_PERCENTAGE' | 'FEE' | 'NOT_CHOSEN' | 'PIECEWORK_WAGE';
    export const RemunerationTypeEnum = {
        MonthlyWage: 'MONTHLY_WAGE' as RemunerationTypeEnum,
        HourlyWage: 'HOURLY_WAGE' as RemunerationTypeEnum,
        CommisionPercentage: 'COMMISION_PERCENTAGE' as RemunerationTypeEnum,
        Fee: 'FEE' as RemunerationTypeEnum,
        NotChosen: 'NOT_CHOSEN' as RemunerationTypeEnum,
        PieceworkWage: 'PIECEWORK_WAGE' as RemunerationTypeEnum
    };
}


