/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Report } from './report';
import { ReportAuthorization } from './reportAuthorization';


export interface ReportAccess { 
    report?: Report;
    grant?: ReportAuthorization;
    /**
     * The reason for having access
     */
    readonly reason?: ReportAccess.ReasonEnum;
}
export namespace ReportAccess {
    export type ReasonEnum = 'Global' | 'Owner' | 'Administrator' | 'Shared' | 'None';
    export const ReasonEnum = {
        Global: 'Global' as ReasonEnum,
        Owner: 'Owner' as ReasonEnum,
        Administrator: 'Administrator' as ReasonEnum,
        Shared: 'Shared' as ReasonEnum,
        None: 'None' as ReasonEnum
    };
}


