/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportSingularFilter } from './reportSingularFilter';


export interface ReportActivityFilter { 
    filters?: Array<ReportSingularFilter>;
    complement?: boolean;
    version?: number;
}

