/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportGroupOrderBy { 
    order?: ReportGroupOrderBy.OrderEnum;
    expression?: string;
}
export namespace ReportGroupOrderBy {
    export type OrderEnum = 'Ascending' | 'Descending';
    export const OrderEnum = {
        Ascending: 'Ascending' as OrderEnum,
        Descending: 'Descending' as OrderEnum
    };
}


