/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportResultCellValue { 
    value?: object;
    type?: ReportResultCellValue.TypeEnum;
}
export namespace ReportResultCellValue {
    export type TypeEnum = 'NULL' | 'NUMBER' | 'STRING' | 'BOOLEAN' | 'DATE' | 'ERROR' | 'REFERENCE' | 'ARRAY' | 'OBJECT';
    export const TypeEnum = {
        Null: 'NULL' as TypeEnum,
        Number: 'NUMBER' as TypeEnum,
        String: 'STRING' as TypeEnum,
        Boolean: 'BOOLEAN' as TypeEnum,
        Date: 'DATE' as TypeEnum,
        Error: 'ERROR' as TypeEnum,
        Reference: 'REFERENCE' as TypeEnum,
        Array: 'ARRAY' as TypeEnum,
        Object: 'OBJECT' as TypeEnum
    };
}


