/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportResultCellValue } from './reportResultCellValue';


export interface ReportResultRowHeader { 
    value?: ReportResultCellValue;
    formatted?: string;
    style?: Array<string>;
    children?: Array<ReportResultRowHeader>;
    initiallyExpanded?: boolean;
    sourceRef?: string;
    autoGroupType?: number;
    leafCount?: number;
    depth?: number;
    link?: string;
}

