/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportSettingsHeaders { 
    showColumnHeaders?: boolean;
    showRowHeaders?: boolean;
    columnHeaderVisibilityExpression?: string;
    rowHeaderVisibilityExpression?: string;
    version?: number;
}

