/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportSettingsFiltersOptionsPeriod { 
    divisions?: { [key: string]: boolean; };
    shortcuts?: { [key: string]: boolean; };
    stepSize?: ReportSettingsFiltersOptionsPeriod.StepSizeEnum;
    initialValueProvider?: ReportSettingsFiltersOptionsPeriod.InitialValueProviderEnum;
    start?: string;
    end?: string;
    version?: number;
}
export namespace ReportSettingsFiltersOptionsPeriod {
    export type StepSizeEnum = 'Day' | 'Week' | 'Month' | 'WageTerm' | 'VatTerm' | 'Year';
    export const StepSizeEnum = {
        Day: 'Day' as StepSizeEnum,
        Week: 'Week' as StepSizeEnum,
        Month: 'Month' as StepSizeEnum,
        WageTerm: 'WageTerm' as StepSizeEnum,
        VatTerm: 'VatTerm' as StepSizeEnum,
        Year: 'Year' as StepSizeEnum
    };
    export type InitialValueProviderEnum = 'All' | 'ThisDay' | 'ThisWeek' | 'NextSevenDays' | 'NextThirtyDays' | 'ThisMonth' | 'ThisYear' | 'SoFarThisWeek' | 'SoFarThisMonth' | 'SoFarThisYear';
    export const InitialValueProviderEnum = {
        All: 'All' as InitialValueProviderEnum,
        ThisDay: 'ThisDay' as InitialValueProviderEnum,
        ThisWeek: 'ThisWeek' as InitialValueProviderEnum,
        NextSevenDays: 'NextSevenDays' as InitialValueProviderEnum,
        NextThirtyDays: 'NextThirtyDays' as InitialValueProviderEnum,
        ThisMonth: 'ThisMonth' as InitialValueProviderEnum,
        ThisYear: 'ThisYear' as InitialValueProviderEnum,
        SoFarThisWeek: 'SoFarThisWeek' as InitialValueProviderEnum,
        SoFarThisMonth: 'SoFarThisMonth' as InitialValueProviderEnum,
        SoFarThisYear: 'SoFarThisYear' as InitialValueProviderEnum
    };
}


