/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportResultRowHeader } from './reportResultRowHeader';
import { ReportResultCell } from './reportResultCell';
import { ReportResultColumnHeader } from './reportResultColumnHeader';


export interface ReportResult { 
    name?: string;
    columnHeaders?: Array<ReportResultColumnHeader>;
    rowHeaders?: Array<ReportResultRowHeader>;
    tableContent?: Array<Array<ReportResultCell>>;
    rowDepth?: number;
    height?: number;
    width?: number;
    columnDepth?: number;
}

