/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { GenericData } from './genericData';


export interface ResearchAndDevelopmentResolution { 
    yearEndReport?: YearEndReport;
    /**
     * Group ID
     */
    groupId?: number;
    /**
     * Sub group ID
     */
    subGroupId?: number;
    /**
     * Associated posts
     */
    posts?: Array<GenericData>;
    /**
     * The date of the resolution
     */
    date?: string;
    /**
     * The type of the resolution
     */
    type?: ResearchAndDevelopmentResolution.TypeEnum;
    /**
     * The delimitation of the resolution
     */
    delimitation?: string;
}
export namespace ResearchAndDevelopmentResolution {
    export type TypeEnum = 'NONE' | 'DELIMITATION' | 'PROCESSING_AFTER_APPROVED_COMPLAINT' | 'APPROVAL_RESCINDED' | 'ADMINISTRATIVELY_APPROVED_COMPLAINT' | 'COMPLAINT_RECEIVED' | 'PROJECT_CANCELLED' | 'FINAL_REPORT_APPROVED' | 'FINAL_REPORT_SENT' | 'FINAL_REPORT_RETURNED' | 'FINAL_REPORT_PENDING' | 'APPLICATION_REJECTED' | 'APPLICATION_APPROVED' | 'ANNUAL_REPORT_APPROVED' | 'ANNUAL_REPORT_SENT' | 'ANNUAL_REPORT_RETURNED' | 'ANNUAL_REPORT_PENDING';
    export const TypeEnum = {
        None: 'NONE' as TypeEnum,
        Delimitation: 'DELIMITATION' as TypeEnum,
        ProcessingAfterApprovedComplaint: 'PROCESSING_AFTER_APPROVED_COMPLAINT' as TypeEnum,
        ApprovalRescinded: 'APPROVAL_RESCINDED' as TypeEnum,
        AdministrativelyApprovedComplaint: 'ADMINISTRATIVELY_APPROVED_COMPLAINT' as TypeEnum,
        ComplaintReceived: 'COMPLAINT_RECEIVED' as TypeEnum,
        ProjectCancelled: 'PROJECT_CANCELLED' as TypeEnum,
        FinalReportApproved: 'FINAL_REPORT_APPROVED' as TypeEnum,
        FinalReportSent: 'FINAL_REPORT_SENT' as TypeEnum,
        FinalReportReturned: 'FINAL_REPORT_RETURNED' as TypeEnum,
        FinalReportPending: 'FINAL_REPORT_PENDING' as TypeEnum,
        ApplicationRejected: 'APPLICATION_REJECTED' as TypeEnum,
        ApplicationApproved: 'APPLICATION_APPROVED' as TypeEnum,
        AnnualReportApproved: 'ANNUAL_REPORT_APPROVED' as TypeEnum,
        AnnualReportSent: 'ANNUAL_REPORT_SENT' as TypeEnum,
        AnnualReportReturned: 'ANNUAL_REPORT_RETURNED' as TypeEnum,
        AnnualReportPending: 'ANNUAL_REPORT_PENDING' as TypeEnum
    };
}


