/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourcePlanEmployee } from './resourcePlanEmployee';


export interface ResourcePlanActivity { 
    activityId?: number;
    activityName?: string;
    /**
     * List of EmployeeResourcePlanDTO
     */
    employeeEntries?: Array<ResourcePlanEmployee>;
}

