/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourcePlanHours } from './resourcePlanHours';


export interface ResourcePlanEmployee { 
    employeeId?: number;
    employeeName?: string;
    budget?: number;
    remaining?: number;
    totalHours?: number;
    totalAllocated?: number;
    /**
     * List of HoursResourcePlanDTO
     */
    hoursEntries?: Array<ResourcePlanHours>;
}

