/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourcePlanActivity } from './resourcePlanActivity';


export interface ResourcePlanBudget { 
    projectId?: number;
    projectName?: string;
    periodStart?: string;
    periodEnd?: string;
    periodType?: ResourcePlanBudget.PeriodTypeEnum;
    /**
     * List of ActivityResourcePlanDTO
     */
    activityEntries?: Array<ResourcePlanActivity>;
}
export namespace ResourcePlanBudget {
    export type PeriodTypeEnum = 'HOUR' | 'DAY' | 'WEEK' | 'MONTH';
    export const PeriodTypeEnum = {
        Hour: 'HOUR' as PeriodTypeEnum,
        Day: 'DAY' as PeriodTypeEnum,
        Week: 'WEEK' as PeriodTypeEnum,
        Month: 'MONTH' as PeriodTypeEnum
    };
}


