/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankReconciliationMatchesCounter } from './bankReconciliationMatchesCounter';


export interface ResponseWrapperBankReconciliationMatchesCounter { 
    value?: BankReconciliationMatchesCounter;
}

