/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2Transaction } from './salaryV2Transaction';


export interface ResponseWrapperSalaryV2Transaction { 
    value?: SalaryV2Transaction;
}

