/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VatReturnsValidationResult } from './vatReturnsValidationResult';


export interface ResponseWrapperVatReturnsValidationResult { 
    value?: VatReturnsValidationResult;
}

