/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerReceivable } from './customerReceivable';


export interface ResponseWrapperCustomerReceivable { 
    value?: CustomerReceivable;
}

