/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyChooserCompany } from './companyChooserCompany';


export interface ResponseWrapperListCompanyChooserCompany { 
    value?: Array<CompanyChooserCompany>;
}

