/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndAnnualAccountsFreeNote } from './yearEndAnnualAccountsFreeNote';


export interface ResponseWrapperYearEndAnnualAccountsFreeNote { 
    value?: YearEndAnnualAccountsFreeNote;
}

