/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Checkout } from './checkout';


export interface ResponseWrapperCheckout { 
    value?: Checkout;
}

