/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseWrapperAccessStatus { 
    value?: ResponseWrapperAccessStatus.ValueEnum;
}
export namespace ResponseWrapperAccessStatus {
    export type ValueEnum = 'YES' | 'NO' | 'UNKNOWN';
    export const ValueEnum = {
        Yes: 'YES' as ValueEnum,
        No: 'NO' as ValueEnum,
        Unknown: 'UNKNOWN' as ValueEnum
    };
}


