/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxReturnOverview } from './taxReturnOverview';


export interface ResponseWrapperTaxReturnOverview { 
    value?: TaxReturnOverview;
}

