/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RP2EmployeeJobMoveResponse } from './rP2EmployeeJobMoveResponse';


export interface ResponseWrapperRP2EmployeeJobMoveResponse { 
    value?: RP2EmployeeJobMoveResponse;
}

