/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneralLedgerCloseGroup } from './generalLedgerCloseGroup';


export interface ResponseWrapperGeneralLedgerCloseGroup { 
    value?: GeneralLedgerCloseGroup;
}

