/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2EmployeeToEmploymentsRelationship } from './salaryV2EmployeeToEmploymentsRelationship';


export interface ResponseWrapperListSalaryV2EmployeeToEmploymentsRelationship { 
    value?: Array<SalaryV2EmployeeToEmploymentsRelationship>;
}

