/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegacyAddress } from './legacyAddress';


export interface ResponseWrapperLegacyAddress { 
    value?: LegacyAddress;
}

