/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VatReturns2022 } from './vatReturns2022';


export interface ResponseWrapperVatReturns2022 { 
    value?: VatReturns2022;
}

