/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimesheetAllocated } from './timesheetAllocated';


export interface ResponseWrapperTimesheetAllocated { 
    value?: TimesheetAllocated;
}

