/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentationGenericData } from './documentationGenericData';


export interface ResponseWrapperListDocumentationGenericData { 
    value?: Array<DocumentationGenericData>;
}

