/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RP2JobTemplate } from './rP2JobTemplate';


export interface ResponseWrapperRP2JobTemplate { 
    value?: RP2JobTemplate;
}

