/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BringCredentials } from './bringCredentials';


export interface ResponseWrapperBringCredentials { 
    value?: BringCredentials;
}

