/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountingPeriod } from './accountingPeriod';


export interface ResponseWrapperAccountingPeriod { 
    value?: AccountingPeriod;
}

