/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndShareholderRegister } from './yearEndShareholderRegister';


export interface ResponseWrapperYearEndShareholderRegister { 
    value?: YearEndShareholderRegister;
}

