/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantReport } from './participantReport';


export interface ResponseWrapperParticipantReport { 
    value?: ParticipantReport;
}

