/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientInbox } from './clientInbox';


export interface ResponseWrapperListClientInbox { 
    value?: Array<ClientInbox>;
}

