/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyStandardTime } from './companyStandardTime';


export interface ResponseWrapperCompanyStandardTime { 
    value?: CompanyStandardTime;
}

