/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Disposition } from './disposition';


export interface ResponseWrapperDisposition { 
    value?: Disposition;
}

