/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2Settings } from './salaryV2Settings';


export interface ResponseWrapperSalaryV2Settings { 
    value?: SalaryV2Settings;
}

