/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZtlConsentWarning } from './ztlConsentWarning';


export interface ResponseWrapperZtlConsentWarning { 
    value?: ZtlConsentWarning;
}

