/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseWrapperSignatureStatus { 
    value?: ResponseWrapperSignatureStatus.ValueEnum;
}
export namespace ResponseWrapperSignatureStatus {
    export type ValueEnum = 'NOT_SIGNED' | 'PENDING_SIGNATURE' | 'SIGNED' | 'NOT_A_SIGNER';
    export const ValueEnum = {
        NotSigned: 'NOT_SIGNED' as ValueEnum,
        PendingSignature: 'PENDING_SIGNATURE' as ValueEnum,
        Signed: 'SIGNED' as ValueEnum,
        NotASigner: 'NOT_A_SIGNER' as ValueEnum
    };
}


