/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleCategoryContainer } from './roleCategoryContainer';


export interface ResponseWrapperListRoleCategoryContainer { 
    value?: Array<RoleCategoryContainer>;
}

