/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2Specification } from './salaryV2Specification';


export interface ResponseWrapperSalaryV2Specification { 
    value?: SalaryV2Specification;
}

