/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RP2ModalPermissions } from './rP2ModalPermissions';


export interface ResponseWrapperRP2ModalPermissions { 
    value?: RP2ModalPermissions;
}

