/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxCalculation } from './taxCalculation';


export interface ResponseWrapperTaxCalculation { 
    value?: TaxCalculation;
}

