/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseWrapperAddonStatusType { 
    value?: ResponseWrapperAddonStatusType.ValueEnum;
}
export namespace ResponseWrapperAddonStatusType {
    export type ValueEnum = 'IN_DEVELOPMENT' | 'PENDING' | 'REJECTED' | 'APPROVED';
    export const ValueEnum = {
        InDevelopment: 'IN_DEVELOPMENT' as ValueEnum,
        Pending: 'PENDING' as ValueEnum,
        Rejected: 'REJECTED' as ValueEnum,
        Approved: 'APPROVED' as ValueEnum
    };
}


