/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RP2Permissions } from './rP2Permissions';


export interface ResponseWrapperRP2Permissions { 
    value?: RP2Permissions;
}

