/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountClosureFeedback } from './accountClosureFeedback';


export interface ResponseWrapperAccountClosureFeedback { 
    value?: AccountClosureFeedback;
}

