/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerImport } from './customerImport';


export interface ResponseWrapperCustomerImport { 
    value?: CustomerImport;
}

