/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncomeAndCostSummaryDTO } from './incomeAndCostSummaryDTO';


export interface ResponseWrapperIncomeAndCostSummaryDTO { 
    value?: IncomeAndCostSummaryDTO;
}

