/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductGroupRelation } from './productGroupRelation';


export interface ResponseWrapperProductGroupRelation { 
    value?: ProductGroupRelation;
}

