/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiscountPolicy } from './discountPolicy';


export interface ResponseWrapperDiscountPolicy { 
    value?: DiscountPolicy;
}

