/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2TravelExpense } from './salaryV2TravelExpense';


export interface ResponseWrapperSalaryV2TravelExpense { 
    value?: SalaryV2TravelExpense;
}

