/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentReceptionPageContext } from './documentReceptionPageContext';


export interface ResponseWrapperDocumentReceptionPageContext { 
    value?: DocumentReceptionPageContext;
}

