/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeCategory } from './employeeCategory';


export interface ResponseWrapperEmployeeCategory { 
    value?: EmployeeCategory;
}

