/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2PaymentType } from './salaryV2PaymentType';


export interface ResponseWrapperListSalaryV2PaymentType { 
    value?: Array<SalaryV2PaymentType>;
}

