/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2Payment } from './salaryV2Payment';


export interface ResponseWrapperSalaryV2Payment { 
    value?: SalaryV2Payment;
}

