/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyAuthority } from './companyAuthority';


export interface ResponseWrapperCompanyAuthority { 
    value?: CompanyAuthority;
}

