/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlobalReminder } from './globalReminder';


export interface ResponseWrapperGlobalReminder { 
    value?: GlobalReminder;
}

