/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportAuthorization } from './reportAuthorization';


export interface ResponseWrapperReportAuthorization { 
    value?: ReportAuthorization;
}

