/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalProduct } from './externalProduct';


export interface ResponseWrapperExternalProduct { 
    value?: ExternalProduct;
}

