/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccommodationAllowance } from './accommodationAllowance';


export interface ResponseWrapperAccommodationAllowance { 
    value?: AccommodationAllowance;
}

