/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoggedInUserInfo } from './loggedInUserInfo';


export interface ResponseWrapperLoggedInUserInfo { 
    value?: LoggedInUserInfo;
}

