/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2Type } from './salaryV2Type';


export interface ResponseWrapperSalaryV2Type { 
    value?: SalaryV2Type;
}

