/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseWrapperListDocumentArchiveModelType { 
    value?: Array<ResponseWrapperListDocumentArchiveModelType.ValueEnum>;
}
export namespace ResponseWrapperListDocumentArchiveModelType {
    export type ValueEnum = 'NONE' | 'CUSTOMER' | 'SUPPLIER' | 'PROJECT' | 'ORDER' | 'OFFER' | 'PROJECT_OFFER' | 'PRODUCT' | 'EMPLOYEE' | 'ACCOUNT' | 'ASSET';
    export const ValueEnum = {
        None: 'NONE' as ValueEnum,
        Customer: 'CUSTOMER' as ValueEnum,
        Supplier: 'SUPPLIER' as ValueEnum,
        Project: 'PROJECT' as ValueEnum,
        Order: 'ORDER' as ValueEnum,
        Offer: 'OFFER' as ValueEnum,
        ProjectOffer: 'PROJECT_OFFER' as ValueEnum,
        Product: 'PRODUCT' as ValueEnum,
        Employee: 'EMPLOYEE' as ValueEnum,
        Account: 'ACCOUNT' as ValueEnum,
        Asset: 'ASSET' as ValueEnum
    };
}


