/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RP2ProjectJobMoveResponse } from './rP2ProjectJobMoveResponse';


export interface ResponseWrapperRP2ProjectJobMoveResponse { 
    value?: RP2ProjectJobMoveResponse;
}

