/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceOptions } from './invoiceOptions';


export interface ResponseWrapperInvoiceOptions { 
    value?: InvoiceOptions;
}

