/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeToken } from './employeeToken';


export interface ResponseWrapperEmployeeToken { 
    value?: EmployeeToken;
}

