/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncomingInvoiceDataRead } from './incomingInvoiceDataRead';


export interface ResponseWrapperIncomingInvoiceDataRead { 
    value?: IncomingInvoiceDataRead;
}

