/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryAndPensionSums } from './salaryAndPensionSums';


export interface ResponseWrapperSalaryAndPensionSums { 
    value?: SalaryAndPensionSums;
}

