/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankStatement } from './bankStatement';


export interface ResponseWrapperBankStatement { 
    value?: BankStatement;
}

