/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RP2EmployeeJob { 
    id?: number;
    label?: string;
    subLabel?: string;
    duration?: number;
    durationUnit?: string;
    periodId?: number;
    subPeriodId?: number;
    startDate?: string;
    startTime?: string;
    endTime?: string;
}

