/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RP2EmployeeJobMoveResponse { 
    jobId?: number;
    employeeIds?: Array<number>;
}

