/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalaryV2VoucherOverview { 
    readonly id?: number;
    readonly voucherNumberAsString?: string;
    readonly datePeriod?: string;
    voucherDate?: string;
    readonly displayName?: string;
    readonly ameldingWageId?: number;
    readonly voucherId?: number;
    ameldingDueDate?: string;
    readonly ameldingStatus?: SalaryV2VoucherOverview.AmeldingStatusEnum;
    readonly eniBasis?: number;
    paymentDate?: string;
    comment?: string;
    readonly isReversed?: boolean;
    readonly wagePeriodTransactionId?: number;
    readonly wagePeriodTransactionVoucherNumber?: string;
    readonly reversedVoucherDisplayName?: string;
    readonly reversedBy?: string;
    readonly completedLogId?: number;
    readonly isHistorical?: boolean;
}
export namespace SalaryV2VoucherOverview {
    export type AmeldingStatusEnum = 'NEUTRAL' | 'SUCCESS' | 'WARNING' | 'WARNING_GUIDELINE' | 'ERROR' | 'ERROR_IMMEDIATELY' | 'ERROR_REJECTED';
    export const AmeldingStatusEnum = {
        Neutral: 'NEUTRAL' as AmeldingStatusEnum,
        Success: 'SUCCESS' as AmeldingStatusEnum,
        Warning: 'WARNING' as AmeldingStatusEnum,
        WarningGuideline: 'WARNING_GUIDELINE' as AmeldingStatusEnum,
        Error: 'ERROR' as AmeldingStatusEnum,
        ErrorImmediately: 'ERROR_IMMEDIATELY' as AmeldingStatusEnum,
        ErrorRejected: 'ERROR_REJECTED' as AmeldingStatusEnum
    };
}


