/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryV2Voucher } from './salaryV2Voucher';
import { SalaryV2PaymentType } from './salaryV2PaymentType';
import { Change } from './change';
import { Document } from './document';
import { SalaryV2Payment } from './salaryV2Payment';


export interface SalaryV2Transaction { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    readonly displayName?: string;
    /**
     * Voucher date.
     */
    date?: string;
    year: number;
    month: number;
    periodAsString?: string;
    /**
     * With historical wage vouchers you can update the wage system with information dated before the opening balance.
     */
    isHistorical?: boolean;
    /**
     * Employee National Insurance calculation method
     */
    payrollTaxCalcMethod?: string;
    /**
     * Comment on voucher
     */
    voucherComment?: string;
    /**
     * Comment to be shown on all payslips
     */
    payslipGeneralComment?: string;
    completed?: boolean;
    reversed?: boolean;
    reverser?: boolean;
    okAllowReverseDifferentDate?: boolean;
    /**
     * The date payslips are made available to the employee. Defaults to voucherDate.
     */
    paySlipsAvailableDate?: string;
    /**
     * Link to individual payslip objects.
     */
    salaryPayments: Array<SalaryV2Payment>;
    /**
     * The date payslips are paid
     */
    paymentDate?: string;
    /**
     * List of messages that explain why voucher cannot be deleted
     */
    readonly notDeletableMessage?: Array<string>;
    hasBankTransfers?: boolean;
    voucher?: SalaryV2Voucher;
    /**
     * True if bank payments are deletable
     */
    allowDeletePayments?: boolean;
    readonly sumPaidAmount?: number;
    readonly sumTaxDeductionAmount?: number;
    anyExternalChangesOnThisTransaction?: boolean;
    attachment?: Document;
    readonly ameldingWageId?: number;
    containsNegativeWps?: boolean;
    useLandscapeForBankList?: boolean;
    readonly numberEmployees?: number;
    readonly wagePeriodTransactionId?: number;
    readonly ameldingWageNumber?: number;
    readonly wagePeriodTransactionNumber?: number;
    readonly reverseVoucherDisplayName?: string;
    readonly urlDetails?: string;
    paymentType?: SalaryV2PaymentType;
}

