/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalaryV2Modules { 
    /**
     * Module department
     */
    readonly moduleDepartment?: boolean;
    /**
     * Module Nets
     */
    readonly moduleNets?: boolean;
    /**
     * Module Autopay
     */
    readonly moduleAutopay?: boolean;
    /**
     * Module Ztl
     */
    readonly moduleZtl?: boolean;
    /**
     * Module Agro
     */
    readonly moduleAgro?: boolean;
    /**
     * Module Mamut
     */
    readonly moduleMamut?: boolean;
    /**
     * Module Encrypted Payslip
     */
    readonly moduleEncryptedPayslip?: boolean;
    /**
     * Module Union Deduction
     */
    readonly moduleUnionDeduction?: boolean;
    /**
     * Module Free Company Car
     */
    readonly moduleFreeCompanyCar?: boolean;
    /**
     * Module Mesan
     */
    readonly moduleMesan?: boolean;
    /**
     * Module department accounting
     */
    readonly moduleDepartmentAccounting?: boolean;
    /**
     * Module wage project accounting
     */
    readonly moduleWageProjectAccounting?: boolean;
    /**
     * Module Electronic vouchers
     */
    readonly moduleElectronicVoucher?: boolean;
    /**
     * Module seamen deduction
     */
    readonly moduleSeamenDeduction?: boolean;
}

