/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryCompilationLine } from './salaryCompilationLine';


export interface SalaryCompilation { 
    readonly employee?: number;
    readonly year?: number;
    readonly vacationPayBasis?: number;
    readonly wages?: Array<SalaryCompilationLine>;
    readonly expenses?: Array<SalaryCompilationLine>;
    readonly taxDeductions?: Array<SalaryCompilationLine>;
    readonly mandatoryTaxDeductions?: Array<SalaryCompilationLine>;
}

