/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalarySettingsInternal { 
    /**
     * Is salary paid in advance
     */
    isPaidInAdvance?: boolean;
    /**
     * Month for half tax
     */
    halfTaxMonth: SalarySettingsInternal.HalfTaxMonthEnum;
    /**
     * Month for salary correction
     */
    vacationCorrectionMonth: SalarySettingsInternal.VacationCorrectionMonthEnum;
    /**
     * Month for vacation
     */
    vacationMonth: SalarySettingsInternal.VacationMonthEnum;
    /**
     * Month for vacation pay
     */
    vacationPayMonth: SalarySettingsInternal.VacationPayMonthEnum;
    /**
     * Company has free car
     */
    isFreeCar?: boolean;
    /**
     * Company has union deduction
     */
    isUnionDeduction?: boolean;
    /**
     * Bank account number of tax account
     */
    taxBankAccountNumber?: string;
}
export namespace SalarySettingsInternal {
    export type HalfTaxMonthEnum = 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER' | 'NOT_CHOSEN';
    export const HalfTaxMonthEnum = {
        January: 'JANUARY' as HalfTaxMonthEnum,
        February: 'FEBRUARY' as HalfTaxMonthEnum,
        March: 'MARCH' as HalfTaxMonthEnum,
        April: 'APRIL' as HalfTaxMonthEnum,
        May: 'MAY' as HalfTaxMonthEnum,
        June: 'JUNE' as HalfTaxMonthEnum,
        July: 'JULY' as HalfTaxMonthEnum,
        August: 'AUGUST' as HalfTaxMonthEnum,
        September: 'SEPTEMBER' as HalfTaxMonthEnum,
        October: 'OCTOBER' as HalfTaxMonthEnum,
        November: 'NOVEMBER' as HalfTaxMonthEnum,
        December: 'DECEMBER' as HalfTaxMonthEnum,
        NotChosen: 'NOT_CHOSEN' as HalfTaxMonthEnum
    };
    export type VacationCorrectionMonthEnum = 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER' | 'NOT_CHOSEN';
    export const VacationCorrectionMonthEnum = {
        January: 'JANUARY' as VacationCorrectionMonthEnum,
        February: 'FEBRUARY' as VacationCorrectionMonthEnum,
        March: 'MARCH' as VacationCorrectionMonthEnum,
        April: 'APRIL' as VacationCorrectionMonthEnum,
        May: 'MAY' as VacationCorrectionMonthEnum,
        June: 'JUNE' as VacationCorrectionMonthEnum,
        July: 'JULY' as VacationCorrectionMonthEnum,
        August: 'AUGUST' as VacationCorrectionMonthEnum,
        September: 'SEPTEMBER' as VacationCorrectionMonthEnum,
        October: 'OCTOBER' as VacationCorrectionMonthEnum,
        November: 'NOVEMBER' as VacationCorrectionMonthEnum,
        December: 'DECEMBER' as VacationCorrectionMonthEnum,
        NotChosen: 'NOT_CHOSEN' as VacationCorrectionMonthEnum
    };
    export type VacationMonthEnum = 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER' | 'NOT_CHOSEN';
    export const VacationMonthEnum = {
        January: 'JANUARY' as VacationMonthEnum,
        February: 'FEBRUARY' as VacationMonthEnum,
        March: 'MARCH' as VacationMonthEnum,
        April: 'APRIL' as VacationMonthEnum,
        May: 'MAY' as VacationMonthEnum,
        June: 'JUNE' as VacationMonthEnum,
        July: 'JULY' as VacationMonthEnum,
        August: 'AUGUST' as VacationMonthEnum,
        September: 'SEPTEMBER' as VacationMonthEnum,
        October: 'OCTOBER' as VacationMonthEnum,
        November: 'NOVEMBER' as VacationMonthEnum,
        December: 'DECEMBER' as VacationMonthEnum,
        NotChosen: 'NOT_CHOSEN' as VacationMonthEnum
    };
    export type VacationPayMonthEnum = 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER' | 'NOT_CHOSEN';
    export const VacationPayMonthEnum = {
        January: 'JANUARY' as VacationPayMonthEnum,
        February: 'FEBRUARY' as VacationPayMonthEnum,
        March: 'MARCH' as VacationPayMonthEnum,
        April: 'APRIL' as VacationPayMonthEnum,
        May: 'MAY' as VacationPayMonthEnum,
        June: 'JUNE' as VacationPayMonthEnum,
        July: 'JULY' as VacationPayMonthEnum,
        August: 'AUGUST' as VacationPayMonthEnum,
        September: 'SEPTEMBER' as VacationPayMonthEnum,
        October: 'OCTOBER' as VacationPayMonthEnum,
        November: 'NOVEMBER' as VacationPayMonthEnum,
        December: 'DECEMBER' as VacationPayMonthEnum,
        NotChosen: 'NOT_CHOSEN' as VacationPayMonthEnum
    };
}


