/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Department } from './department';
import { Employee } from './employee';
import { SalaryType } from './salaryType';
import { Change } from './change';
import { Payslip } from './payslip';


export interface SalarySpecification { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    rate: number;
    count: number;
    project?: Project;
    department?: Department;
    salaryType: SalaryType;
    payslip?: Payslip;
    employee?: Employee;
    description?: string;
    year?: number;
    month?: number;
    amount?: number;
}

