/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiValidationMessage } from './apiValidationMessage';
import { SalaryV2Specification } from './salaryV2Specification';
import { Country } from './country';
import { Change } from './change';


export interface SalaryV2Supplement { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    salarySpecification?: SalaryV2Specification;
    country?: Country;
    taxCountry?: Country;
    carNumberOfKm?: number;
    carNumberOfKmToHomeOrWork?: number;
    carListPrice?: number;
    carRegistrationNumber?: string;
    numberOfJourneys?: number;
    upgrossingBasis?: number;
    upgrossingTableNumber?: number;
    yearOfIncome?: number;
    deductedArtistTax?: number;
    taxPaidAbroad?: number;
    continentalShaft?: boolean;
    /**
     * start date, currently only for Norwegian Continental Shaft
     */
    startDate?: string;
    /**
     * end date, currently only for Norwegian Continental Shaft
     */
    endDate?: string;
    numberOfDays?: number;
    readonly validations?: Array<ApiValidationMessage>;
}

