/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';


export interface SalaryAndPensionAccountInfo { 
    account?: Account;
    readonly groupId?: number;
    readonly outgoingBalance?: number;
    readonly additions?: number;
    readonly deductions?: number;
    readonly totalNotifiableBenefits?: number;
    readonly benefitSubjectToEmployerTax?: number;
}

