/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalesModule { 
    name: SalesModule.NameEnum;
    costStartDate?: string;
}
export namespace SalesModule {
    export type NameEnum = 'MAMUT' | 'MAMUT_WITH_WAGE' | 'AGRO_LICENCE' | 'AGRO_CLIENT' | 'AGRO_DOCUMENT_CENTER' | 'AGRO_INVOICE' | 'AGRO_INVOICE_MIGRATED' | 'AGRO_WAGE' | 'NO1TS' | 'NO1TS_TRAVELREPORT' | 'NO1TS_ACCOUNTING' | 'DIYPACKAGE' | 'BASIS' | 'SMART' | 'KOMPLETT' | 'VVS' | 'ELECTRO' | 'ACCOUNTING_OFFICE' | 'SMART_WAGE' | 'SMART_TIME_TRACKING' | 'SMART_PROJECT' | 'OCR' | 'API_V2' | 'ELECTRONIC_VOUCHERS' | 'UP_TO_100_VOUCHERS' | 'UP_TO_500_VOUCHERS' | 'UP_TO_1000_VOUCHERS' | 'UP_TO_2000_VOUCHERS' | 'UP_TO_3500_VOUCHERS' | 'UP_TO_5000_VOUCHERS' | 'UP_TO_10000_VOUCHERS' | 'UNLIMITED_VOUCHERS' | 'UP_TO_100_VOUCHERS_AUTOMATION' | 'UP_TO_500_VOUCHERS_AUTOMATION' | 'UP_TO_1000_VOUCHERS_AUTOMATION' | 'UP_TO_2000_VOUCHERS_AUTOMATION' | 'UP_TO_3500_VOUCHERS_AUTOMATION' | 'UP_TO_5000_VOUCHERS_AUTOMATION' | 'UP_TO_10000_VOUCHERS_AUTOMATION' | 'UNLIMITED_VOUCHERS_AUTOMATION' | 'LOGISTICS' | 'MIKRO' | 'AUTOPLUS_MINI' | 'AUTOPLUS_MEDIUM' | 'AUTOPLUS_STOR' | 'INTEGRATION_PARTNER' | 'PROJECT' | 'YEAR_END_REPORTING_ENK' | 'YEAR_END_REPORTING_AS' | 'YEAR_END_REPORTING_ANS' | 'YEAR_END_REPORTING_DA' | 'YEAR_END_REPORTING_STI' | 'YEAR_END_REPORTING_ORG' | 'YEAR_END_REPORTING_SA' | 'YEAR_END_REPORTING_FLI' | 'YEAR_END_REPORTING_NUF' | 'PRIMARY_INDUSTRY';
    export const NameEnum = {
        Mamut: 'MAMUT' as NameEnum,
        MamutWithWage: 'MAMUT_WITH_WAGE' as NameEnum,
        AgroLicence: 'AGRO_LICENCE' as NameEnum,
        AgroClient: 'AGRO_CLIENT' as NameEnum,
        AgroDocumentCenter: 'AGRO_DOCUMENT_CENTER' as NameEnum,
        AgroInvoice: 'AGRO_INVOICE' as NameEnum,
        AgroInvoiceMigrated: 'AGRO_INVOICE_MIGRATED' as NameEnum,
        AgroWage: 'AGRO_WAGE' as NameEnum,
        No1Ts: 'NO1TS' as NameEnum,
        No1TsTravelreport: 'NO1TS_TRAVELREPORT' as NameEnum,
        No1TsAccounting: 'NO1TS_ACCOUNTING' as NameEnum,
        Diypackage: 'DIYPACKAGE' as NameEnum,
        Basis: 'BASIS' as NameEnum,
        Smart: 'SMART' as NameEnum,
        Komplett: 'KOMPLETT' as NameEnum,
        Vvs: 'VVS' as NameEnum,
        Electro: 'ELECTRO' as NameEnum,
        AccountingOffice: 'ACCOUNTING_OFFICE' as NameEnum,
        SmartWage: 'SMART_WAGE' as NameEnum,
        SmartTimeTracking: 'SMART_TIME_TRACKING' as NameEnum,
        SmartProject: 'SMART_PROJECT' as NameEnum,
        Ocr: 'OCR' as NameEnum,
        ApiV2: 'API_V2' as NameEnum,
        ElectronicVouchers: 'ELECTRONIC_VOUCHERS' as NameEnum,
        UpTo100Vouchers: 'UP_TO_100_VOUCHERS' as NameEnum,
        UpTo500Vouchers: 'UP_TO_500_VOUCHERS' as NameEnum,
        UpTo1000Vouchers: 'UP_TO_1000_VOUCHERS' as NameEnum,
        UpTo2000Vouchers: 'UP_TO_2000_VOUCHERS' as NameEnum,
        UpTo3500Vouchers: 'UP_TO_3500_VOUCHERS' as NameEnum,
        UpTo5000Vouchers: 'UP_TO_5000_VOUCHERS' as NameEnum,
        UpTo10000Vouchers: 'UP_TO_10000_VOUCHERS' as NameEnum,
        UnlimitedVouchers: 'UNLIMITED_VOUCHERS' as NameEnum,
        UpTo100VouchersAutomation: 'UP_TO_100_VOUCHERS_AUTOMATION' as NameEnum,
        UpTo500VouchersAutomation: 'UP_TO_500_VOUCHERS_AUTOMATION' as NameEnum,
        UpTo1000VouchersAutomation: 'UP_TO_1000_VOUCHERS_AUTOMATION' as NameEnum,
        UpTo2000VouchersAutomation: 'UP_TO_2000_VOUCHERS_AUTOMATION' as NameEnum,
        UpTo3500VouchersAutomation: 'UP_TO_3500_VOUCHERS_AUTOMATION' as NameEnum,
        UpTo5000VouchersAutomation: 'UP_TO_5000_VOUCHERS_AUTOMATION' as NameEnum,
        UpTo10000VouchersAutomation: 'UP_TO_10000_VOUCHERS_AUTOMATION' as NameEnum,
        UnlimitedVouchersAutomation: 'UNLIMITED_VOUCHERS_AUTOMATION' as NameEnum,
        Logistics: 'LOGISTICS' as NameEnum,
        Mikro: 'MIKRO' as NameEnum,
        AutoplusMini: 'AUTOPLUS_MINI' as NameEnum,
        AutoplusMedium: 'AUTOPLUS_MEDIUM' as NameEnum,
        AutoplusStor: 'AUTOPLUS_STOR' as NameEnum,
        IntegrationPartner: 'INTEGRATION_PARTNER' as NameEnum,
        Project: 'PROJECT' as NameEnum,
        YearEndReportingEnk: 'YEAR_END_REPORTING_ENK' as NameEnum,
        YearEndReportingAs: 'YEAR_END_REPORTING_AS' as NameEnum,
        YearEndReportingAns: 'YEAR_END_REPORTING_ANS' as NameEnum,
        YearEndReportingDa: 'YEAR_END_REPORTING_DA' as NameEnum,
        YearEndReportingSti: 'YEAR_END_REPORTING_STI' as NameEnum,
        YearEndReportingOrg: 'YEAR_END_REPORTING_ORG' as NameEnum,
        YearEndReportingSa: 'YEAR_END_REPORTING_SA' as NameEnum,
        YearEndReportingFli: 'YEAR_END_REPORTING_FLI' as NameEnum,
        YearEndReportingNuf: 'YEAR_END_REPORTING_NUF' as NameEnum,
        PrimaryIndustry: 'PRIMARY_INDUSTRY' as NameEnum
    };
}


