/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchCompletion { 
    readonly id?: string;
    readonly name?: string;
    readonly alternateName?: string;
    readonly address?: string;
    readonly postalCode?: string;
    readonly postalArea?: string;
    readonly latitude?: number;
    readonly longitude?: number;
    readonly category?: string;
    readonly score?: number;
    readonly sources?: Array<SearchCompletion.SourcesEnum>;
}
export namespace SearchCompletion {
    export type SourcesEnum = 'SEARCH1881' | 'TRIPLETEX' | 'NICKNAME' | 'EMPLOYEE' | 'CONTACT' | 'ACTIVITY' | 'PROJECT' | 'ORDER' | 'OFFER' | 'CUSTOMER' | 'COMPANY' | 'CONTROLSCHEMA' | 'HOUR' | 'TRAVELEXPENSE';
    export const SourcesEnum = {
        Search1881: 'SEARCH1881' as SourcesEnum,
        Tripletex: 'TRIPLETEX' as SourcesEnum,
        Nickname: 'NICKNAME' as SourcesEnum,
        Employee: 'EMPLOYEE' as SourcesEnum,
        Contact: 'CONTACT' as SourcesEnum,
        Activity: 'ACTIVITY' as SourcesEnum,
        Project: 'PROJECT' as SourcesEnum,
        Order: 'ORDER' as SourcesEnum,
        Offer: 'OFFER' as SourcesEnum,
        Customer: 'CUSTOMER' as SourcesEnum,
        Company: 'COMPANY' as SourcesEnum,
        Controlschema: 'CONTROLSCHEMA' as SourcesEnum,
        Hour: 'HOUR' as SourcesEnum,
        Travelexpense: 'TRAVELEXPENSE' as SourcesEnum
    };
}


