/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SegmentationRoles { 
    readonly roleAdministrator?: boolean;
    readonly roleAccountAdministrator?: boolean;
    readonly roleSystemAdministrator?: boolean;
    readonly isAuthInvoicing?: boolean;
    readonly isAuthCompanyAdmin?: boolean;
    readonly isAuthReadOnly?: boolean;
    readonly isAuthCreateOrder?: boolean;
    readonly isAuthAccountingSettings?: boolean;
    readonly isAuthCompanyWageAdmin?: boolean;
    readonly isAuthTravelsAndExpensesAdminSettings?: boolean;
    readonly isAuthInvoiceAdminSettings?: boolean;
    readonly isAuthInboxVoucher?: boolean;
    readonly isAutWageAdminSetting?: boolean;
    readonly isAuthWageSettings?: boolean;
    readonly isAuthBankReconciliation?: boolean;
    readonly isAuthAllVouchers?: boolean;
    readonly isAuthDirectRemitZtl?: boolean;
}

