/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SegmentationModules { 
    readonly moduleaccountinginternal?: boolean;
    readonly moduleaccountingexternal?: boolean;
    readonly moduledepartment?: boolean;
    readonly projectForecast?: boolean;
    readonly resourcePlanning?: boolean;
    readonly moduleprojecteconomy?: boolean;
    readonly moduleinvoice?: boolean;
    readonly modulebudget?: boolean;
    readonly referenceFee?: boolean;
    readonly moduleHourCost?: boolean;
    readonly moduleemployee?: boolean;
    readonly moduleproject?: boolean;
    readonly projectCategories?: boolean;
    readonly moduleProjectBudget?: boolean;
    readonly moduletask?: boolean;
    readonly moduleTravelExpense?: boolean;
    readonly modulecustomer?: boolean;
    readonly modulenote?: boolean;
    readonly modulesubscription?: boolean;
    readonly moduleproduct?: boolean;
    readonly moduleVoucherExport?: boolean;
    readonly moduleaccountingreports?: boolean;
    readonly moduleCustomerCategories?: boolean;
    readonly moduleCustomerCategory1?: boolean;
    readonly moduleCustomerCategory2?: boolean;
    readonly moduleCustomerCategory3?: boolean;
    readonly budgetOnSubcontracts?: boolean;
    readonly approveHourLists?: boolean;
    readonly approveInvoices?: boolean;
    readonly approvetravelreports?: boolean;
    readonly completeweeklyhourlists?: boolean;
    readonly completemonthlyhourlists?: boolean;
    readonly approvemonthlyhourlists?: boolean;
    readonly mustApproveRegisteredHours?: boolean;
    readonly modulePayrollAccounting?: boolean;
    readonly modulePayrollAccountingNO?: boolean;
    readonly modulehourlist?: boolean;
    readonly moduleTimeBalance?: boolean;
    readonly moduleVacationBalance?: boolean;
    readonly moduleWorkingHours?: boolean;
    readonly moduleCurrency?: boolean;
    readonly moduleContact?: boolean;
    readonly autoGenerateProjectNumber?: boolean;
    readonly moduleWageExport?: boolean;
    readonly approveWeeklyHourlists?: boolean;
    readonly moduleProvisionSalary?: boolean;
    readonly moduleOrderNumber?: boolean;
    readonly moduleOrderDiscount?: boolean;
    readonly moduleOrderMarkup?: boolean;
    readonly moduleOrderLineCost?: boolean;
    readonly resourceGroups?: boolean;
    readonly moduleVendor?: boolean;
    readonly moduleAutoCustomerNumber?: boolean;
    readonly moduleAutoVendorNumber?: boolean;
    readonly historicalInformation?: boolean;
    readonly showTravelReportLetterhead?: boolean;
    readonly moduleOcr?: boolean;
    readonly moduleRemit?: boolean;
    readonly moduleRemitNets?: boolean;
    readonly moduleRemitZtl?: boolean;
    readonly moduleRemitAutoPay?: boolean;
    readonly moduleTravelExpenseRates?: boolean;
    readonly moduleVoucherScanning?: boolean;
    readonly moduleInvoiceScanning?: boolean;
    readonly holidayPlan?: boolean;
    readonly moduleEmployeeCategory?: boolean;
    readonly multipleCustomerCategories?: boolean;
    readonly moduleProductInvoice?: boolean;
    readonly autoInvoicing?: boolean;
    readonly moduleFactoring?: boolean;
    readonly moduleEmployeeAccounting?: boolean;
    readonly moduleDepartmentAccounting?: boolean;
    readonly moduleProjectAccounting?: boolean;
    readonly moduleWageProjectAccounting?: boolean;
    readonly moduleProductAccounting?: boolean;
    readonly moduleElectro?: boolean;
    readonly moduleNrf?: boolean;
    readonly moduleResultBudget?: boolean;
    readonly moduleVoucherTypes?: boolean;
    readonly moduleWarehouse?: boolean;
    readonly moduleNetsEboks?: boolean;
    readonly moduleNetsPrintSalary?: boolean;
    readonly moduleNetsPrintInvoice?: boolean;
    readonly hourlyRateProjectsWriteUpDown?: boolean;
    readonly showRecentlyClosedProjectsOnSupplierInvoice?: boolean;
    readonly moduleEmail?: boolean;
    readonly sendPayslipsByEmail?: boolean;
    readonly moduleApproveVoucher?: boolean;
    readonly moduleApproveProjectVoucher?: boolean;
    readonly moduleApproveDepartmentVoucher?: boolean;
    readonly moduleArchive?: boolean;
    readonly moduleOrderOut?: boolean;
    readonly moduleMesan?: boolean;
    readonly moduleAccountantConnectClient?: boolean;
    readonly moduleDivisions?: boolean;
    readonly moduleBoligmappa?: boolean;
    readonly markReadyForInvoicing?: boolean;
    readonly tripletexSupportLoginAccessCompanyLevel?: boolean;
    readonly moduleCRM?: boolean;
    readonly modulePensionreport?: boolean;
    readonly moduleControlSchemaRequiredInvoicing?: boolean;
    readonly moduleControlSchemaRequiredHourTracking?: boolean;
    readonly moduleInvoiceOptionVipps?: boolean;
    readonly moduleInvoiceOptionEfaktura?: boolean;
    readonly moduleInvoiceOptionPaper?: boolean;
    readonly moduleInvoiceOptionAvtaleGiro?: boolean;
    readonly moduleInvoiceOptionEhfIncoming?: boolean;
    readonly moduleInvoiceOptionEhfOutbound?: boolean;
    readonly moduleAPI20?: boolean;
    readonly moduleAgro?: boolean;
    readonly moduleMamut?: boolean;
    readonly moduleFactoringAprila?: boolean;
    readonly moduleCashCreditAprila?: boolean;
    readonly moduleInvoiceOptionAutoinvoiceEhf?: boolean;
    readonly moduleSmartScan?: boolean;
    readonly moduleAutoBankReconciliation?: boolean;
    readonly moduleOffer?: boolean;
    readonly moduleVoucherAutomation?: boolean;
    readonly moduleAmortization?: boolean;
    readonly moduleEncryptedPaySlip?: boolean;
    readonly hourCostPercentage?: boolean;
    readonly yearEndReport?: boolean;
    readonly moduleLogistics?: boolean;
    readonly moduleIndustry?: boolean;
}

