/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendToDocumentArchive { 
    /**
     * List of messageIds to move to archive
     */
    messageIds?: Array<object>;
    /**
     * Target path in archive
     */
    pathId?: number;
    /**
     * Override filename
     */
    fileName?: string;
    /**
     * Add to specific archive
     */
    modelType?: SendToDocumentArchive.ModelTypeEnum;
    modelId?: number;
    /**
     * Add to document to invoice
     */
    invoiceArchiveRelation?: SendToDocumentArchive.InvoiceArchiveRelationEnum;
}
export namespace SendToDocumentArchive {
    export type ModelTypeEnum = 'NONE' | 'CUSTOMER' | 'SUPPLIER' | 'PROJECT' | 'ORDER' | 'OFFER' | 'PROJECT_OFFER' | 'PRODUCT' | 'EMPLOYEE' | 'ACCOUNT' | 'ASSET';
    export const ModelTypeEnum = {
        None: 'NONE' as ModelTypeEnum,
        Customer: 'CUSTOMER' as ModelTypeEnum,
        Supplier: 'SUPPLIER' as ModelTypeEnum,
        Project: 'PROJECT' as ModelTypeEnum,
        Order: 'ORDER' as ModelTypeEnum,
        Offer: 'OFFER' as ModelTypeEnum,
        ProjectOffer: 'PROJECT_OFFER' as ModelTypeEnum,
        Product: 'PRODUCT' as ModelTypeEnum,
        Employee: 'EMPLOYEE' as ModelTypeEnum,
        Account: 'ACCOUNT' as ModelTypeEnum,
        Asset: 'ASSET' as ModelTypeEnum
    };
    export type InvoiceArchiveRelationEnum = 'ADD_TO_INVOICE_NONE' | 'ADD_TO_INVOICE_NEXT' | 'ADD_TO_INVOICE_ALL';
    export const InvoiceArchiveRelationEnum = {
        AddToInvoiceNone: 'ADD_TO_INVOICE_NONE' as InvoiceArchiveRelationEnum,
        AddToInvoiceNext: 'ADD_TO_INVOICE_NEXT' as InvoiceArchiveRelationEnum,
        AddToInvoiceAll: 'ADD_TO_INVOICE_ALL' as InvoiceArchiveRelationEnum
    };
}


