/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendFormEmail { 
    /**
     * The IDs of the forms to send.
     */
    ids: Array<number>;
    /**
     * If true, the attachments will be merged into one PDF file before sending the email.
     */
    mergeAttachments?: boolean;
    /**
     * The email address to send the form to. This can be one or more emails separated by a comma.
     */
    emailAddress: string;
    /**
     * The message to include in the email.
     */
    message: string;
}

