/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeToken } from './employeeToken';
import { Change } from './change';
import { ConsumerToken } from './consumerToken';


export interface SessionToken { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    consumerToken?: ConsumerToken;
    employeeToken?: EmployeeToken;
    expirationDate: string;
    token: string;
    readonly encryptionKey?: string;
}

