/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Shareholder } from './shareholder';


export interface ShareholderOverviewDTO { 
    readonly shareholders?: Array<Shareholder>;
    readonly sumNumberOfSharesThisYear?: number;
    readonly sumNumberOfSharesLastYear?: number;
    readonly sumOwnershipThisYear?: number;
    readonly sumOwnershipLastYear?: number;
}

