/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { Transaction } from './transaction';
import { CompanyEvent } from './companyEvent';
import { ShareholderRegisterData } from './shareholderRegisterData';


export interface ShareholderRegisterDataOverview { 
    yearEndReport?: YearEndReport;
    readonly groupId?: number;
    readonly shareholderRegisterDataType?: ShareholderRegisterDataOverview.ShareholderRegisterDataTypeEnum;
    readonly shareholderRegisterDataTypeGroupId?: number;
    posts?: Array<ShareholderRegisterData>;
    events?: Array<CompanyEvent>;
    transactions?: Array<Transaction>;
    readonly objectIdentifier?: string;
}
export namespace ShareholderRegisterDataOverview {
    export type ShareholderRegisterDataTypeEnum = 'COMPANY_INFO' | 'CONTACT_INFO' | 'SHAREHOLDER_INFO' | 'EVENT_AND_TRANSACTION';
    export const ShareholderRegisterDataTypeEnum = {
        CompanyInfo: 'COMPANY_INFO' as ShareholderRegisterDataTypeEnum,
        ContactInfo: 'CONTACT_INFO' as ShareholderRegisterDataTypeEnum,
        ShareholderInfo: 'SHAREHOLDER_INFO' as ShareholderRegisterDataTypeEnum,
        EventAndTransaction: 'EVENT_AND_TRANSACTION' as ShareholderRegisterDataTypeEnum
    };
}


