/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { Shareholder } from './shareholder';
import { ShareholderRegisterData } from './shareholderRegisterData';


export interface ShareholderInfo { 
    yearEndReport?: YearEndReport;
    /**
     * Id of shareholder register data to update
     */
    readonly id?: number;
    shareholder?: Shareholder;
    readonly groupId?: number;
    numberOfSharesLastYear?: ShareholderRegisterData;
    readonly numberOfSharesThisYear?: number;
    readonly ownershipLastYear?: number;
    readonly ownershipThisYear?: number;
}

