/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SnowplowGlobalEmployee { 
    readonly userId?: number;
    readonly employeeId?: number;
    readonly tripletexEmployeeId?: number;
    readonly isAccountant?: boolean;
    readonly roleIds?: Array<number>;
}

