/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SnowplowGlobalEmployee } from './snowplowGlobalEmployee';


export interface SnowplowContextSnowplowGlobalEmployee { 
    readonly schema?: string;
    data?: SnowplowGlobalEmployee;
}

