/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SseInitializationResult { 
    /**
     * The contextId of the employee
     */
    readonly contextId?: number;
    /**
     * The companyId of the employee
     */
    readonly employeeId?: number;
    /**
     * The current hidden cursor
     */
    readonly currentHiddenCursor?: number;
    /**
     * The current read cursor
     */
    readonly currentReadCursor?: number;
}

