/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';


export interface StatusLog { 
    readonly actionType?: StatusLog.ActionTypeEnum;
    readonly actionDate?: string;
    actionCreator?: Employee;
    /**
     * Rejection message if payment was rejected by the bank.
     */
    readonly rejectionMessage?: string;
}
export namespace StatusLog {
    export type ActionTypeEnum = 'PAYMENT_CREATED' | 'PAYMENT_APPROVED' | 'PAYMENT_APPROVAL_ABORTED' | 'PAYMENT_SENT_TO_BANK' | 'PAYMENT_RECEIVED_BY_BANK' | 'PAYMENT_ACCEPTED_BY_BANK' | 'PAYMENT_CANCELLED_IN_BANK' | 'PAYMENT_AMOUNT_CHANGED' | 'PAYMENT_DUE_DATE_CHANGED' | 'PAYMENT_REJECTED' | 'PAYMENT_NOT_UPDATED' | 'PAYMENT_APPROVAL_MULTIPLE_APPROVERS' | 'PAYMENT_ATTESTED' | 'PAYMENT_ATTESTATION_REJECTED' | 'PAYMENT_IMPORTED_AND_NOT_SENT' | 'PAYMENT_PAID' | 'PAYMENT_BOOKED';
    export const ActionTypeEnum = {
        PaymentCreated: 'PAYMENT_CREATED' as ActionTypeEnum,
        PaymentApproved: 'PAYMENT_APPROVED' as ActionTypeEnum,
        PaymentApprovalAborted: 'PAYMENT_APPROVAL_ABORTED' as ActionTypeEnum,
        PaymentSentToBank: 'PAYMENT_SENT_TO_BANK' as ActionTypeEnum,
        PaymentReceivedByBank: 'PAYMENT_RECEIVED_BY_BANK' as ActionTypeEnum,
        PaymentAcceptedByBank: 'PAYMENT_ACCEPTED_BY_BANK' as ActionTypeEnum,
        PaymentCancelledInBank: 'PAYMENT_CANCELLED_IN_BANK' as ActionTypeEnum,
        PaymentAmountChanged: 'PAYMENT_AMOUNT_CHANGED' as ActionTypeEnum,
        PaymentDueDateChanged: 'PAYMENT_DUE_DATE_CHANGED' as ActionTypeEnum,
        PaymentRejected: 'PAYMENT_REJECTED' as ActionTypeEnum,
        PaymentNotUpdated: 'PAYMENT_NOT_UPDATED' as ActionTypeEnum,
        PaymentApprovalMultipleApprovers: 'PAYMENT_APPROVAL_MULTIPLE_APPROVERS' as ActionTypeEnum,
        PaymentAttested: 'PAYMENT_ATTESTED' as ActionTypeEnum,
        PaymentAttestationRejected: 'PAYMENT_ATTESTATION_REJECTED' as ActionTypeEnum,
        PaymentImportedAndNotSent: 'PAYMENT_IMPORTED_AND_NOT_SENT' as ActionTypeEnum,
        PaymentPaid: 'PAYMENT_PAID' as ActionTypeEnum,
        PaymentBooked: 'PAYMENT_BOOKED' as ActionTypeEnum
    };
}


