/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SticosLink } from './sticosLink';
import { Change } from './change';


export interface SticosConversationMessage { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    response: string;
    confidence?: number;
    flag: number;
    sessionId: string;
    /**
     * List of sticos sources
     */
    sticosLinks?: Array<SticosLink>;
}

