/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface SticosLink { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    linkId: number;
    title: string;
    header: string;
    linkUrl: string;
}

