/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface Subscription { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Event name (from /v2/event) you wish to subscribe to. Form should be: *subject.verb*.
     */
    event: string;
    /**
     * The callback URL used for subscriptions (including authentication tokens). Must be absolute and use HTTPS. Basic authentication is supported.
     */
    targetUrl: string;
    /**
     * The fields in the object delivered with the notification callback, nested as in other API calls.
     */
    fields?: string;
    /**
     * The status of the subscription.
     */
    status?: Subscription.StatusEnum;
    /**
     * Custom authentication header name
     */
    authHeaderName?: string;
    /**
     * Custom authentication header value (write only)
     */
    authHeaderValue?: string;
    /**
     * HMAC signing shared secret (write only). Optionally add this field to enable hmac signing. Calculation is header(\'x-request-signature\') = base64(HmacSHA512(header(\'idempotency-key\') + \'&\' + body))
     */
    hmacSharedSecret?: string;
}
export namespace Subscription {
    export type StatusEnum = 'ACTIVE' | 'DISABLED' | 'DISABLED_TOO_MANY_ERRORS' | 'DISABLED_RATE_LIMIT_EXCEEDED' | 'DISABLED_MISUSE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Disabled: 'DISABLED' as StatusEnum,
        DisabledTooManyErrors: 'DISABLED_TOO_MANY_ERRORS' as StatusEnum,
        DisabledRateLimitExceeded: 'DISABLED_RATE_LIMIT_EXCEEDED' as StatusEnum,
        DisabledMisuse: 'DISABLED_MISUSE' as StatusEnum
    };
}


