/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoucherApprovalListElement } from './voucherApprovalListElement';
import { OrderLine } from './orderLine';
import { Posting } from './posting';
import { Currency } from './currency';
import { Supplier } from './supplier';
import { Change } from './change';
import { Voucher } from './voucher';


export interface SupplierInvoice { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Invoice number
     */
    invoiceNumber?: string;
    invoiceDate: string;
    supplier?: Supplier;
    invoiceDueDate?: string;
    /**
     * KID or message
     */
    kidOrReceiverReference?: string;
    voucher?: Voucher;
    /**
     * In the company’s currency, typically NOK. Is 0 if value is missing.
     */
    readonly amount?: number;
    /**
     * In the specified currency.
     */
    amountCurrency?: number;
    /**
     * Amount excluding VAT (NOK). Is 0 if value is missing.
     */
    readonly amountExcludingVat?: number;
    /**
     * Amount excluding VAT in the specified currency. Is 0 if value is missing.
     */
    readonly amountExcludingVatCurrency?: number;
    currency?: Currency;
    readonly isCreditNote?: boolean;
    readonly orderLines?: Array<OrderLine>;
    readonly payments?: Array<Posting>;
    readonly originalInvoiceDocumentId?: number;
    readonly approvalListElements?: Array<VoucherApprovalListElement>;
    /**
     * The amount outstanding on the invoice, in the invoice currency.
     */
    readonly outstandingAmount?: number;
}

