/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SupportAIMatchedArticle } from './supportAIMatchedArticle';
import { Change } from './change';


export interface SupportAIConversationMessage { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    response: string;
    responseType?: string;
    /**
     * List of supportAIMatchedArticles
     */
    supportAIMatchedArticles?: Array<SupportAIMatchedArticle>;
}

