/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupplierImportRowContent { 
    supplierNumber?: string;
    supplierName?: string;
    organizationNumber?: string;
    phoneNumber?: string;
    phoneNumberMobile?: string;
    email?: string;
    postalAddress1?: string;
    postalAddress2?: string;
    postalCode?: string;
    postalAddressCity?: string;
    postalAddressCountry?: string;
    bban?: string;
    iban?: string;
    swift?: string;
    isPrivatePerson?: string;
    fax?: string;
    currencyCode?: string;
    category1Number?: string;
    category1Name?: string;
    category2Number?: string;
    category2Name?: string;
    category3Number?: string;
    category3Name?: string;
    contactFirstName?: string;
    contactLastName?: string;
    contactAddress1?: string;
    contactAddress2?: string;
    contactAddressPostalCode?: string;
    contactAddressCity?: string;
    contactAddressCountry?: string;
    contactPhoneNumberWork?: string;
    contactPhoneNumberMobile?: string;
    contactEmail?: string;
    businessAddress1?: string;
    businessAddress2?: string;
    businessAddressPostalCode?: string;
    businessAddressCity?: string;
    businessAddressCountry?: string;
    deliveryAddress1?: string;
    deliveryAddress2?: string;
    deliveryAddressPostalCode?: string;
    deliveryAddressCity?: string;
    deliveryAddressCountry?: string;
    selfEmployedWithoutBusinessAddress?: string;
    socialSecurityNumber?: string;
    empty?: boolean;
}

