/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemReport } from './systemReport';


export interface SystemReportCategory { 
    /**
     * The text key for the name of the report category
     */
    readonly textKey?: string;
    /**
     * The theme of the report category
     */
    readonly theme?: string;
    /**
     * The icon for the report category
     */
    readonly icon?: string;
    /**
     * The reports in this report category
     */
    readonly reports?: Array<SystemReport>;
    /**
     * The report categories in this report category
     */
    readonly subCategories?: Array<SystemReportCategory>;
}

