/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TangibleFixedAsset { 
    readonly name?: string;
    readonly businessActivityTitle?: string;
    readonly objectIdentifier?: string;
    readonly objectGroup?: string;
    readonly accountNumber?: string;
    readonly accountId?: number;
    readonly type?: string;
    readonly openingBalance?: number;
    readonly openingBalanceTaxValue?: number;
    readonly closingBalance?: number;
    readonly closingBalanceTaxValue?: number;
    readonly newAcquisitions?: number;
    readonly acquisitionCost?: number;
    readonly improvements?: number;
    readonly publicSubsidies?: number;
    readonly salesAndOtherRealisation?: number;
    readonly salesAndOtherRealisationRecognition?: number;
    readonly subsidiesForRegionalInvestments?: number;
    readonly reversalOfSubsidiesForRegionalInvestments?: number;
    readonly adjustmentOfInputVat?: number;
    readonly obviousChangeOfValue?: number;
    readonly unknownTransactionType?: number;
    readonly depreciation?: number;
    readonly writeupsOrWritedowns?: number;
    readonly depreciationTaxValue?: number;
    readonly calculatedDepreciation?: number;
    readonly accountedDepreciationPercentage?: number;
    readonly depreciationPercentage?: number;
    readonly depreciationPercentageTaxValue?: number;
    readonly depreciationDifference?: number;
    readonly incomeRecognitionOfNegativeBalance?: number;
    readonly straightLineDepreciation?: number;
    readonly straightLineDepreciationTaxValue?: number;
    readonly basisForDepreciationOrIncomeRecognition?: number;
    readonly basisForDepreciationOrIncomeRecognitionTaxValue?: number;
    readonly profitTransferredToProfitAndLossAccount?: number;
    readonly lossTransferredToProfitAndLossAccount?: number;
    readonly accountingValueProfitAndLoss?: number;
    readonly warningTooHighPercentage?: string;
    readonly warningTooLowPercentage?: string;
    readonly infoResidualWriteOff?: string;
    readonly infoMessageDepreciation?: string;
    readonly infoMessageIncomeRecognition?: string;
    readonly infoTransferBalance?: string;
    readonly negate?: boolean;
    /**
     * Additional tax for the project
     */
    lifetime?: number;
    acquisitionDate?: string;
    realisationDate?: string;
    /**
     * Additional tax for the project
     */
    historicalCostPrice?: number;
    /**
     * Additional tax for the project
     */
    writtenDownValuePr01011984?: number;
    /**
     * Additional tax for the project
     */
    lowerLimitDepreciation?: number;
    readonly commercialBuildingAcquiredBefore1984?: boolean;
    readonly isPhysicalOperatingAssetsInBalanceSheet?: boolean;
    /**
     * Underlying Documents Used For Assessment
     */
    facilityType?: TangibleFixedAsset.FacilityTypeEnum;
    readonly maxDepreciationPercentage?: number;
    physicalOperatingAssetsInBalanceSheet?: boolean;
}
export namespace TangibleFixedAsset {
    export type FacilityTypeEnum = 'LIFETIME_OVER_20_YEARS' | 'LIFETIME_UNDER_20_YEARS' | 'LIVESTOCK_BUILDINGS' | 'FRUIT_FIELD' | 'BERRY_FIELD';
    export const FacilityTypeEnum = {
        LifetimeOver20Years: 'LIFETIME_OVER_20_YEARS' as FacilityTypeEnum,
        LifetimeUnder20Years: 'LIFETIME_UNDER_20_YEARS' as FacilityTypeEnum,
        LivestockBuildings: 'LIVESTOCK_BUILDINGS' as FacilityTypeEnum,
        FruitField: 'FRUIT_FIELD' as FacilityTypeEnum,
        BerryField: 'BERRY_FIELD' as FacilityTypeEnum
    };
}


