/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskWidgetDTO } from './taskWidgetDTO';


export interface TaskDTO { 
    readonly tasks?: Array<TaskWidgetDTO>;
}

