/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxAdminPhysicalAddress } from './taxAdminPhysicalAddress';
import { TaxAdminProperty } from './taxAdminProperty';


export interface TaxAdminSearchResponse { 
    readonly resultSize?: number;
    readonly properties?: Array<TaxAdminProperty>;
    readonly physicalAddresses?: Array<TaxAdminPhysicalAddress>;
    readonly searchStart?: string;
    readonly searchEnd?: string;
}

