/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxAdminProperty } from './taxAdminProperty';


export interface TaxAdminPhysicalAddress { 
    readonly sergPropertyIdentifier?: number;
    readonly uniquePropertyIdentifier?: number;
    readonly addressName?: string;
    readonly houseNo?: number;
    readonly zipCode?: string;
    readonly postalPlaceName?: string;
    readonly highlight?: string;
    readonly properties?: Array<TaxAdminProperty>;
}

