/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaxAdminProperty { 
    readonly sergPropertyIdentifier?: number;
    readonly uniquePropertyIdentifier?: number;
    readonly propertyCreatedDate?: string;
    readonly municipalityNo?: string;
    readonly municipalityName?: string;
    readonly cadastralUnitNo?: number;
    readonly propertyUnitNo?: number;
    readonly leaseholdNo?: number;
    readonly sectionNo?: number;
    readonly historical?: boolean;
    readonly highlight?: string;
}

