/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaxCalculation { 
    readonly objectIdentifier?: number;
    readonly taxableProfit?: number;
    readonly accumulatedLoss?: number;
    readonly taxRateThisYear?: number;
    readonly taxRateNextYear?: number;
    readonly taxCalculated?: number;
    readonly taxPosted?: number;
    readonly taxDiff?: number;
    readonly tooLittleTaxSetAside?: number;
    readonly tooMuchTaxSetAside?: number;
    readonly totalTaxSetAside?: number;
    readonly basisDefferedTax?: number;
    readonly basisDefferedTaxAssets?: number;
    readonly deferredTaxOpeningBalance?: number;
    readonly deferredTaxAssetsOpeningBalance?: number;
    readonly deferredTaxClosingBalance?: number;
    readonly deferredTaxAssetsClosingBalance?: number;
    readonly calculatedDeferredTax?: number;
    readonly calculatedDeferredTaxAssets?: number;
    readonly increasedDeferredTax?: number;
    readonly decreasedDeferredTax?: number;
    readonly increasedDeferredTaxAssets?: number;
    readonly decreasedDeferredTaxAssets?: number;
    readonly deferredTaxToBePosted?: number;
    readonly deferredTaxAssetsToBePosted?: number;
    readonly totalTaxToSetAsside?: number;
    readonly totalAdditions?: number;
    readonly totalDeductions?: number;
    readonly totalBasis?: number;
    readonly deferredTaxAssetsInBalance?: number;
    readonly totalWealthDistribution?: number;
    readonly taxCalculatedOnWealth?: number;
    readonly totalTaxCalculated?: number;
}

