/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaxReturnValidationGuidance { 
    readonly guidanceType?: string;
    readonly occurrenceIdentifier?: string;
    readonly helpText?: string;
    readonly strategyOfService?: string;
    readonly path?: string;
}

