/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { TimberAccount } from './timberAccount';


export interface TimberAccountOverview { 
    yearEndReport?: YearEndReport;
    timberAccounts?: Array<TimberAccount>;
    readonly transferredFromTimberAccountAccounting?: number;
    readonly transferredFromTimberAccountInTimberAccount?: number;
    readonly registeredAccounting?: number;
    readonly registeredInTimberAccount?: number;
    readonly deductedAccounting?: number;
    readonly deductedInTimberAccount?: number;
}

