/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Employee } from './employee';
import { Activity } from './activity';
import { Change } from './change';
import { TimesheetEntry } from './timesheetEntry';


export interface TimeClock { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    employee: Employee;
    project?: Project;
    activity?: Activity;
    timesheetEntry: TimesheetEntry;
    date: string;
    timeStart: string;
    timeStop: string;
    hoursStart?: number;
    lunchBreakDuration?: number;
}

