/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Employee } from './employee';
import { SalaryType } from './salaryType';
import { Change } from './change';
import { Payslip } from './payslip';


export interface TimesheetProjectSalaryTypeSpecification { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    employee: Employee;
    project?: Project;
    salaryType: SalaryType;
    description?: string;
    date: string;
    count: number;
    wagePayment?: Payslip;
}

