/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Activity } from './activity';
import { Change } from './change';


export interface TimesheetSettings { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    timeClock?: boolean;
    timesheetCompleted?: boolean;
    flexBalance?: boolean;
    vacationBalance?: boolean;
    defaultProjectActivity?: Activity;
}

