/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoListItemStatus } from './todoListItemStatus';


export interface TodoListExpandedDetail { 
    category?: TodoListExpandedDetail.CategoryEnum;
    description?: string;
    status?: TodoListItemStatus;
    url?: string;
}
export namespace TodoListExpandedDetail {
    export type CategoryEnum = 'RECONCILIATION_BANK' | 'RECONCILIATION_LEDGER' | 'RECONCILIATION_CUSTOMER' | 'RECONCILIATION_VENDOR' | 'RECONCILIATION_WAGE' | 'AMELDING_EMPLOYMENT' | 'AMELDING_WAGE_TRANSACTION' | 'WAGE_TRANSACTION_PAID_MANDATORY_DEDUCTION' | 'WAGE_TRANSACTION_PAID_TAX_DEDUCTION' | 'WAGE_TRANSACTION_PAID_PAYROLL_TAX';
    export const CategoryEnum = {
        ReconciliationBank: 'RECONCILIATION_BANK' as CategoryEnum,
        ReconciliationLedger: 'RECONCILIATION_LEDGER' as CategoryEnum,
        ReconciliationCustomer: 'RECONCILIATION_CUSTOMER' as CategoryEnum,
        ReconciliationVendor: 'RECONCILIATION_VENDOR' as CategoryEnum,
        ReconciliationWage: 'RECONCILIATION_WAGE' as CategoryEnum,
        AmeldingEmployment: 'AMELDING_EMPLOYMENT' as CategoryEnum,
        AmeldingWageTransaction: 'AMELDING_WAGE_TRANSACTION' as CategoryEnum,
        WageTransactionPaidMandatoryDeduction: 'WAGE_TRANSACTION_PAID_MANDATORY_DEDUCTION' as CategoryEnum,
        WageTransactionPaidTaxDeduction: 'WAGE_TRANSACTION_PAID_TAX_DEDUCTION' as CategoryEnum,
        WageTransactionPaidPayrollTax: 'WAGE_TRANSACTION_PAID_PAYROLL_TAX' as CategoryEnum
    };
}


