/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoListItemStatus } from './todoListItemStatus';


export interface TodoListAnnualAccounts { 
    readonly itemIdentifier?: number;
    readonly customerId?: number;
    readonly clientName?: string;
    readonly clientCompanyId?: number;
    readonly accountManagerName?: string;
    readonly accountManagerId?: number;
    readonly customAccountManagerName?: string;
    readonly customAccountManagerId?: number;
    status?: TodoListItemStatus;
    customStatus?: TodoListItemStatus;
    readonly dueDate?: string;
    readonly customDueDate?: string;
    readonly periodStart?: string;
    readonly period?: string;
    readonly year?: number;
    readonly url?: string;
}

