/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferPostingsAdjustmentRequestDTO { 
    /**
     * The id of the reconciliation where adjustment will be created
     */
    reconciliationId?: number;
    /**
     * Posting Ids
     */
    postingIds: Array<number>;
    /**
     * New Date for postings
     */
    date: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Interim Account Id
     */
    interimAccountId: number;
}

