/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Change } from './change';


export interface TravelPaymentType { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    description: string;
    account?: Account;
    readonly showOnTravelExpenses?: boolean;
    readonly showOnEmployeeExpenses?: boolean;
    readonly isInactive?: boolean;
}

