/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrialInfoAutomation { 
    readonly totalCouldBeAutomated190days?: number;
    readonly totalCouldBeAutomated365days?: number;
    readonly percentSuggestionsEHF?: number;
    readonly percentAutomatedEHF?: number;
    readonly totalEHFinvoices?: number;
    readonly totalCorrectSuggestions?: number;
    readonly correctSuggestions190days?: number;
    readonly correctSuggestions365days?: number;
    readonly totalAutomated190days?: number;
    readonly totalAutomated365days?: number;
    readonly countDeactivatedVendors?: number;
    readonly countActivatedVendors?: number;
    readonly getvendorsCouldBeAutomated?: number;
    readonly vendorsNotSendingEhf?: number;
    readonly voucherCountNonEhf?: number;
    readonly percentVendorsNotSendingEhf?: number;
    readonly percentInvoicesNonEhf?: number;
    readonly showProjectHint?: boolean;
}

