/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Trigger { 
    readonly calendarName?: string;
    readonly description?: string;
    readonly name?: string;
    readonly nextFireTime?: string;
    readonly previousFireTime?: string;
    readonly state?: string;
}

