/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TripletexCompanyBuilder { 
    companyId?: number;
    type?: number;
    customerId?: number;
    customerCompanyId?: number;
    invoiceNumberOfMonths?: number;
    invoiceNumberOfMonthsInAdvance?: number;
    priceList?: TripletexCompanyBuilder.PriceListEnum;
}
export namespace TripletexCompanyBuilder {
    export type PriceListEnum = 'TRIPLETEX_OLD_MODEL' | 'TRIPLETEX_STANDARD' | 'AGRO' | 'MAMUT' | 'BASIS' | 'SMART' | 'KOMPLETT' | 'VVS_ELEKTRO' | 'AUTOPLUS' | 'MIKRO' | 'INTEGRATION_PARTNER' | 'PLUSS' | 'DIYPACKAGE';
    export const PriceListEnum = {
        TripletexOldModel: 'TRIPLETEX_OLD_MODEL' as PriceListEnum,
        TripletexStandard: 'TRIPLETEX_STANDARD' as PriceListEnum,
        Agro: 'AGRO' as PriceListEnum,
        Mamut: 'MAMUT' as PriceListEnum,
        Basis: 'BASIS' as PriceListEnum,
        Smart: 'SMART' as PriceListEnum,
        Komplett: 'KOMPLETT' as PriceListEnum,
        VvsElektro: 'VVS_ELEKTRO' as PriceListEnum,
        Autoplus: 'AUTOPLUS' as PriceListEnum,
        Mikro: 'MIKRO' as PriceListEnum,
        IntegrationPartner: 'INTEGRATION_PARTNER' as PriceListEnum,
        Pluss: 'PLUSS' as PriceListEnum,
        Diypackage: 'DIYPACKAGE' as PriceListEnum
    };
}


