/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlobalReminder } from './globalReminder';
import { CompanyReminder } from './companyReminder';


export interface TripletexDashboardReminder { 
    globalReminder?: GlobalReminder;
    companyReminder?: CompanyReminder;
    reminderBorderColor?: TripletexDashboardReminder.ReminderBorderColorEnum;
}
export namespace TripletexDashboardReminder {
    export type ReminderBorderColorEnum = 'NONE' | 'RED' | 'GREEN' | 'YELLOW';
    export const ReminderBorderColorEnum = {
        None: 'NONE' as ReminderBorderColorEnum,
        Red: 'RED' as ReminderBorderColorEnum,
        Green: 'GREEN' as ReminderBorderColorEnum,
        Yellow: 'YELLOW' as ReminderBorderColorEnum
    };
}


