/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lookup1881TollStationV2 } from './lookup1881TollStationV2';
import { Lookup1881TotalToll } from './lookup1881TotalToll';


export interface TripSearchResponse { 
    readonly distance?: number;
    readonly travelTimeInMinutes?: number;
    totalToll?: Lookup1881TotalToll;
    readonly tollStations?: Array<Lookup1881TollStationV2>;
}

