/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TskInternalContextDTO { 
    readonly companyName?: string;
    readonly hasDepartment?: boolean;
    readonly hasEmployeeCategory?: boolean;
    readonly hasDivision?: boolean;
    readonly maxEmployeesPerSalaryTransaction?: number;
    readonly isPilotSalaryRun?: boolean;
    readonly contextCompanyId?: number;
    readonly loginEmployeeId?: number;
    readonly actualEmployeeId?: number;
    readonly isProxyLogin?: boolean;
    readonly isShowSalaryOnboarding?: boolean;
    readonly isPayInAdvance?: boolean;
    readonly isTestAccount?: boolean;
    readonly isAuthReadonly?: boolean;
    readonly isAuthCompanyWageAdmin?: boolean;
    readonly isAuthDepartmentWageAdmin?: boolean;
    readonly isAuthCompanyEmployeeAdmin?: boolean;
    readonly isAuthDepartmentEmployeeAdmin?: boolean;
    readonly isAuthEmployeeInfo?: boolean;
    readonly authLevelWage?: number;
    readonly authLevelEmployeeOrWage?: number;
    readonly userDepartmentId?: number;
    newCustomerFrom2025?: boolean;
}

