/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VacationSummary { 
    readonly incomingVacationBalance?: number;
    readonly outgoingVacationBalance?: number;
    readonly vacationTakenInPeriod?: number;
    readonly vacationTakenThisYear?: number;
}

