/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationReason } from './validationReason';


export interface ValidationError { 
    /**
     * The vatCode connected to this error
     */
    readonly vatCode?: string;
    /**
     * The vatSpecificationLine id the error is connected to
     */
    readonly vatSpecificationLineId?: number;
    /**
     * The list of reasons of this error
     */
    readonly reasons?: Array<ValidationReason>;
}

