/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';


export interface VatDeliveryStatus { 
    /**
     * The delivery status of the VAT
     */
    readonly status?: VatDeliveryStatus.StatusEnum;
    employee?: Employee;
    /**
     * Date and time the delivery status was updated
     */
    readonly time?: string;
}
export namespace VatDeliveryStatus {
    export type StatusEnum = 'NOT_STARTED' | 'NOT_SENT' | 'SENDING' | 'WAITING_FOR_REPLY' | 'RECEIPT_RECEIVED' | 'MANUAL_DELIVERY' | 'DELIVERY_FORBIDDEN' | 'FAILED';
    export const StatusEnum = {
        NotStarted: 'NOT_STARTED' as StatusEnum,
        NotSent: 'NOT_SENT' as StatusEnum,
        Sending: 'SENDING' as StatusEnum,
        WaitingForReply: 'WAITING_FOR_REPLY' as StatusEnum,
        ReceiptReceived: 'RECEIPT_RECEIVED' as StatusEnum,
        ManualDelivery: 'MANUAL_DELIVERY' as StatusEnum,
        DeliveryForbidden: 'DELIVERY_FORBIDDEN' as StatusEnum,
        Failed: 'FAILED' as StatusEnum
    };
}


