/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employee } from './employee';


export interface VatPaymentStatus { 
    /**
     * The payment status of the VAT
     */
    readonly status?: VatPaymentStatus.StatusEnum;
    /**
     * Total amount in NOK
     */
    readonly totalAmount?: number;
    /**
     * Remaining amount in NOK
     */
    readonly remainingAmount?: number;
    employee?: Employee;
    /**
     * Date and time the delivery status was updated
     */
    readonly time?: string;
}
export namespace VatPaymentStatus {
    export type StatusEnum = 'NOT_STARTED' | 'NOT_PAID' | 'NO_TAX_TO_PAY' | 'AMOUNT_CREDITED' | 'PAYMENT_REGISTERED';
    export const StatusEnum = {
        NotStarted: 'NOT_STARTED' as StatusEnum,
        NotPaid: 'NOT_PAID' as StatusEnum,
        NoTaxToPay: 'NO_TAX_TO_PAY' as StatusEnum,
        AmountCredited: 'AMOUNT_CREDITED' as StatusEnum,
        PaymentRegistered: 'PAYMENT_REGISTERED' as StatusEnum
    };
}


