/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VatReturnsComment } from './vatReturnsComment';


export interface VatReturnsVatCodeComment { 
    /**
     * The vatCode
     */
    vatCode?: string;
    /**
     * List of comments for the given vatCode
     */
    readonly comments?: Array<VatReturnsComment>;
}

