/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VatSpecificationGroup } from './vatSpecificationGroup';
import { Change } from './change';
import { AltinnInstance } from './altinnInstance';
import { Voucher } from './voucher';


export interface VatReturns2022 { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    readonly start?: string;
    readonly end?: string;
    readonly year?: number;
    readonly vatTermNumber?: number;
    readonly displayName?: string;
    readonly closedDate?: string;
    /**
     * The current instance status of the vatReturns.
     */
    readonly status?: VatReturns2022.StatusEnum;
    readonly userComment?: string;
    readonly structuredComment?: string;
    readonly vatGroups?: Array<VatSpecificationGroup>;
    voucher?: Voucher;
    altinnMetadata?: AltinnInstance;
    /**
     * Attachment for vat return
     */
    readonly receiptId?: number;
    readonly totalAmountVatToPay?: number;
    readonly remainingAmountVatToPay?: number;
    readonly isPaid?: boolean;
    readonly reportType?: VatReturns2022.ReportTypeEnum;
}
export namespace VatReturns2022 {
    export type StatusEnum = 'NOT_STARTED' | 'INSTANCE_CREATED' | 'VAT_ENVELOPE_DELIVERED' | 'VAT_RETURNS_DELIVERED' | 'ATTACHMENTS_DELIVERED' | 'FILLING_COMPLETE' | 'SENDING_COMPLETE' | 'FEEDBACK_RECEIVED' | 'MANUAL_DELIVERY' | 'USER_FORBIDDEN' | 'SENDING_FAILED';
    export const StatusEnum = {
        NotStarted: 'NOT_STARTED' as StatusEnum,
        InstanceCreated: 'INSTANCE_CREATED' as StatusEnum,
        VatEnvelopeDelivered: 'VAT_ENVELOPE_DELIVERED' as StatusEnum,
        VatReturnsDelivered: 'VAT_RETURNS_DELIVERED' as StatusEnum,
        AttachmentsDelivered: 'ATTACHMENTS_DELIVERED' as StatusEnum,
        FillingComplete: 'FILLING_COMPLETE' as StatusEnum,
        SendingComplete: 'SENDING_COMPLETE' as StatusEnum,
        FeedbackReceived: 'FEEDBACK_RECEIVED' as StatusEnum,
        ManualDelivery: 'MANUAL_DELIVERY' as StatusEnum,
        UserForbidden: 'USER_FORBIDDEN' as StatusEnum,
        SendingFailed: 'SENDING_FAILED' as StatusEnum
    };
    export type ReportTypeEnum = 'PRIMARY_INDUSTRY' | 'GENERAL_INDUSTRY';
    export const ReportTypeEnum = {
        PrimaryIndustry: 'PRIMARY_INDUSTRY' as ReportTypeEnum,
        GeneralIndustry: 'GENERAL_INDUSTRY' as ReportTypeEnum
    };
}


