/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VatReturnsComment { 
    /**
     * Title of the comment
     */
    readonly title?: string;
    /**
     * Technical name of the comment
     */
    readonly technicalName?: string;
    /**
     * Detailed description of the comment
     */
    readonly description?: string;
    /**
     * Detailed description of the comment
     */
    readonly vatSpecificationType?: VatReturnsComment.VatSpecificationTypeEnum;
    /**
     * The sign expected on the structured comment
     */
    readonly expectedSign?: VatReturnsComment.ExpectedSignEnum;
    /**
     * The sign delivered on the structured comment
     */
    readonly deliveredSign?: VatReturnsComment.DeliveredSignEnum;
}
export namespace VatReturnsComment {
    export type VatSpecificationTypeEnum = 'DEFAULT' | 'LOSS_OF_CLAIM' | 'WITHDRAWAL' | 'ADJUSTMENT' | 'REVERSAL' | 'COMPENSATION';
    export const VatSpecificationTypeEnum = {
        Default: 'DEFAULT' as VatSpecificationTypeEnum,
        LossOfClaim: 'LOSS_OF_CLAIM' as VatSpecificationTypeEnum,
        Withdrawal: 'WITHDRAWAL' as VatSpecificationTypeEnum,
        Adjustment: 'ADJUSTMENT' as VatSpecificationTypeEnum,
        Reversal: 'REVERSAL' as VatSpecificationTypeEnum,
        Compensation: 'COMPENSATION' as VatSpecificationTypeEnum
    };
    export type ExpectedSignEnum = 'ZERO' | 'POSITIVE' | 'NEGATIVE';
    export const ExpectedSignEnum = {
        Zero: 'ZERO' as ExpectedSignEnum,
        Positive: 'POSITIVE' as ExpectedSignEnum,
        Negative: 'NEGATIVE' as ExpectedSignEnum
    };
    export type DeliveredSignEnum = 'ZERO' | 'POSITIVE' | 'NEGATIVE';
    export const DeliveredSignEnum = {
        Zero: 'ZERO' as DeliveredSignEnum,
        Positive: 'POSITIVE' as DeliveredSignEnum,
        Negative: 'NEGATIVE' as DeliveredSignEnum
    };
}


