/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VatReturns2022Creation { 
    /**
     * The year of creating the vatReturns
     */
    year: number;
    /**
     * The term of the vatReturns. Must be according to the terms the company have.
     */
    term: number;
    /**
     * Vat report type
     */
    reportType?: VatReturns2022Creation.ReportTypeEnum;
}
export namespace VatReturns2022Creation {
    export type ReportTypeEnum = 'PRIMARY_INDUSTRY' | 'GENERAL_INDUSTRY';
    export const ReportTypeEnum = {
        PrimaryIndustry: 'PRIMARY_INDUSTRY' as ReportTypeEnum,
        GeneralIndustry: 'GENERAL_INDUSTRY' as ReportTypeEnum
    };
}


