/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VatReturnsOverviewItem { 
    readonly id?: number;
    readonly startDate?: string;
    readonly endDate?: string;
    readonly dueDate?: string;
    readonly status?: VatReturnsOverviewItem.StatusEnum;
    readonly voucherId?: number;
    readonly voucherNumber?: string;
    readonly amount?: number;
    readonly isPaid?: boolean;
    readonly term?: number;
    readonly termDisplayName?: string;
    readonly year?: number;
    readonly reportType?: VatReturnsOverviewItem.ReportTypeEnum;
    readonly reportTypeName?: string;
}
export namespace VatReturnsOverviewItem {
    export type StatusEnum = 'NOT_STARTED' | 'INSTANCE_CREATED' | 'VAT_ENVELOPE_DELIVERED' | 'VAT_RETURNS_DELIVERED' | 'ATTACHMENTS_DELIVERED' | 'FILLING_COMPLETE' | 'SENDING_COMPLETE' | 'FEEDBACK_RECEIVED' | 'MANUAL_DELIVERY' | 'USER_FORBIDDEN' | 'SENDING_FAILED';
    export const StatusEnum = {
        NotStarted: 'NOT_STARTED' as StatusEnum,
        InstanceCreated: 'INSTANCE_CREATED' as StatusEnum,
        VatEnvelopeDelivered: 'VAT_ENVELOPE_DELIVERED' as StatusEnum,
        VatReturnsDelivered: 'VAT_RETURNS_DELIVERED' as StatusEnum,
        AttachmentsDelivered: 'ATTACHMENTS_DELIVERED' as StatusEnum,
        FillingComplete: 'FILLING_COMPLETE' as StatusEnum,
        SendingComplete: 'SENDING_COMPLETE' as StatusEnum,
        FeedbackReceived: 'FEEDBACK_RECEIVED' as StatusEnum,
        ManualDelivery: 'MANUAL_DELIVERY' as StatusEnum,
        UserForbidden: 'USER_FORBIDDEN' as StatusEnum,
        SendingFailed: 'SENDING_FAILED' as StatusEnum
    };
    export type ReportTypeEnum = 'PRIMARY_INDUSTRY' | 'GENERAL_INDUSTRY';
    export const ReportTypeEnum = {
        PrimaryIndustry: 'PRIMARY_INDUSTRY' as ReportTypeEnum,
        GeneralIndustry: 'GENERAL_INDUSTRY' as ReportTypeEnum
    };
}


