/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VatSettingsBuilder { 
    companyId?: number;
    hasVatOutMedium?: boolean;
    hasVatOutLow?: boolean;
    hasVatOutInside?: boolean;
    hasVatOutMediumFish?: boolean;
    hasVatInMedium?: boolean;
    status?: number;
}

