/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoucherBuilder { 
    companyId?: number;
    type?: number;
    year?: number;
    description?: string;
    date?: string;
}

