/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Posting } from './posting';
import { Change } from './change';
import { Document } from './document';
import { Voucher } from './voucher';
import { VoucherType } from './voucherType';


export interface VoucherInternal { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    date: string;
    /**
     * System generated number that cannot be changed.
     */
    readonly number?: number;
    /**
     * Temporary voucher number.
     */
    readonly tempNumber?: number;
    /**
     * System generated number that cannot be changed.
     */
    readonly year?: number;
    description: string;
    voucherType?: VoucherType;
    reverseVoucher?: Voucher;
    postings: Array<Posting>;
    document?: Document;
    attachment?: Document;
    /**
     * External voucher number.
     */
    externalVoucherNumber?: string;
    ediDocument?: Document;
    /**
     * Supplier voucher type - simple and detailed.
     */
    supplierVoucherType?: VoucherInternal.SupplierVoucherTypeEnum;
    /**
     * Voucher was auto matched
     */
    readonly wasAutoMatched?: boolean;
    /**
     * Vendor invoice number.
     */
    vendorInvoiceNumber?: string;
    readonly displayName?: string;
    urlDetails?: string;
}
export namespace VoucherInternal {
    export type SupplierVoucherTypeEnum = 'TYPE_SUPPLIER_INVOICE_SIMPLE' | 'TYPE_SUPPLIER_INVOICE_DETAILED';
    export const SupplierVoucherTypeEnum = {
        TypeSupplierInvoiceSimple: 'TYPE_SUPPLIER_INVOICE_SIMPLE' as SupplierVoucherTypeEnum,
        TypeSupplierInvoiceDetailed: 'TYPE_SUPPLIER_INVOICE_DETAILED' as SupplierVoucherTypeEnum
    };
}


