/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictionLine } from './predictionLine';


export interface VoucherInboxItem { 
    readonly id?: number;
    readonly companyId?: number;
    readonly companyName?: string;
    readonly description?: string;
    readonly filterType?: VoucherInboxItem.FilterTypeEnum;
    readonly receivedDate?: string;
    readonly voucherId?: number;
    readonly invoiceId?: number;
    readonly bankAccount?: string;
    readonly kid?: string;
    readonly merchantName?: string;
    readonly orderNumberCustomer?: string;
    readonly orderNumberBuyer?: string;
    readonly projectRef?: string;
    readonly vendorRef?: string;
    readonly buyersRef?: string;
    readonly buyersContact?: string;
    readonly lastComment?: string;
    readonly invoiceNumber?: string;
    readonly invoiceDate?: string;
    readonly dueDate?: string;
    readonly isDue?: boolean;
    readonly supplierName?: string;
    readonly invoiceAmount?: number;
    readonly invoiceCurrency?: string;
    readonly documents?: Array<string>;
    readonly documentIds?: Array<number>;
    readonly account?: string;
    readonly vatNumber?: string;
    readonly vatAmount?: number;
    readonly vatPercentage?: number;
    readonly project?: string;
    readonly department?: string;
    readonly paymentTypeId?: number;
    readonly paymentType?: string;
    readonly importFailureReason?: string;
    readonly predictionLines?: Array<PredictionLine>;
    readonly filename?: string;
    readonly isTemporary?: boolean;
    readonly isInvoiceSimple?: boolean;
    readonly isInvoiceDetailed?: boolean;
    /**
     * Has one or more predictions from FabricAi
     */
    readonly hasPredictions?: boolean;
    /**
     * Has one or more suggestions from SmartScan
     */
    readonly hasSmartScanSuggestions?: boolean;
    /**
     * Is voucher locked for change by external integration
     */
    readonly isLocked?: boolean;
    readonly commentCount?: number;
    readonly nonAutomationReason?: string;
    /**
     * Possible to do one click \'Send to ledger\'
     */
    readonly canBeSentToLedger?: boolean;
    /**
     * Possible to do one click \'Send to ledger\'
     */
    readonly canBeRegisteredAsChanged?: boolean;
    readonly canBeRegisteredAsSimpleInvoice?: boolean;
    readonly canBeRegisteredAsDetailedInvoice?: boolean;
    readonly canBeRegisteredAsBankReconciliation?: boolean;
    readonly canBeRegisteredAsPaymentIn?: boolean;
    readonly canBeRegisteredAsIncome?: boolean;
    readonly canBeRegisteredAsCustomsDeclaration?: boolean;
    readonly canBeRegisteredAsAdvanced?: boolean;
    readonly canBeSentToAccountant?: boolean;
    readonly canBeSentToArchive?: boolean;
    readonly canBeDeleted?: boolean;
    readonly canBeRegisteredInQueue?: boolean;
    readonly canBeMerged?: boolean;
    readonly canBeReclaimed?: boolean;
    readonly canChangeDescription?: boolean;
    readonly preferDetailedInvoice?: boolean;
    readonly approvalHasBeenRejected?: boolean;
    readonly allowPostingBeforeVoucherApproved?: boolean;
    readonly senderEmailAddress?: string;
    readonly isSpam?: boolean;
    readonly emailArrivalTime?: string;
    readonly spamReportForDisplay?: string;
    readonly hasAttachment?: boolean;
    readonly documentUploaderName?: string;
    readonly documentUploaderEmail?: string;
}
export namespace VoucherInboxItem {
    export type FilterTypeEnum = 'UNKNOWN' | 'EHF' | 'EHF_WITH_PREDICTIONS' | 'EFO_NELFO' | 'EFO_NELFO_WITH_PREDICTIONS' | 'INVOICE' | 'PDF_INVOICE' | 'PDF_RECEIPT' | 'PDF_CREDIT_NOTE' | 'ERROR_EHF_IMPORT' | 'REPLAYABLE_VOUCHER' | 'REMINDER_SPECIFICATION' | 'PDF_INVOICE_PREDICTIONS';
    export const FilterTypeEnum = {
        Unknown: 'UNKNOWN' as FilterTypeEnum,
        Ehf: 'EHF' as FilterTypeEnum,
        EhfWithPredictions: 'EHF_WITH_PREDICTIONS' as FilterTypeEnum,
        EfoNelfo: 'EFO_NELFO' as FilterTypeEnum,
        EfoNelfoWithPredictions: 'EFO_NELFO_WITH_PREDICTIONS' as FilterTypeEnum,
        Invoice: 'INVOICE' as FilterTypeEnum,
        PdfInvoice: 'PDF_INVOICE' as FilterTypeEnum,
        PdfReceipt: 'PDF_RECEIPT' as FilterTypeEnum,
        PdfCreditNote: 'PDF_CREDIT_NOTE' as FilterTypeEnum,
        ErrorEhfImport: 'ERROR_EHF_IMPORT' as FilterTypeEnum,
        ReplayableVoucher: 'REPLAYABLE_VOUCHER' as FilterTypeEnum,
        ReminderSpecification: 'REMINDER_SPECIFICATION' as FilterTypeEnum,
        PdfInvoicePredictions: 'PDF_INVOICE_PREDICTIONS' as FilterTypeEnum
    };
}


