/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoucherStatusBuilder { 
    companyId?: number;
    voucherId?: number;
    status?: number;
    type?: number;
    timestamp?: string;
    processOwner?: number;
}

