/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WageTransactionBuilder { 
    companyId?: number;
    comment?: string;
    historical?: boolean;
    payrollTaxCalcMethod?: string;
}

