/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WageCodeBuilder { 
    companyId?: number;
    number?: string;
    name?: string;
    description?: string;
    inactive?: boolean;
    hourlistRestrictAccess?: boolean;
    showInHourlist?: boolean;
    forceTaxPercentageDeduction?: boolean;
}

