/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';
import { SalaryV2Supplement } from './salaryV2Supplement';


export interface WageSpecificationTemplate { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    description?: string;
    wageCodeId: number;
    /**
     * StarDate
     */
    startDate: string;
    /**
     * EndDate
     */
    endDate?: string;
    type: number;
    amount?: number;
    percentage?: number;
    maxPaymentAmount?: number;
    wageSpecificationExtra?: SalaryV2Supplement;
}

