/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WootricPropertiesDTO } from './wootricPropertiesDTO';


export interface WootricDTO { 
    readonly email?: string;
    readonly external_id?: string;
    readonly created_at?: number;
    readonly product_name?: string;
    readonly cesToken?: string;
    readonly npsToken?: string;
    readonly language?: string;
    properties?: WootricPropertiesDTO;
    readonly thankYouMessageMain?: string;
    readonly thankYouMessageSetup?: string;
}

