/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';


export interface WorkingHoursScheme { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    /**
     * Defines the working hours scheme option.
     */
    workingHoursScheme: WorkingHoursScheme.WorkingHoursSchemeEnum;
    nameNO?: string;
    code?: string;
}
export namespace WorkingHoursScheme {
    export type WorkingHoursSchemeEnum = 'NOT_SHIFT' | 'ROUND_THE_CLOCK' | 'SHIFT_365' | 'OFFSHORE_336' | 'CONTINUOUS' | 'OTHER_SHIFT' | 'NOT_CHOSEN';
    export const WorkingHoursSchemeEnum = {
        NotShift: 'NOT_SHIFT' as WorkingHoursSchemeEnum,
        RoundTheClock: 'ROUND_THE_CLOCK' as WorkingHoursSchemeEnum,
        Shift365: 'SHIFT_365' as WorkingHoursSchemeEnum,
        Offshore336: 'OFFSHORE_336' as WorkingHoursSchemeEnum,
        Continuous: 'CONTINUOUS' as WorkingHoursSchemeEnum,
        OtherShift: 'OTHER_SHIFT' as WorkingHoursSchemeEnum,
        NotChosen: 'NOT_CHOSEN' as WorkingHoursSchemeEnum
    };
}


