/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface YearEndReportPost { 
    readonly groupNumber?: string;
    readonly grouping?: string;
    readonly post?: string;
    readonly subPost?: string;
    readonly name?: string;
    readonly technicalName?: string;
    readonly info?: string;
    readonly sumAmount?: number;
    readonly sumAmountPreviousYear?: number;
    readonly balanceIn?: number;
    isExcludeFromTaxReturn?: boolean;
}

