/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Change } from './change';
import { ShareholderRegisterSubmissionResult } from './shareholderRegisterSubmissionResult';


export interface YearEndShareholderRegister { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    readonly year?: number;
    sentDate?: string;
    status?: YearEndShareholderRegister.StatusEnum;
    submissionInProgress?: boolean;
    submissionAttemptDate?: string;
    submissionResult?: ShareholderRegisterSubmissionResult;
}
export namespace YearEndShareholderRegister {
    export type StatusEnum = 'STARTED' | 'UPDATED' | 'RESTARTED' | 'REJECTED' | 'SUBMITTED_UNSIGNED' | 'SUBMITTED_SIGNED' | 'USER_MARKED_AS_SIGNEDBYALL' | 'SYSTEM_MARKED_AS_SIGNEDBYALL';
    export const StatusEnum = {
        Started: 'STARTED' as StatusEnum,
        Updated: 'UPDATED' as StatusEnum,
        Restarted: 'RESTARTED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        SubmittedUnsigned: 'SUBMITTED_UNSIGNED' as StatusEnum,
        SubmittedSigned: 'SUBMITTED_SIGNED' as StatusEnum,
        UserMarkedAsSignedbyall: 'USER_MARKED_AS_SIGNEDBYALL' as StatusEnum,
        SystemMarkedAsSignedbyall: 'SYSTEM_MARKED_AS_SIGNEDBYALL' as StatusEnum
    };
}


