/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YearEndReport } from './yearEndReport';
import { Change } from './change';
import { YearEndAnnualAccountsFreeNoteLastModifiedInfo } from './yearEndAnnualAccountsFreeNoteLastModifiedInfo';


export interface YearEndAnnualAccountsFreeNote { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    yearEndReport?: YearEndReport;
    checked?: boolean;
    displayName?: string;
    numerated?: number;
    sortOrder?: number;
    content?: string;
    grouping?: string;
    lastModifiedInfo?: YearEndAnnualAccountsFreeNoteLastModifiedInfo;
}

