/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZendeskChatMetaDTO { 
    readonly apiKey?: string;
    readonly name?: string;
    readonly email?: string;
    readonly locale?: string;
    readonly departments?: Array<string>;
    readonly tags?: Array<string>;
}

