/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZendeskSearchResult { 
    readonly id?: number;
    readonly title?: string;
    readonly url?: string;
}

