/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Currency } from './currency';
import { Change } from './change';


export interface ZtlAccount { 
    id?: number;
    version?: number;
    readonly changes?: Array<Change>;
    readonly url?: string;
    name?: string;
    account: Account;
    readonly bban?: string;
    readonly iban?: string;
    currency?: Currency;
    readonly availableBalanceCurrency?: number;
    readonly bookedBalanceCurrency?: number;
    /**
     * Last time the account information was updated, mainly balance.
     */
    readonly lastUpdated?: string;
    readonly deletable?: boolean;
}

