/**
 * Tripletex API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZtlAccount } from './ztlAccount';
import { ZtlEmployee } from './ztlEmployee';


export interface ZtlSettingsData { 
    readonly bankName?: string;
    readonly bankId?: number;
    readonly accounts?: Array<ZtlAccount>;
    readonly employees?: Array<ZtlEmployee>;
}

